#pragma once
typedef enum UP_CENTER_DOWN_TYPE
{
	UP_CDENTER_DOWN_TYPE_CDENTER,
	UP_CDENTER_DOWN_TYPE_DOWN,
	UP_CDENTER_DOWN_TYPE_UP
}UP_CDENTER_DOWN_TYPE;

typedef enum NORM_QUIET_SELENT_TYPE
{
	NORM_QUIET_SELENT_TYPE_NORM,
	NORM_QUIET_SELENT_TYPE_QUIET,
	NORM_QUIET_SELENT_TYPE_SELENT
}NORM_QUIET_SELENT_TYPE;


typedef enum OFF_ARM_TYPE
{
	OFF_ARM_TYPE_OFF,
	OFF_ARM_TYPE_ARM
}OFF_ARM_TYPE;




typedef enum ARM_OFF_SIMULATE_TYPE
{
	ARM_OFF_SIMULATE_TYPE_ARM,
	ARM_OFF_SIMULATE_TYPE_OFF,
	ARM_OFF_SIMULATE_TYPE_SIMULATE
}ARM_OFF_SIMULATE_TYPE;



typedef enum HDG_SEL_ATT_HOLD_STRG_SEL_TYPE
{
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_HDGSEL,
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_ATTHOLD,
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_STRGSEL,
}HDG_SEL_ATT_HOLD_STRG_SEL_TYPE;


typedef enum ALT_HOLD_AP_OFF_ATT_HOLD_TYPE
{
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_ALT_HOLD,
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_AP_OFF,
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_ATT_HOLD,
}ALT_HOLD_AP_OFF_ATT_HOLD_TYPE;


typedef enum RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE
{
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_RTN,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_UP,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_DOWN,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_SEQ,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_NOT_PRESS
}RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE;


typedef enum DRIFT_NORM_WARN_RESET_TYPE
{
	DRIFT_NORM_WARN_RESET_TYPE_DRIFT,
	DRIFT_NORM_WARN_RESET_TYPE_NORM,
	DRIFT_NORM_WARN_RESET_TYPE_WARN_RESET
}DRIFT_NORM_WARN_RESET_TYPE;


typedef enum DOWN_UP_NOT_PRESS_TYPE
{
	DOWN_UP_NOT_PRESS_TYPE_DOWN,
	DOWN_UP_NOT_PRESS_TYPE_UP,
	DOWN_UP_NOT_PRESS_TYPE_NOT_PRESS
}DOWN_UP_NOT_PRESS_TYPE;

typedef enum GAIN_LVL_AUTO_TYPE
{
	GAIN_LVL_AUTO_TYPE_GAIN,
	GAIN_LVL_AUTO_TYPE_LVL,
	GAIN_LVL_AUTO_TYPE_AUTO
}GAIN_LVL_AUTO_TYPE;

typedef enum ILS_TCN_TCN_NAV_ILS_NAV_TYPE
{
	ILS_TCN,
	TCN,
	NAV,
	ILS_NAV
}ILS_TCN_TCN_NAV_ILS_NAV_TYPE;


typedef enum TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE
{
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_TEST,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_FORM,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_RSVR,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_INT_WING,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_EXT_WING,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_EXT_CENTER
}TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE;

typedef enum NORM_WING_FIRST_TYPE
{
	NORM_WING_FIRST_TYPE_NORM,
	NORM_WING_FIRST_TYPE_WING_FIRST
}NORM_WING_FIRST_TYPE;


typedef enum ELECT_PNEU_TYPE {
	ELECT_PNEU_TYPE_ELECT,
	ELECT_PNEU_TYPE_PNEU
}ELECT_PNEU_TYPE;


typedef enum DOWN_UP_TYPE
{
	DOWN_UP_TYPE_DOWN,
	DOWN_UP_TYPE_UP
}DOWN_UP_TYPE;



typedef enum OFF_ENABLE_TYPE
{
	OFF_ENABLE_TYPE_OFF,
	OFF_ENABLE_TYPE_ENABLE
}OFF_ENABLE_TYPE;

typedef enum OFF_ON_ANTI_SKID_TYPE
{
	OFF_ON_ANTI_SKID_TYPE_OFF,
	OFF_ON_ANTI_SKID_TYPE_ON,
	OFF_ON_ANTI_SKID_TYPE_ANTI_SKID
}OFF_ON_ANTI_SKID_TYPE;

typedef enum CHAN_1_CHAN_2_TYPE
{
	CHAN_1_CHAN_2_TYPE_CHAN_1,
	CHAN_1_CHAN_2_TYPE_CHAN_2,
}CHAN_1_CHAN_2_TYPE;


typedef enum OFF_LANDING_TAXI_TYPE
{
	OFF_LANDING_TAXI_TYPE_OFF,
	OFF_LANDING_TAXI_TYPE_LANDING,
	OFF_LANDING_TAXI_TYPE_TAXI
}OFF_LANDING_TAXI_TYPE;


typedef enum CAT_1_CAT_2_TYPE
{
	CAT_1_CAT_2_TYPE_CAT1,
	CAT_1_CAT_2_TYPE_CAT2
}CAT_1_CAT_2_TYPE;


typedef enum BIT_1_2_3_4_TYPE
{
	BIT_1_2_3_4_TYPE_1,
	BIT_1_2_3_4_TYPE_2,
	BIT_1_2_3_4_TYPE_3,
	BIT_1_2_3_4_TYPE_4
}BIT_1_2_3_4_TYPE;


typedef enum OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE
{
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_OFF,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_STBY,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_MAN,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_SEMI,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_AUTO,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_BYP
}OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE;

typedef enum A_3_2_TYPE
{
	A_3_2_TYPE_A,
	A_3_2_TYPE_3,
	A_3_2_TYPE_2
}A_3_2_TYPE;






typedef enum NUM_0_25_50_75_TYPE
{
	NUM_0_25_50_75_TYPE_0,
	NUM_0_25_50_75_TYPE_25,
	NUM_0_25_50_75_TYPE_50,
	NUM_0_25_50_75_TYPE_75
}NUM_0_25_50_75_TYPE;


typedef enum OFF_MAIN_BOTH_ADF_TYPE
{
	OFF_MAIN_BOTH_ADF_TYPE_OFF,
	OFF_MAIN_BOTH_ADF_TYPE_MAIN,
	OFF_MAIN_BOTH_ADF_TYPE_BOTH,
	OFF_MAIN_BOTH_ADF_TYPE_ADF
}OFF_MAIN_BOTH_ADF_TYPE;

typedef enum MNL_PRESET_GRD_TYPE
{

	MNL_PRESET_GRD_TYPE_MNL,
	MNL_PRESET_GRD_TYPE_PRESET,
	MNL_PRESET_GRD_TYPE_GRD
}MNL_PRESET_GRD_TYPE;



typedef enum T_TONE_TYPE
{
	T_TONE_TYPE_T,
	T_TONE_TYPE_TONE
}T_TONE_TYPE;


typedef enum OFF_SQL_GD_TYPE
{
	OFF_SQL_GD_TYPE_OFF,
	OFF_SQL_GD_TYPE_SQL,
	OFF_SQL_GD_TYPE_GD
}OFF_SQL_GD_TYPE;



typedef enum OFF_MBIT_STBY_ON_TYPE
{
	OFF_MBIT_STBY_ON_TYPE_OFF,
	OFF_MBIT_STBY_ON_TYPE_MBIT,
	OFF_MBIT_STBY_ON_TYPE_STBY,
	OFF_MBIT_STBY_ON_TYPE_ON
}OFF_MBIT_STBY_ON_TYPE;

typedef enum NUM_1_2_3_TYPE
{
	NUM_1_2_3_TYPE_1,
	NUM_1_2_3_TYPE_2,
	NUM_1_2_3_TYPE_3

}NUM_1_2_3_TYPE;

typedef enum NUM_1_2_3_4_TYPE
{
	NUM_1_2_3_4_TYPE_1,
	NUM_1_2_3_4_TYPE_2,
	NUM_1_2_3_4_TYPE_3,
	NUM_1_2_3_4_TYPE_4
}NUM_1_2_3_4_TYPE;


typedef enum OFF_NORM_TYPE {

	OFF_NORM_TYPE_OFF,
	OFF_NORM_TYPE_NORM
}OFF_NORM_TYPE;


typedef enum MAN_AUTO_TYPE
{
	MAN_AUTO_TYPE_MAN,
	MAN_AUTO_TYPE_AUTO
}MAN_AUTO_TYPE;


typedef enum OFF_MAIN_PWR_BATT_TYPE
{
	OFF_MAIN_PWR_BATT_TYPE_OFF,
	OFF_MAIN_PWR_BATT_TYPE_MAIN_PWR,
	OFF_MAIN_PWR_BATT_TYPE_BATT
}OFF_MAIN_PWR_BATT_TYPE;
typedef enum HUD_HMD_TYPE {
	F16_HUD,
	F16_HMD
}HUD_HMD_TYPE;

typedef enum EVENT_MAKR_RECORD_OFF_TYPE {
	EVENT_MARK,
	RECORD,
	DVR_RECORD_OFF
}EVENT_MAKR_RECORD_OFF_TYPE;
typedef enum AFT_LEFT_HUD_RIGHT_TYPE
{
	AFT_LEFT_HUD_RIGHT_TYPE_AFT,
	AFT_LEFT_HUD_RIGHT_TYPE_LEFT,
	AFT_LEFT_HUD_RIGHT_TYPE_HUD,
	AFT_LEFT_HUD_RIGHT_TYPE_RIGHT
}AFT_LEFT_HUD_RIGHT_TYPE;


typedef enum OFF_MASTER_TYPE
{
	OFF_MASTER_TYPE_OFF,
	OFF_MASTER_TYPE_MASTER
}OFF_MASTER_TYPE;


typedef enum OFF_TANK_INERTING_TYPE
{
	OFF_TANK_INERTING_TYPE_OFF,
	OFF_TANK_INERTING_TYPE_TANKINERTING
}OFF_TANK_INERTING_TYPE;



typedef enum OFF_NORM_AFT_FWD_TYPE
{
	OFF_NORM_AFT_FWD_TYPE_OFF,
	OFF_NORM_AFT_FWD_TYPE_NORM,
	OFF_NORM_AFT_FWD_TYPE_AFT,
	OFF_NORM_AFT_FWD_TYPE_FWD
}OFF_NORM_AFT_FWD_TYPE;


typedef enum CLOSE_OPEN_TYPE
{
	CLOSE_OPEN_TYPE_CLOSE,
	CLOSE_OPEN_TYPE_OPEN
}CLOSE_OPEN_TYPE;

typedef enum OFF_SYBY_LOW_NORM_EMER_TYPE
{
	CLOSE_OPEN_TYPE_OFF,
	CLOSE_OPEN_TYPE_SYBY,
	CLOSE_OPEN_TYPE_LOW,
	CLOSE_OPEN_TYPE_NORM,
	CLOSE_OPEN_TYPE_EMER
}OFF_SYBY_LOW_NORM_EMER_TYPE;


typedef enum ZERO_A_B_HOLD_TYPE
{
	ZERO_A_B_HOLD_TYPE_ZERO,
	ZERO_A_B_HOLD_TYPE_A_B,
	ZERO_A_B_HOLD_TYPE_HOLD
}ZERO_A_B_HOLD_TYPE;



typedef enum BACK_UP_UFC_TYPE
{
	BACK_UP_UFC_TYPE_BACKUP,
	BACK_UP_UFC_TYPE_UFC
}BACK_UP_UFC_TYPE;

typedef enum M3_OFF_M1_TYPE {
	M_3,
	AUX_ENABLE_SWITCH_OFF,
	M_1
}M3_OFF_M1_TYPE;

typedef enum B_A_OUT_TYPE
{
	B_A_OUT_TYPE_B,
	B_A_OUT_TYPE_A,
	B_A_OUT_TYPE_OUT
}B_A_OUT_TYPE;


typedef enum AUDIO_OUT_TYPE
{
	AUDIO_OUT_TYPE_AUDIO,
	AUDIO_OUT_TYPE_OUT
}AUDIO_OUT_TYPE;


typedef enum NUM_0_1_TYPE
{
	NUM_0_1_TYPE_ZERO,
	NUM_0_1_TYPE_ONE
}NUM_0_1_TYPE;


typedef enum X_Y_TYPE
{
	X_Y_TYPE_X,
	X_Y_TYPE_Y
}X_Y_TYPE;

typedef enum T_R_A_A_TR_TYPE
{
	T_R_A_A_TR_TYPE_T_R,
	T_R_A_A_TR_TYPE_A_ATR
}T_R_A_A_TR_TYPE;


typedef enum OFF_1_2_3_4_A_B_C_TYPE
{
	OFF_1_2_3_4_A_B_C_TYPE_OFF,
	OFF_1_2_3_4_A_B_C_TYPE_One,
	OFF_1_2_3_4_A_B_C_TYPE_Two,
	OFF_1_2_3_4_A_B_C_TYPE_Three,
	OFF_1_2_3_4_A_B_C_TYPE_Four,
	OFF_1_2_3_4_A_B_C_TYPE_A,
	OFF_1_2_3_4_A_B_C_TYPE_B,
	OFF_1_2_3_4_A_B_C_TYPE_C
}OFF_1_2_3_4_A_B_C_TYPE;

typedef enum FLASH_STEADY_TYPE
{
	FLASH_STEADY_TYPE_FLASH,
	FLASH_STEADY_TYPE_STEADY
}FLASH_STEADY_TYPE;


typedef enum OFF_BRT_DIM_TYPE
{
	OFF_BRT_DIM_TYPE_OFF,
	OFF_BRT_DIM_TYPE_BRT,
	OFF_BRT_DIM_TYPE_DIM
}OFF_BRT_DIM_TYPE;



typedef enum OFF_ALL_A_C_FORM_NORM_TYPE
{
	OFF_ALL_A_C_FORM_NORM_TYPE_OFF,
	OFF_ALL_A_C_FORM_NORM_TYPE_ALL,
	OFF_ALL_A_C_FORM_NORM_TYPE_A_C,
	OFF_ALL_A_C_FORM_NORM_TYPE_FORM,
	OFF_ALL_A_C_FORM_NORM_TYPE_NORM
}OFF_ALL_A_C_FORM_NORM_TYPE;


typedef enum OFF_BACKUP_TYPE
{
	OFF_BACKUP_TYPE_OFF,
	OFF_BACKUP_TYPE_BACKUP
}OFF_BACKUP_TYPE;


typedef enum EXTEND_NORM_TYPE
{
	EXTEND_NORM_TYPE_EXTEND,
	EXTEND_NORM_TYPE_NORM
}EXTEND_NORM_TYPE;






typedef enum DISABLE_ENABLE_TYPE
{
	DISABLE_ENABLE_TYPE_DISABLE,
	DISABLE_ENABLE_TYPE_ENABLE
}DISABLE_ENABLE_TYPE;


typedef enum LOCK_AUTO_TYPE
{
	LOCK_AUTO_TYPE_LOCK,
	LOCK_AUTO_TYPE_AUTO
}LOCK_AUTO_TYPE;


typedef enum OFF_RESET_TYPE
{
	OFF_RESET_TYPE_OFF,
	OFF_RESET_TYPE_RESET
}OFF_RESET_TYPE;



typedef enum OFF_BIT_TYPE
{
	OFF_BIT_TYPE_OFF,
	OFF_BIT_TYPE_BIT
}OFF_BIT_TYPE;


typedef enum NORM_DISC_TYPE
{
	NORM_DISC_TYPE_NORM,
	NORM_DISC_TYPE_DISC
}NORM_DISC_TYPE;

typedef enum OFF_OXY_OTY_TYPE
{
	OFF_OXY_OTY_TYPE_OFF,
	OFF_OXY_OTY_TYPE_OXY_OTY
}OFF_OXY_OTY_TYPE;

typedef enum OFF_EPU_GEN_TYPE
{
	OFF_EPU_GEN_TYPE_OFF,
	OFF_EPU_GEN_TYPE_EPU_GNE

}OFF_EPU_GEN_TYPE;


typedef enum OFF_PROBE_HEAT_TEST_TYPE
{
	OFF_PROBE_HEAT_TEST_TYPE_OFF,
	OFF_PROBE_HEAT_TEST_TYPE_PROBEHEAT,
	OFF_PROBE_HEAT_TEST_TYPE_TEST
}OFF_PROBE_HEAT_TEST_TYPE;

typedef enum OFF_OFF_EPU_GEN_TYPE
{
	OFF_OFF_EPU_GEN_TYPE_OFF,
	OFF_OFF_EPU_GEN_TYPE_EPU_GEN
}OFF_OFF_EPU_GEN_TYPE;

typedef enum AFT_FWD_TYPE
{
	AFT_FWD_TYPE_TYPE_AFT,
	AFT_FWD_TYPE_TYPE_FWD,
}AFT_FWD_TYPE;

typedef enum TEST_NORM_MAINT_TYPE
{
	TEST_NORM_MAINT_TYPE_TEST,
	TEST_NORM_MAINT_TYPE_NORM,
	TEST_NORM_MAINT_TYPE_MAINT
}TEST_NORM_MAINT_TYPE;

typedef enum OFF_START1_START2_TYPE
{
	OFF_START1_START2_TYPE_OFF,
	OFF_START1_START2_TYPE_START1,
	OFF_START1_START2_TYPE_START2
}OFF_START1_START2_TYPE;


typedef enum PRI_SEC_TYPE
{
	PRI_SEC_TYPE_PRI,
	PRI_SEC_TYPE_SEC
}PRI_SEC_TYPE;



typedef enum AB_RESET_NORM_ENG_DATA_TYPE
{
	AB_RESET_NORM_ENG_DATA_TYPE_ABRESET,
	AB_RESET_NORM_ENG_DATA_TYPE_NORM,
	AB_RESET_NORM_ENG_DATA_TYPE_ENGDATA
}AB_RESET_NORM_ENG_DATA_TYPE;


typedef enum OFF_MAX_POWER_TYPE
{
	OFF_MAX_POWER_TYPE_OFF,
	OFF_MAX_POWER_TYPE_MAXPOWER
}OFF_MAX_POWER_TYPE;

typedef enum OFF_ON_NORMAL_TYPE
{
	OFF_ON_NORMAL_TYPE_OFF,
	OFF_ON_NORMAL_TYPE_ON,
	OFF_ON_NORMAL_TYPE_NORMAL
}OFF_ON_NORMAL_TYPE;


typedef enum OFF_MIC_CIPHER_TYPE
{
	OFF_MIC_CIPHER_TYPE_OFF,
	OFF_MIC_CIPHER_TYPE_MIC,
	OFF_MIC_CIPHER_TYPE_CHPHER
}OFF_MIC_CIPHER_TYPE;


typedef enum CLOSE_LATCH_UNLATCH_OPEN_TYPE
{
	CLOSE_LATCH_UNLATCH_OPEN_TYPE_CLOSELATCH,
	CLOSE_LATCH_UNLATCH_OPEN_TYPE_UNLATCHOPEN
}CLOSE_LATCH_UNLATCH_OPEN_TYPE;



typedef enum NOT_EJECT_EJECT_TYPE
{
	NOT_EJECT_EJECT_TYPE_NOTEJECT,
	NOT_EJECT_EJECT_TYPE_EJECT
}NOT_EJECT_EJECT_TYPE;



typedef enum OVRD_NORM_TYPE
{
	OVRD_NORM_TYPE_OVRD,
	OVRD_NORM_TYPE_NORM
}OVRD_NORM_TYPE;



typedef enum MAN_RNG_UNCAGE_TYPE
{
	MAN_RNG_UNCAGE_TYPE_MANRNG,
	MAN_RNG_UNCAGE_TYPE_UNCAGE
}MAN_RNG_UNCAGE_TYPE;


typedef enum CURSOR_ENALBLE_TYPE
{
	CURSOR_ENALBLE_TYPE_CURSOR,
	CURSOR_ENALBLE_TYPE_ENALBLE
}CURSOR_ENALBLE_TYPE;



typedef enum FORWARD_BACKWARD_TYPE
{
	FORWARD_BACKWARD_TYPE_FORWARD,
	FORWARD_BACKWARD_TYPE_BACKWARD
}FORWARD_BACKWARD_TYPE;

typedef enum VHF_UHF_IN_OUT_TYPE
{
	VHF_UHF_IN_OUT_TYPE_VHF,
	VHF_UHF_IN_OUT_TYPE_UHF,
	VHF_UHF_IN_OUT_TYPE_IN,
	VHF_UHF_IN_OUT_TYPE_OUT
}VHF_UHF_IN_OUT_TYPE;


typedef enum NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE
{
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_NWS,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_RDISC,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_MSLSTEP,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_GTOGGLE,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_G,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_A
}NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE;


typedef enum FWD_AFT_LEFT_RIGHT_TYPE
{
	FWD_AFT_LEFT_RIGHT_TYPE_FWD,
	FWD_AFT_LEFT_RIGHT_TYPE_AFT,
	FWD_AFT_LEFT_RIGHT_TYPE_LEFT,
	FWD_AFT_LEFT_RIGHT_TYPE_RIGHT
}FWD_AFT_LEFT_RIGHT_TYPE;

typedef enum STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE
{


	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_STT_TTS,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_SAM,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_TWS,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_SMT_WITH_NO_BUG,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_ACM

}STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE;
typedef enum RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE
{
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_RWS,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_SAM,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_TWS,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_ACM,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_ACMboresight,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_A2G
}RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE;

typedef enum GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE
{
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_GRATERTHAN0_5SECOND,
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_TGP_EO,
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_HSDWITHDATALINK
}GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE;


typedef enum _1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE {
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_LESSTHAN1SECONDNOBUG,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_LESSTHAN1SECONDBUGGEDTARGET,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_IRWSGREATERTHAN1SECOND,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_ITWS_SMT,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_ACM,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_A2G
}_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE;


typedef enum _1_DETENT_2_DETENT_TYPE
{
	_1_DETENT_2_DETENT_TYPE_1_DETENT,
	_1_DETENT_2_DETENT_TYPE_2_DETENT
}_1_DETENT_2_DETENT_TYPE;


typedef enum OFF_VV_VAH_VAH_TYPE
{
	OFF_VV_VAH_VAH_TYPE_OFF,
	OFF_VV_VAH_VAH_TYPE_VVVAH,
	OFF_VV_VAH_VAH_TYPE_VAH
}OFF_VV_VAH_VAH_TYPE;


typedef enum OFF_ATT_FPM_FPM_TYPE
{
	OFF_ATT_FPM_FPM_TYPE_OFF,
	OFF_ATT_FPM_FPM_TYPE_ATT_FPM,
	OFF_ATT_FPM_FPM_TYPE_FPM
}OFF_ATT_FPM_FPM_TYPE;


typedef enum OFF_DED_DATA_PFL_TYPE
{
	OFF_DED_DATA_PFL_TYPE_OFF,
	OFF_DED_DATA_PFL_TYPE_DEDDATA,
	OFF_DED_DATA_PFL_TYPE_PFL
}OFF_DED_DATA_PFL_TYPE;


typedef enum OFF_STBY_PRI_TYPE
{
	OFF_STBY_PRI_TYPE_OFF,
	OFF_STBY_PRI_TYPE_STBY,
	OFF_STBY_PRI_TYPE_PRI
}OFF_STBY_PRI_TYPE;


typedef enum CAS_TA_GND_SPD_TYPE
{
	CAS_TA_GND_SPD_TYPE_CAS,
	CAS_TA_GND_SPD_TYPE_TAS,
	CAS_TA_GND_SPD_TYPE_GNDSPD
}CAS_TA_GND_SPD_TYPE;


typedef enum  ALT_RADAR_BARO_AUTO_TYPE
{
	ALT_RADAR_BARO_AUTO_TYPE_ALTRADAR,
	ALT_RADAR_BARO_AUTO_TYPE_BARO,
	ALT_RADAR_BARO_AUTO_TYPE_AUTO,
}ALT_RADAR_BARO_AUTO_TYPE;


typedef enum DAY_AUTO_BRT_NIGHT_TYPE
{
	DAY_AUTO_BRT_NIGHT_TYPE_DAY,
	DAY_AUTO_BRT_NIGHT_TYPE_AUTOBRT,
	DAY_AUTO_BRT_NIGHT_TYPE_NIGHT
}DAY_AUTO_BRT_NIGHT_TYPE;



typedef enum  OFF_TEST_STEP_ON_TYPE
{
	OFF_TEST_STEP_ON_TYPE_OFF,
	OFF_TEST_STEP_ON_TYPE_TESTSTEP,
	OFF_TEST_STEP_ON_TYPE_ON
}OFF_TEST_STEP_ON_TYPE;


typedef enum NORM_BRT_DIM_TYPE
{
	NORM_BRT_DIM_TYPE_NORM,
	NORM_BRT_DIM_TYPE_BRT,
	NORM_BRT_DIM_TYPE_DIM
}NORM_BRT_DIM_TYPE;

typedef enum OFF_MMC_TYPE {
	AVION_MMC_OFF,
	MMC
}OFF_MMC_TYPE;

typedef enum OFF_STA_TYPE {
	AVION_STA_OFF,
	STA
}OFF_STA_TYPE;







typedef enum OFF_NORM_DUMP_RAM_TYPE
{
	OFF_NORM_DUMP_RAM_TYPE_OFF,
	OFF_NORM_DUMP_RAM_TYPE_NORM,
	OFF_NORM_DUMP_RAM_TYPE_DUMP,
	OFF_NORM_DUMP_RAM_TYPE_RAM
}OFF_NORM_DUMP_RAM_TYPE;



typedef enum OFF_FCC_TYPE
{
	OFF_FCC_TYPE_OFF,
	OFF_FCC_TYPE_FCC
}OFF_FCC_TYPE;

typedef enum OFF_SMS_TYPE
{
	OFF_SMS_TYPE_OFF,
	OFF_SMS_TYPE_SMS
}OFF_SMS_TYPE;


typedef enum OFF_MFD_TYPE
{
	OFF_MFD_TYPE_OFF,
	OFF_MFD_TYPE_MFD
}OFF_MFD_TYPE;


typedef enum OFF_UFC_TYPE
{
	OFF_UFC_TYPE_OFF,
	OFF_UFC_TYPE_UFC
}OFF_UFC_TYPE;

typedef enum ZERO_OFF_ON_TYPE {
	AVION_MIDS_SWITCH_ZERO,
	AVION_MIDS_SWITCH_OFF,
	AVION_MIDS_SWITCH_ON
}ZERO_OFF_ON_TYPE;

typedef enum OFF_GES_TYPE {
	AVION_SWITCH_OFF,
	AVION_SWITCH_GES,
};


typedef enum OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE
{
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_OFF,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_STORHDG,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_NORM,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_NAV,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_CAL,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_INFLT,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_ATT
}OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE;

typedef enum OFF_GPS_TYPE
{
	OFF_GPS_TYPE_OFF,
	OFF_GPS_TYPE_GPS
}OFF_GPS_TYPE;


typedef enum OFF_DL_TYPE
{
	OFF_DL_TYPE_OFF,
	OFF_DL_TYPE_DL
}OFF_DL_TYPE;

typedef enum OFF_CPD_TYPE
{
	OFF_CPD_TYPE_OFF,
	OFF_CPD_TYPE_CPD
}OFF_CPD_TYPE;

typedef enum OFF_MAP_TYPE
{
	OFF_MAP_TYPE_OFF,
	OFF_MAP_TYPE_MAP
}OFF_MAP_TYPE;

typedef enum EMERGENCY_NORM_TEST_MASK_TYPE
{
	EMERGENCY_NORM_TEST_MASK_TYPE_EMERGENCY,
	EMERGENCY_NORM_TEST_MASK_TYPE_NORM,
	EMERGENCY_NORM_TEST_MASK_TYPE_TESTMASK
}EMERGENCY_NORM_TEST_MASK_TYPE;



typedef enum NORM_O2_TYPE
{
	NORM_O2_TYPE_NORM,
	NORM_O2_TYPE_O2
}NORM_O2_TYPE;

typedef enum PBG_ON_OFF_TYPE
{
	PBG_ON_OFF_TYPE_PBG,
	PBG_ON_OFF_TYPE_ON,
	PBG_ON_OFF_TYPE_OFF
}PBG_ON_OFF_TYPE;

typedef enum WHITE_BLACK_TYPE
{
	WHITE_BLACK_TYPE_WHITE,
	WHITE_BLACK_TYPE_BLACK

}WHITE_BLACK_TYPE;


typedef enum OFF_LEFT_HDPT_TYPE
{
	OFF_LEFT_HDPT_TYPE_OFF,
	OFF_LEFT_HDPT_TYPE_LEFTHDPT
}OFF_LEFT_HDPT_TYPE;

typedef enum OFF_RIGHT_HDPT_TYPE
{
	OFF_RIGHT_HDPT_TYPE_OFF,
	OFF_RIGHT_HDPT_TYPE_RIGHTHDPT
}OFF_RIGHT_HDPT_TYPE;

typedef enum OFF_FCR_TYPE
{
	OFF_FCR_TYPE_OFF,
	OFF_FCR_TYPE_FCR
}OFF_FCR_TYPE;


typedef enum OFF_RDR_ALT_STBY_TYPE
{
	OFF_RDR_ALT_STBY_TYPE_OFF,
	OFF_RDR_ALT_STBY_TYPE_RDRALT,
	OFF_RDR_ALT_STBY_TYPE_STBY
}OFF_RDR_ALT_STBY_TYPE;


typedef enum OFF_OFP_DATA_TYPE
{
	OFF_OFP_DATA_TYPE_OFF,
	OFF_OFP_DATA_TYPE_OFP,
	OFF_OFP_DATA_TYPE_DATA
}OFF_OFP_DATA_TYPE;



typedef enum INNIBIT_NORM_TYPE
{
	INNIBIT_NORM_TYPE_INNIBIT,
	INNIBIT_NORM_TYPE_NORM
}INNIBIT_NORM_TYPE;


typedef enum NORM_CARD1_CARD2_TYPE
{
	NORM_CARD1_CARD2_TYPE_NORM,
	NORM_CARD1_CARD2_TYPE_CARD1,
	NORM_CARD1_CARD2_TYPE_CARD2
}NORM_CARD1_CARD2_TYPE;

typedef enum OFF_ON_AUTO_TYPE
{
	OFF_ON_AUTO_TYPE_OFF,
	OFF_ON_AUTO_TYPE_ON,
	OFF_ON_AUTO_TYPE_AUTO
}OFF_ON_AUTO_TYPE;

typedef enum NORM_UPPER_LOWER_TYPE
{
	NORM_UPPER_LOWER_TYPE_NORM,
	NORM_UPPER_LOWER_TYPE_UPPER,
	NORM_UPPER_LOWER_TYPE_LOWER
}NORM_UPPER_LOWER_TYPE;
typedef enum ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE
{
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_ONE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_TWO,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_THREE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_FOUR,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_FIVE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_SIX,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_MAN,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_OFL,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_Z_ALL,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_REM,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_OFF,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_PT

}ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE;

typedef enum ON_OFF_TYPE { 
	OFF = 0,
	ON = 1
}ON_OFF_TYPE;

///////////////////////////////////////////////////////////////////////////////////
//기존 f-15 구조체
////////////////////////////////////////////////////////////////////////////////////////

typedef enum MTD_MODE_TYPE
{
	OFF_MODE = 0,
	PWR_MODE = 1,
	WAIT_MODE = 2,
	RUN_MODE = 3,
	INIT_MODE = 4,
	ORT_MODE = 5,
	FREEZE_MODE = 6,
	SIM_MODE = 7,
	FI_INIT_MODE = 8,
	FI_SEL_MODE = 9
} MTD_MODE_TYPE;

//typedef enum ON_OFF_TYPE {
//	OFF = 0, 
//	ON = 1
//}ON_OFF_TYPE;

typedef enum TF_TYPE
{
	TF_COUPLE = 0,
	TF_OFF = 1

}TF_TYPE;

typedef enum LEFT_RIGHT_NORMAL_TYPE
{
	CT_LEFT = 0,
	CT_NORMAL = 1,
	CT_RIGHT = 2

}LEFT_RIGHT_NORMAL_TYPE;

typedef enum AUTO_EMERG_TYPE
{
	EMERG_AUTO = 0,
	EMERG = 1
}AUTO_EMERG_TYPE;

typedef enum ANTI_SKID_TYPE
{
	ANTISKID_NORM = 0,
	ANTISKID_PULSER = 1,
	ANTISKID_OFF = 2
}ANTI_SKID_TYPE;

typedef enum LDG_TAXI_LIGHT_TYPE
{
	LDG_LDG_LIGHT = 0,
	LDG_OFF = 1,
	LDG_TAXI_LIGHT = 2 //name change
}LDG_TAXI_LIGHT_TYPE;

typedef enum FUEL_CONTROL_TYPE
{
	FUEL_CONTROL_STOP_TRANS = 0,
	FUEL_CONTROL_NORM = 1,
	FUEL_CONTROL_STOP_REFUEL = 2

}FUEL_CONTROL_TYPE;

typedef enum DUMP_TYPE
{
	DUMP = 0,
	DUMP_NORM = 1
}DUMP_TYPE;

typedef enum EXT_TRANS_TYPE
{
	CONF_TANK = 0,
	WING_CTR = 1,
}EXT_TRANS_TYPE;

typedef enum OPEN_CLOSE_ORIDE_TYPE
{
	SWITCH_ORIDE = 0,
	SWITCH_OEPN = 1,
	SWITCH_CLOSE = 2
}OPEN_CLOSE_ORIDE_TYPE;

typedef enum UP_DOWN_TYPE
{
	UP_DOWN__UP = 0,
	UP_DOWN__DOWN = 1
}UP_DOWN_TYPE;

typedef enum IFF_ANTENNA_TYPE
{
	IFF_ANTENNA_UPPER = 0,
	IFF_ANTENNA_BOTH = 1,
	IFF_ANTENNA_LOWER = 2
}IFF_ANTENNA_TYPE;

typedef enum CRYPTO_TYPE
{
	CRYPTO_HOLD = 0,
	CRYPTO_NORM = 1,
	CRYPTO_ZERO = 2
}CRYPTO_TYPE;

typedef enum ON_OFF_ORIDE_TYPE
{
	ORIDE_ON = 0,
	ORIDE_OFF = 1,
	ORIDE = 2
}ON_OFF_ORIDE_TYPE;

typedef enum RAD1_ANT_TYPE
{
	RAD1_ANT_UPPER = 0,
	RAD1_ANT_AUTO = 1,
	RAD1_ANT_LOWER = 2
}RAD1_ANT_TYPE;

typedef enum TONE_TYPE
{
	TONE_RAD1 = 0,
	TONE_OFF = 1,
	TONE_RAD2 = 2
}TONE_TYPE;

typedef enum CIPHER_TEXT_TYPE
{
	CIPHER_TEXT_ONLY = 0,
	CIPHER_TEXT_NORM = 1
}CIPHER_TEXT_TYPE;

typedef enum IFF_MODE_TYPE
{
	IFF_MODE_MODE_B = 0,
	IFF_MODE_MODE_A = 1,
	IFF_MODE_MODE_OUT = 2,
}IFF_MODE_TYPE;

typedef enum IFF_MASTER_TYPE
{
	IFF_MASTER_LOW = 0,
	IFF_MASTER_NORM = 1,
	IFF_MASTER_EMERG = 2
}IFF_MASTER_TYPE;

typedef enum IFF_LIGHT_TYPE
{
	IFF_LIGHT_LIGHT = 0,
	IFF_LIGHT_AUDIO_REC = 1,
	IFF_LIGHT_OFF = 2
}IFF_LIGHT_TYPE;

typedef enum ON_OFF_AUTO_TYPE
{
	AUTO_ON = 0, //A ON
	AUTO_AUTO = 1,
	AUTO_OFF = 2 //B ON
}ON_OFF_AUTO_TYPE;

typedef enum GROUND_PWR_TYPE
{
	GND_PWR_ON = 0,
	GND_PWR_AUTO = 1
}GROUND_PWR_TYPE;


typedef enum ON_OFF_RESET_TYPE
{
	RESET_ON = 0,
	RESET = 1,
	RESET_OFF = 2
}ON_OFF_RESET_TYPE;

/*typedef enum TF_TYPE
{
	TF_COUPLE = 0,
	TF_OFF = 1
}TF_TYPE;*/
// delete change on off type

typedef enum THROTTLE_POSITION_TYPE
{
	THROTTLE_OFF = 0,
	THROTTLE_MIL = 1,
	THROTTLE_MAX = 2,
	THROTTLE_IDLE = 3
}THROTTLE_POSITION_TYPE;

typedef enum POSITION_TYPE
{
	POSITION_FWD = 0,
	POSITION_CTR = 1,
	POSITION_AFT = 2
}POSITION_TYPE;

typedef enum MULTIFUNCTION_TYPE
{
	HAT_CENTER = 0,
	HAT_UP = 1,
	HAT_DOWN = 2,
	HAT_LEFT = 3,
	HAT_RIGHT = 4

}RIGHT_MULTIFUNCTION_TYPE;

typedef enum TARGET_DESIGNATOR_CONTROL_TYPE
{
	TDC_CENTER = 0,
	TDC_UP = 1,
	TDC_DOWN = 2,
	TDC_LEFT = 3,
	TDC_RIGHT = 4
}TARGET_DESIGNATOR_CONTROL_TYPE;

typedef enum CASTLE_TYPE
{
	CASTLE_CENTER = 0,
	CASTLE_PUSH = 1, //add 2019.01.02
	CASTLE_UP = 2,
	CASTLE_DOWN = 3,
	CASTLE_LEFT = 4,
	CASTLE_RIGHT = 5


}CASTLE_TYPE;

typedef enum STICK_POSITION_TYPE
{
	STICK_CENTER = 0, //
	STICK_UP_LIMIT = 1,
	STICK_DOWN_LIMIT = 2,
	STICK_LEFT_LIMIT = 3,
	STICK_RIGHT_LIMIT = 4,
	STICK_IGNORE = 5
}STICK_POSITION_TYPE;

typedef enum TRIM_TYPE
{
	TRIM_CENTER = 0,
	TRIM_PUSH = 1, //add 2019.01.02
	TRIM_UP = 2,
	TRIM_DOWN = 3,
	TRIM_LEFT = 4,
	TRIM_RIGHT = 5
}TRIM_TYPE;

typedef enum AUTO_ACQUISITION_TYPE
{
	AUTO_ACQUISITION_CENTER = 0,
	AUTO_ACQUISITION_FWD = 1,
	AUTO_ACQUISITION_AFT = 2,
	AUTO_ACQUISITION_DOWN = 3
	
}AUTO_ACQUISITION_TYPE;

typedef enum STICK_TRIGGER_TYPE
{
	TRIGGER_OFF = 0,
	TRIGGER_DVR = 1,
	TRIGGER_FIRE = 2
}STICK_TRIGGER_TYPE;


typedef enum EXTERIOR_LIGHT_TYPE
{
	EXTERIOR_LIGHT_OFF = 0,
	EXTERIOR_LIGHT_ONE = 1,
	EXTERIOR_LIGHT_TWO = 2,
	EXTERIOR_LIGHT_THREE = 3,
	EXTERIOR_LIGHT_FOUR = 4,
	EXTERIOR_LIGHT_FIVE = 5,
	EXTERIOR_LIGHT_BRT = 6,
	EXTERIOR_LIGHT_FLASH = 7
}EXTERIOR_LIGHT_TYPE;

typedef enum FORMATION_LIGHT_TYPE
{
	FORMATION_LIGHT_NORMAL = 0,
	FORMATION_LIGHT_NVIS = 1
}FORMATION_LIGHT_TYPE;

typedef enum VERT_TAIL_FLOOD_LIGHT_TYPE
{
	VERT_TAIL_FLOOD_LIGHT_BRT = 0,
	VERT_TAIL_FLOOD_LIGHT_DIM = 1,
	VERT_TAIL_FLOOD_LIGHT_OFF = 2
}VERT_TAIL_FLOOD_LIGHT_TYPE;

typedef enum ON_OFF_STBY_TYPE
{
	STBY_ON = 0,
	STBY = 1,
	STBY_OFF = 2
}ON_OFF_STBY_TYPE;

typedef enum RDR_ALT_TYPE
{
	RDRALT_OVERRIDE = 0,
	RDRALT_ON = 1,
	RDRALT_OFF = 2,

}RDR_ALT_TYPE;

typedef enum RADAR_MODE_TYPE
{
	RADAR_MODE_OFF = 0,
	RADAR_MODE_STBY = 1,
	RADAR_MODE_ON = 2,
	RADAR_MODE_EMERG = 3
}RADAR_MODE_TYPE;


typedef enum FDL_TYPE
{
	FDL_OFF = 0,
	FDL_POLL = 1,
	FDL_NORM = 2,
	FDL_SIL = 3,
	FDL_HOLD = 4
}FDL_TYPE;

typedef enum OPEN_NORM_TYPE
{
	NORM_OEPN = 0,
	NORM = 1
}OPEN_NORM_TYPE;

typedef enum SEAT_ARMAMENT_TYPE
{
	SEAT_ARMAMENT_SEAT = 0,
	SEAT_ARMAMENT_OVERRIDE = 1
}SEAT_ARMAMENT_TYPE;


typedef enum ANTI_FOG_TYPE
{
	ANTI_FOG_HOT = 0,
	ANTI_FOG_NORM = 1,
	ANTI_FOG_COLD = 2
}ANTI_FOG_TYPE;

typedef enum ON_OFF_TEST_TYPE
{
	TEST_ON = 0,
	TEST_OFF = 1,
	TEST_TEST = 2
}ON_OFF_TEST_TYPE;

typedef enum AIRCOND_TEMP_TYPE
{
	AIRCOND_TEMP_AUTO = 0,
	AIRCOND_TEMP_MAN = 1,
	AIRCOND_TEMP_OFF = 2
}AIRCOND_TEMP_TYPE;

typedef enum AIRCOND_FLOW_TYPE
{
	AIRCOND_FLOW_MAX = 0,
	AIRCOND_FLOW_NORM = 1,
	AIRCOND_FLOW_MIN = 2
}AIRCOND_FLOW_TYPE;

typedef enum AIR_SOURCE_TYPE
{
	FLOW_SWITCH_OFF = 0,
	FLOW_SWITCH_L_ENG = 1,
	FLOW_SWITCH_BOTH = 2,
	FLOW_SWITCH_R_ENG = 3
}AIR_SOURCE_TYPE;

typedef enum DAY_NIGHT_TYPE
{
	DN_DAY = 0,
	DN_NIGHT = 1,
	DN_AUTO = 2
}DAY_NIGHT_TYPE;

typedef enum RWR_COMBAT_TYPE
{
	RWR_SWITCH_COMBAT = 0,
	RWR_SWITCH_TRNG = 1
}RWR_COMBAT_TYPE;

typedef enum ICS_SWITCH_TYPE
{
	ICS_SWITCH_MAN = 0,
	ICS_SWITCH_AUTO = 1,
	ICS_SWITCH_STBY = 2
}ICS_SWITCH_TYPE;

typedef enum CMD_BYPASS_TYPE
{
	CMD_BYPASS_BYPASS = 0,
	CMD_BYPASS_ON = 1,
	CMD_BYPASS_OFF = 2
}CMD_BYPASS_TYPE;

typedef enum CMD_JETTISON_TYPE
{
	CMD_SWITCH_JETT = 0,
	CMD_SWITCH_NORM = 1
}CMD_JETTISON_TYPE;

typedef enum ENGINE_EMERG_TYPE
{
	ENGINE_EMERG_AUTO = 0,
	ENGINE_EMERG_MAN = 1,
	ENGINE_EMERG_ISOLATE = 2
}ENGINE_EMERG_TYPE;

typedef enum ENGINE_EXTPWR_TYPE
{
	ENGINE_EXTPWR_RESET = 0,
	ENGINE_EXTPWR_NORM = 1,
	ENGINE_EXTPWR_OFF = 2
}ENGINE_EXTPWR_TYPE;

typedef enum OXYGEN_EMERG_TYPE
{
	OXYGEN_EMERG_EMERG = 0,
	OXYGEN_EMERG_NORM = 1,
	OXYGEN_EMERG_TEST_MASK = 2
}OXYGEN_EMERG_TYPE;

typedef enum OXYGEN_TYPE
{
	OXY_MAX = 0,
	OXY_NORM = 1
}OXYGEN_TYPE;

typedef enum OXYGEN_SUPPLY_TYPE
{
	OXYGEN_SUPPLY_PBG = 0,
	OXYGEN_SUPPLY_ON = 1,
	OXYGEN_SUPPLY_OFF = 2
}OXYGEN_SUPPLY_TYPE;

typedef enum CANOPY_CONTROL_TYPE
{
	CANOPY_CTR_LOCKED = 0,
	CANOPY_CTR_DOWN = 1,
	CANOPY_CTR_HOLD = 2,
	CANOPY_CTR_UP

}CANOPY_CONTROL_TYPE;

typedef enum DISCHARGE_TYPE
{
	DISCHARGE_DISCHARGE = 0,
	DISCHARGE_OFF = 1,
	DISCHARGE_TEST = 2

}DISCHARGE_TYPE;

typedef enum ARMT_CONTROL_TYPE
{
	ARMT_CONTROLFF = 0,
	ARMT_CONTROLRET = 1,
	ARMT_CONTROLREL = 2,
	ARMT_CONTROLOFF = 3,
	ARMT_CONTROLCOMBAT = 4,
	ARMT_CONTROLA_A = 5,
	ARMT_CONTROLA_G = 6
}ARMT_CONTROL_TYPE;

typedef enum ARMT_TYPE
{
	ARMT_ARM = 0,
	ARMT_SAFE = 1
}ARMT_TYPE;

typedef enum PULL_PUSH_TYPE
{
	PULL = 0,
	PUSH = 1
}PULL_PUSH_TYPE;

// add 19. 01. 13
typedef enum JET_STARTER_TYPE
{
	JET_STARTER_SEC = 0,
	JET_STARTER_FIR = 1,
	JET_STARTER_NORM = 2
}JET_STARTER_TYPE;

typedef enum SYM_DECLUTTER_TYPE
{
	SYM_BRT_NORM = 0,
	SYM_BRT_REJ1 = 1,
	SYM_BRT_REJ2 = 2
}SYM_DECLUTTER_TYPE;

typedef enum FUEL_QTY_TYPE
{
	FUEL_QTY_BIT = 0,
	FUEL_QTY_FEED = 1,
	FUEL_QTY_INTL_WING = 2,
	FUEL_QTY_EXT_WING = 3,
	FUEL_QTY_EXT_CTR = 4,
	FUEL_QTY_CONF_TANL = 5
}FUEL_QTY_TYPE;

typedef enum ROTATION_TYPE
{
	ROTATION_NONE = 0,
	ROTATION_HORIZONTAL = 1,
	ROTATION_VERTICAL = 2

}ROTATION_TYPE;

typedef enum UFC_MODE_TYPE
{
	UFC_MODE_A_A = 0,
	UFC_MODE_A_G = 1,
	UFC_MODE_NAV = 2,
	UFC_MODE_INST = 3
}UFC_MODE_TYPE;

typedef enum UFC_PWR_MODE_TYPE
{
	UFC_PWR_OFF = 0,
	UFC_PWR_N = 1,
	UFC_PWR_D

}UFC_PWR_MODE_TYPE;

typedef enum Circuit_Breaker_Type
{
	CB_OPEN = 0,
	CB_CLOSE = 1

} Circuit_Breaker_Type;


typedef enum CANOPY_JETTISON_TYPE
{
	//CANOPY_JETTISON_UNLOCK = 0,
	CANOPY_JETTISON_PULL = 0,
	CANOPY_JETTISON_PUSH = 1
}CANOPY_JETTISON_TYPE;

typedef enum CANOPY_LOCK_TYPE
{
	CANOPY_LOCK = 0,
	CANOPY_UNLOCK = 1
}CANOPY_LOCK_TYPE;

typedef enum PULL_TO_CAGE_KNOB_TYPE
{
	PULL_TO_CAGE_OFF = 0,
	PULL_TO_CAGE_PULLED = 1
}PULL_TO_CAGE_KNOB_TYPE;

typedef enum FUEL_QTY_SELECT_TYPE
{
	BIT = 0,
	FEED = 1,
	INTL_WING = 2,
	TANK = 3,
	EXT_WING = 4,
	EXT_CTR = 5,
	CONF__TANK = 6
}FUEL_QTY_SELECT_TYPE;

typedef enum SOLENOID_COIL_TYPE
{
	JFS_START_SW = 0,
	DUMP_SW = 1,
	GND_PWR_1_SW = 2,
	GND_PWR_2_SW = 3,
	GND_PWR_3_SW = 4,
	GND_PWR_4_SW = 5,
	GND_PWR_PACS_SW = 6,
	GND_PWR_ADCP_AIU_SW = 7,
	ARMAMENT_SAFETY_OVERRIDE_SW = 8,
	ANTO_FOG_SW = 9,
	EMERG_GEN_SW = 10,
	SOLENOIDE_COIL_END
}SOLENOID_COIL_TYPE;