/* F-15K MTD HOST Program Data */
/*
Project		: F-15K MTD
File			: cockpit_type.h    
Developers	: HSD
Revision		: 14/08/22 Created
Purpose 		: F-15K MTD HOST Program   
memo			: cockpit_type.h     
*/

/*
@brief
 This module defines the variables of I/O enum Type.
*/ 


#pragma once

#pragma pack(push, 1)

//start

typedef  enum UP_CDENTER_DOWN_TYPE
{
	
	UP_CDENTER_DOWN_TYPE_DOWN,
	UP_CDENTER_DOWN_TYPE_UP,
	UP_CDENTER_DOWN_TYPE_CDENTER

}UP_CDENTER_DOWN_TYPE;

typedef enum NORM_QUIET_SELENT_TYPE
{
	NORM_QUIET_SELENT_TYPE_NORM,
	NORM_QUIET_SELENT_TYPE_QUIET,
	NORM_QUIET_SELENT_TYPE_SELENT
}NORM_QUIET_SELENT_TYPE;


typedef  enum OFF_ARM_TYPE
{
	OFF_ARM_TYPE_OFF,
	OFF_ARM_TYPE_ARM
}OFF_ARM_TYPE;




typedef  enum ARM_OFF_SIMULATE_TYPE
{
	ARM_OFF_SIMULATE_TYPE_ARM,
	ARM_OFF_SIMULATE_TYPE_OFF,
	ARM_OFF_SIMULATE_TYPE_SIMULATE
}ARM_OFF_SIMULATE_TYPE;



typedef  enum HDG_SEL_ATT_HOLD_STRG_SEL_TYPE
{
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_HDGSEL,
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_ATTHOLD,
	HDG_SEL_ATT_HOLD_STRG_SEL_TYPE_STRGSEL,
}HDG_SEL_ATT_HOLD_STRG_SEL_TYPE;


typedef  enum ALT_HOLD_AP_OFF_ATT_HOLD_TYPE
{
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_ALT_HOLD,
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_AP_OFF,
	ALT_HOLD_AP_OFF_ATT_HOLD_TYPE_ATT_HOLD,
}ALT_HOLD_AP_OFF_ATT_HOLD_TYPE;


typedef  enum RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE
{
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_RTN,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_UP,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_DOWN,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_SEQ,
	RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE_NOT_PRESS
}RTN_UP_DOWN_SEQ_NOT_PRESS_TYPE;


typedef  enum DRIFT_NORM_WARN_RESET_TYPE
{
	DRIFT_NORM_WARN_RESET_TYPE_DRIFT,
	DRIFT_NORM_WARN_RESET_TYPE_NORM,
	DRIFT_NORM_WARN_RESET_TYPE_WARN_RESET
}DRIFT_NORM_WARN_RESET_TYPE;


typedef  enum DOWN_UP_NOT_PRESS_TYPE
{
	DOWN_UP_NOT_PRESS_TYPE_DOWN,
	DOWN_UP_NOT_PRESS_TYPE_UP,
	DOWN_UP_NOT_PRESS_TYPE_NOT_PRESS
}DOWN_UP_NOT_PRESS_TYPE;

typedef  enum GAIN_LVL_AUTO_TYPE
{
	GAIN_LVL_AUTO_TYPE_GAIN,
	GAIN_LVL_AUTO_TYPE_LVL,
	GAIN_LVL_AUTO_TYPE_AUTO
}GAIN_LVL_AUTO_TYPE;

typedef enum ILS_TCN_TCN_NAV_ILS_NAV_TYPE
{
	ILS_TCN,
	TCN,
	NAV,
	ILS_NAV
}ILS_TCN_TCN_NAV_ILS_NAV_TYPE;


typedef enum TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE
{
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_TEST,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_FORM,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_RSVR,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_INT_WING,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_EXT_WING,
	TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE_EXT_CENTER
}TEST_FORM_RSVR_INT_WING_EXT_WING_EXT_CENTER_TYPE;

typedef enum NORM_WING_FIRST_TYPE
{
	NORM_WING_FIRST_TYPE_NORM,
	NORM_WING_FIRST_TYPE_WING_FIRST
}NORM_WING_FIRST_TYPE;

typedef enum ELECT_PNEU_TYPE
{
	ELECT_PNEU_TYPE_ELECT,
	ELECT_PNEU_TYPE_PNEU
}ELECT_PNEU_TYPE;


typedef enum DOWN_UP_TYPE
{
	DOWN_UP_TYPE_DOWN,
	DOWN_UP_TYPE_UP
};



typedef enum OFF_ENABLE_TYPE
{
	OFF_ENABLE_TYPE_OFF,
	OFF_ENABLE_TYPE_ENABLE
}OFF_ENABLE_TYPE;

typedef enum OFF_ON_ANTI_SKID_TYPE
{
	OFF_ON_ANTI_SKID_TYPE_OFF,
	OFF_ON_ANTI_SKID_TYPE_ON,
	OFF_ON_ANTI_SKID_TYPE_ANTI_SKID
}OFF_ON_ANTI_SKID_TYPE;

typedef enum CHAN_1_CHAN_2_TYPE
{
	CHAN_1_CHAN_2_TYPE_CHAN_1,
	CHAN_1_CHAN_2_TYPE_CHAN_2,
}CHAN_1_CHAN_2_TYPE;


typedef enum OFF_LANDING_TAXI_TYPE
{
	OFF_LANDING_TAXI_TYPE_OFF,
	OFF_LANDING_TAXI_TYPE_LANDING,
	OFF_LANDING_TAXI_TYPE_TAXI
}OFF_LANDING_TAXI_TYPE;


typedef enum CAT_1_CAT_2_TYPE
{
	CAT_1_CAT_2_TYPE_CAT1,
	CAT_1_CAT_2_TYPE_CAT2
}CAT_1_CAT_2_TYPE;


typedef enum BIT_1_2_3_4_TYPE
{
	BIT_1_2_3_4_TYPE_1,
	BIT_1_2_3_4_TYPE_2,
	BIT_1_2_3_4_TYPE_3,
	BIT_1_2_3_4_TYPE_4
}BIT_1_2_3_4_TYPE;


typedef enum OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE
{
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_OFF,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_STBY,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_MAN,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_SEMI,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_AUTO,
	OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE_BYP
}OFF_STBY_MAN_SEMI_AUTO_BYP_TYPE;

typedef  enum A_3_2_TYPE
{
	A_3_2_TYPE_A,
	A_3_2_TYPE_3,
	A_3_2_TYPE_2
}A_3_2_TYPE;






typedef  enum NUM_0_25_50_75_TYPE
{
	NUM_0_25_50_75_TYPE_0,
	NUM_0_25_50_75_TYPE_25,
	NUM_0_25_50_75_TYPE_50,
	NUM_0_25_50_75_TYPE_75
}NUM_0_25_50_75_TYPE;


typedef enum OFF_MAIN_BOTH_ADF_TYPE
{
	OFF_MAIN_BOTH_ADF_TYPE_OFF,
	OFF_MAIN_BOTH_ADF_TYPE_MAIN,
	OFF_MAIN_BOTH_ADF_TYPE_BOTH,
	OFF_MAIN_BOTH_ADF_TYPE_ADF
}OFF_MAIN_BOTH_ADF_TYPE;

typedef enum MNL_PRESET_GRD_TYPE
{

	MNL_PRESET_GRD_TYPE_MNL,
	MNL_PRESET_GRD_TYPE_PRESET,
	MNL_PRESET_GRD_TYPE_GRD
}MNL_PRESET_GRD_TYPE;



typedef enum T_TONE_TYPE
{
	T_TONE_TYPE_T,
	T_TONE_TYPE_TONE
}T_TONE_TYPE;


typedef enum OFF_SQL_GD_TYPE
{
	OFF_SQL_GD_TYPE_OFF,
	OFF_SQL_GD_TYPE_SQL,
	OFF_SQL_GD_TYPE_GD
}OFF_SQL_GD_TYPE;



typedef enum OFF_MBIT_STBY_ON_TYPE
{
	OFF_MBIT_STBY_ON_TYPE_OFF,
	OFF_MBIT_STBY_ON_TYPE_MBIT,
	OFF_MBIT_STBY_ON_TYPE_STBY,
	OFF_MBIT_STBY_ON_TYPE_ON
}OFF_MBIT_STBY_ON_TYPE;

typedef enum NUM_1_2_3_TYPE
{
	NUM_1_2_3_TYPE_1,
	NUM_1_2_3_TYPE_2,
	NUM_1_2_3_TYPE_3

}NUM_1_2_3_TYPE;

typedef enum NUM_1_2_3_4_TYPE
{
	NUM_1_2_3_4_TYPE_1,
	NUM_1_2_3_4_TYPE_2,
	NUM_1_2_3_4_TYPE_3,
	NUM_1_2_3_4_TYPE_4
}NUM_1_2_3_4_TYPE;


typedef enum OFF_NORM_TYPE
{

	OFF_NORM_TYPE_OFF,
	OFF_NORM_TYPE_NORM
}OFF_NORM_TYPE;


typedef enum MAN_AUTO_TYPE
{
	MAN_AUTO_TYPE_MAN,
	MAN_AUTO_TYPE_AUTO
}MAN_AUTO_TYPE;


typedef enum OFF_MAIN_PWR_BATT_TYPE
{
	OFF_MAIN_PWR_BATT_TYPE_OFF,
	OFF_MAIN_PWR_BATT_TYPE_MAIN_PWR,
	OFF_MAIN_PWR_BATT_TYPE_BATT
}OFF_MAIN_PWR_BATT_TYPE;
typedef enum HUD_HMD_TYPE
{
	F16_HUD,
	F16_HMD
}HUD_HMD_TYPE;

typedef enum EVENT_MAKR_RECORD_OFF_TYPE
{
	EVENT_MARK,
	RECORD,
	DVR_RECORD_OFF
}EVENT_MAKR_RECORD_OFF_TYPE;
typedef enum AFT_LEFT_HUD_RIGHT_TYPE
{
	AFT_LEFT_HUD_RIGHT_TYPE_AFT,
	AFT_LEFT_HUD_RIGHT_TYPE_LEFT,
	AFT_LEFT_HUD_RIGHT_TYPE_HUD,
	AFT_LEFT_HUD_RIGHT_TYPE_RIGHT
}AFT_LEFT_HUD_RIGHT_TYPE;


typedef enum OFF_MASTER_TYPE
{
	OFF_MASTER_TYPE_OFF,
	OFF_MASTER_TYPE_MASTER
};


typedef enum OFF_TANK_INERTING_TYPE
{
	OFF_TANK_INERTING_TYPE_OFF,
	OFF_TANK_INERTING_TYPE_TANKINERTING
};



typedef enum OFF_NORM_AFT_FWD_TYPE
{
	OFF_NORM_AFT_FWD_TYPE_OFF,
	OFF_NORM_AFT_FWD_TYPE_NORM,
	OFF_NORM_AFT_FWD_TYPE_AFT,
	OFF_NORM_AFT_FWD_TYPE_FWD
}OFF_NORM_AFT_FWD_TYPE;


typedef enum CLOSE_OPEN_TYPE
{
	CLOSE_OPEN_TYPE_CLOSE,
	CLOSE_OPEN_TYPE_OPEN
}CLOSE_OPEN_TYPE;

typedef enum OFF_SYBY_LOW_NORM_EMER_TYPE
{
	CLOSE_OPEN_TYPE_OFF,
	CLOSE_OPEN_TYPE_SYBY,
	CLOSE_OPEN_TYPE_LOW,
	CLOSE_OPEN_TYPE_NORM,
	CLOSE_OPEN_TYPE_EMER
}OFF_SYBY_LOW_NORM_EMER_TYPE;


typedef enum ZERO_A_B_HOLD_TYPE
{
	ZERO_A_B_HOLD_TYPE_ZERO,
	ZERO_A_B_HOLD_TYPE_A_B,
	ZERO_A_B_HOLD_TYPE_HOLD
}ZERO_A_B_HOLD_TYPE;



typedef enum BACK_UP_UFC_TYPE
{
	BACK_UP_UFC_TYPE_BACKUP,
	BACK_UP_UFC_TYPE_UFC
}BACK_UP_UFC_TYPE;

typedef enum M3_OFF_M1_TYPE
{
	M_3,
	AUX_ENABLE_SWITCH_OFF,
	M_1
}M3_OFF_M1_TYPE;

typedef enum B_A_OUT_TYPE
{
	B_A_OUT_TYPE_B,
	B_A_OUT_TYPE_A,
	B_A_OUT_TYPE_OUT
}B_A_OUT_TYPE;


typedef enum AUDIO_OUT_TYPE
{
	AUDIO_OUT_TYPE_AUDIO,
	AUDIO_OUT_TYPE_OUT
}AUDIO_OUT_TYPE;


typedef enum NUM_0_1_TYPE
{
	NUM_0_1_TYPE_ZERO,
	NUM_0_1_TYPE_ONE
}NUM_0_1_TYPE;


typedef enum X_Y_TYPE
{
	X_Y_TYPE_X,
	X_Y_TYPE_Y
}X_Y_TYPE;

typedef enum T_R_A_A_TR_TYPE
{
	T_R_A_A_TR_TYPE_T_R,
	T_R_A_A_TR_TYPE_A_ATR
}T_R_A_A_TR_TYPE;


typedef enum OFF_1_2_3_4_A_B_C_TYPE
{
	OFF_1_2_3_4_A_B_C_TYPE_OFF,
	OFF_1_2_3_4_A_B_C_TYPE_One,
	OFF_1_2_3_4_A_B_C_TYPE_Two,
	OFF_1_2_3_4_A_B_C_TYPE_Three,
	OFF_1_2_3_4_A_B_C_TYPE_Four,
	OFF_1_2_3_4_A_B_C_TYPE_A,
	OFF_1_2_3_4_A_B_C_TYPE_B,
	OFF_1_2_3_4_A_B_C_TYPE_C
}OFF_1_2_3_4_A_B_C_TYPE;

typedef enum FLASH_STEADY_TYPE
{
	FLASH_STEADY_TYPE_FLASH,
	FLASH_STEADY_TYPE_STEADY
}FLASH_STEADY_TYPE;


typedef enum OFF_BRT_DIM_TYPE
{
	OFF_BRT_DIM_TYPE_OFF,
	OFF_BRT_DIM_TYPE_BRT,
	OFF_BRT_DIM_TYPE_DIM
}OFF_BRT_DIM_TYPE;



typedef enum OFF_ALL_A_C_FORM_NORM_TYPE
{
	OFF_ALL_A_C_FORM_NORM_TYPE_OFF,
	OFF_ALL_A_C_FORM_NORM_TYPE_ALL,
	OFF_ALL_A_C_FORM_NORM_TYPE_A_C,
	OFF_ALL_A_C_FORM_NORM_TYPE_FORM,
	OFF_ALL_A_C_FORM_NORM_TYPE_NORM
}OFF_ALL_A_C_FORM_NORM_TYPE;


typedef enum OFF_BACKUP_TYPE
{
	OFF_BACKUP_TYPE_OFF,
	OFF_BACKUP_TYPE_BACKUP
}OFF_BACKUP_TYPE;


typedef enum EXTEND_NORM_TYPE
{
	EXTEND_NORM_TYPE_EXTEND,
	EXTEND_NORM_TYPE_NORM
}EXTEND_NORM_TYPE;






typedef enum DISABLE_ENABLE_TYPE
{
	DISABLE_ENABLE_TYPE_DISABLE,
	DISABLE_ENABLE_TYPE_ENABLE
}DISABLE_ENABLE_TYPE;


typedef enum LOCK_AUTO_TYPE
{
	LOCK_AUTO_TYPE_LOCK,
	LOCK_AUTO_TYPE_AUTO
};


typedef enum OFF_RESET_TYPE
{
	OFF_RESET_TYPE_OFF,
	OFF_RESET_TYPE_RESET
}OFF_RESET_TYPE;



typedef enum OFF_BIT_TYPE
{
	OFF_BIT_TYPE_OFF,
	OFF_BIT_TYPE_BIT
}OFF_BIT_TYPE;

typedef enum NORM_DISC_TYPE
{
	NORM_DISC_TYPE_NORM,
	NORM_DISC_TYPE_DISC
}NORM_DISC_TYPE;

typedef enum OFF_OXY_OTY_TYPE
{
	OFF_OXY_OTY_TYPE_OFF,
	OFF_OXY_OTY_TYPE_OXY_OTY
}OFF_OXY_OTY_TYPE;

typedef enum OFF_EPU_GEN_TYPE
{
	OFF_EPU_GEN_TYPE_OFF,
	OFF_EPU_GEN_TYPE_EPU_GNE

}OFF_EPU_GEN_TYPE;


typedef enum OFF_PROBE_HEAT_TEST_TYPE
{
	OFF_PROBE_HEAT_TEST_TYPE_OFF,
	OFF_PROBE_HEAT_TEST_TYPE_PROBEHEAT,
	OFF_PROBE_HEAT_TEST_TYPE_TEST
}OFF_PROBE_HEAT_TEST_TYPE;

typedef enum OFF_OFF_EPU_GEN_TYPE
{
	OFF_OFF_EPU_GEN_TYPE_OFF,
	OFF_OFF_EPU_GEN_TYPE_EPU_GEN
}OFF_OFF_EPU_GEN_TYPE;

typedef enum AFT_FWD_TYPE
{
	AFT_FWD_TYPE_TYPE_AFT,
	AFT_FWD_TYPE_TYPE_FWD,
}AFT_FWD_TYPE;

typedef enum TEST_NORM_MAINT_TYPE
{
	TEST_NORM_MAINT_TYPE_TEST,
	TEST_NORM_MAINT_TYPE_NORM,
	TEST_NORM_MAINT_TYPE_MAINT
}TEST_NORM_MAINT_TYPE;

typedef enum OFF_START1_START2_TYPE
{
	OFF_START1_START2_TYPE_OFF,
	OFF_START1_START2_TYPE_START1,
	OFF_START1_START2_TYPE_START2
}OFF_START1_START2_TYPE;


typedef enum PRI_SEC_TYPE
{
	PRI_SEC_TYPE_PRI,
	PRI_SEC_TYPE_SEC
}PRI_SEC_TYPE;



typedef enum AB_RESET_NORM_ENG_DATA_TYPE
{
	AB_RESET_NORM_ENG_DATA_TYPE_ABRESET,
	AB_RESET_NORM_ENG_DATA_TYPE_NORM,
	AB_RESET_NORM_ENG_DATA_TYPE_ENGDATA
}AB_RESET_NORM_ENG_DATA_TYPE;


typedef enum OFF_MAX_POWER_TYPE
{
	OFF_MAX_POWER_TYPE_OFF,
	OFF_MAX_POWER_TYPE_MAXPOWER
}OFF_MAX_POWER_TYPE;

typedef enum OFF_ON_NORMAL_TYPE
{
	OFF_ON_NORMAL_TYPE_OFF,
	OFF_ON_NORMAL_TYPE_ON,
	OFF_ON_NORMAL_TYPE_NORMAL
}OFF_ON_NORMAL_TYPE;


typedef enum OFF_MIC_CIPHER_TYPE
{
	OFF_MIC_CIPHER_TYPE_OFF,
	OFF_MIC_CIPHER_TYPE_MIC,
	OFF_MIC_CIPHER_TYPE_CHPHER
}OFF_MIC_CIPHER_TYPE;


typedef enum CLOSE_LATCH_UNLATCH_OPEN_TYPE
{
	CLOSE_LATCH_UNLATCH_OPEN_TYPE_CLOSELATCH,
	CLOSE_LATCH_UNLATCH_OPEN_TYPE_UNLATCHOPEN
}CLOSE_LATCH_UNLATCH_OPEN_TYPE;



typedef enum NOT_EJECT_EJECT_TYPE
{
	NOT_EJECT_EJECT_TYPE_NOTEJECT,
	NOT_EJECT_EJECT_TYPE_EJECT
}NOT_EJECT_EJECT_TYPE;



typedef enum OVRD_NORM_TYPE
{
	OVRD_NORM_TYPE_OVRD,
	OVRD_NORM_TYPE_NORM
}OVRD_NORM_TYPE;



typedef enum MAN_RNG_UNCAGE_TYPE
{
	MAN_RNG_UNCAGE_TYPE_MANRNG,
	MAN_RNG_UNCAGE_TYPE_UNCAGE
}MAN_RNG_UNCAGE_TYPE;


typedef enum CURSOR_ENALBLE_TYPE
{
	CURSOR_ENALBLE_TYPE_CURSOR,
	CURSOR_ENALBLE_TYPE_ENALBLE
}CURSOR_ENALBLE_TYPE;



typedef enum FORWARD_BACKWARD_TYPE
{
	FORWARD_BACKWARD_TYPE_FORWARD,
	FORWARD_BACKWARD_TYPE_BACKWARD
}FORWARD_BACKWARD_TYPE;

typedef enum VHF_UHF_IN_OUT_TYPE
{
	VHF_UHF_IN_OUT_TYPE_VHF,
	VHF_UHF_IN_OUT_TYPE_UHF,
	VHF_UHF_IN_OUT_TYPE_IN,
	VHF_UHF_IN_OUT_TYPE_OUT
}VHF_UHF_IN_OUT_TYPE;


typedef enum NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE
{
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_NWS,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_RDISC,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_MSLSTEP,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_GTOGGLE,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_G,
	NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE_A_A
}NWS_A_R_DISC_MS_L_STEP_A_G_TOGGLE_A_G_A_A_TYPE;


typedef enum FWD_AFT_LEFT_RIGHT_TYPE
{
	FWD_AFT_LEFT_RIGHT_TYPE_FWD,
	FWD_AFT_LEFT_RIGHT_TYPE_AFT,
	FWD_AFT_LEFT_RIGHT_TYPE_LEFT,
	FWD_AFT_LEFT_RIGHT_TYPE_RIGHT
}FWD_AFT_LEFT_RIGHT_TYPE;

typedef enum STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE
{
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_STT_TTS,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_SAM,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_TWS,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_SMT_WITH_NO_BUG,
	STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE_ACM

}STT_TTS_SAM_TWS_SMT_with_no_bug_ACM_TYPE;
typedef enum RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE
{
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_RWS,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_SAM,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_TWS,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_ACM,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_ACMboresight,
	RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE_A2G
}RWS_SAM_TWS_ACM_ACM_boresight_A2G_TYPE;

typedef enum GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE
{
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_GRATERTHAN0_5SECOND,
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_TGP_EO,
	GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE_HSDWITHDATALINK
}GRATER_THAN_0_5_SECOND_TGP_EO_HSD_WITH_DATALINK_TYPE;


typedef enum _1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE
{
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_LESSTHAN1SECONDNOBUG,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_LESSTHAN1SECONDBUGGEDTARGET,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_IRWSGREATERTHAN1SECOND,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_ITWS_SMT,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_ACM,
	_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE_A2G
}_1_SECOND_NO_BUG_1_SECOND_BUGGED_TARGET_IRWS_GREATER_ITWS_SMT_ACM_A2G_TYPE;


typedef enum _1_DETENT_2_DETENT_TYPE
{
	_1_DETENT_2_DETENT_TYPE_1_DETENT,
	_1_DETENT_2_DETENT_TYPE_2_DETENT
}_1_DETENT_2_DETENT_TYPE;


typedef enum OFF_VV_VAH_VAH_TYPE
{
	OFF_VV_VAH_VAH_TYPE_OFF,
	OFF_VV_VAH_VAH_TYPE_VVVAH,
	OFF_VV_VAH_VAH_TYPE_VAH
}OFF_VV_VAH_VAH_TYPE;


typedef enum OFF_ATT_FPM_FPM_TYPE
{
	OFF_ATT_FPM_FPM_TYPE_OFF,
	OFF_ATT_FPM_FPM_TYPE_ATT_FPM,
	OFF_ATT_FPM_FPM_TYPE_FPM
}OFF_ATT_FPM_FPM_TYPE;


typedef enum OFF_DED_DATA_PFL_TYPE
{
	OFF_DED_DATA_PFL_TYPE_OFF,
	OFF_DED_DATA_PFL_TYPE_DEDDATA,
	OFF_DED_DATA_PFL_TYPE_PFL
}OFF_DED_DATA_PFL_TYPE;


typedef enum OFF_STBY_PRI_TYPE
{
	OFF_STBY_PRI_TYPE_OFF,
	OFF_STBY_PRI_TYPE_STBY,
	OFF_STBY_PRI_TYPE_PRI
}OFF_STBY_PRI_TYPE;


typedef enum CAS_TA_GND_SPD_TYPE
{
	CAS_TA_GND_SPD_TYPE_CAS,
	CAS_TA_GND_SPD_TYPE_TAS,
	CAS_TA_GND_SPD_TYPE_GNDSPD
}CAS_TA_GND_SPD_TYPE;


typedef enum ALT_RADAR_BARO_AUTO_TYPE
{
	ALT_RADAR_BARO_AUTO_TYPE_ALTRADAR,
	ALT_RADAR_BARO_AUTO_TYPE_BARO,
	ALT_RADAR_BARO_AUTO_TYPE_AUTO,
}ALT_RADAR_BARO_AUTO_TYPE;


typedef enum DAY_AUTO_BRT_NIGHT_TYPE
{
	DAY_AUTO_BRT_NIGHT_TYPE_DAY,
	DAY_AUTO_BRT_NIGHT_TYPE_AUTOBRT,
	DAY_AUTO_BRT_NIGHT_TYPE_NIGHT
}DAY_AUTO_BRT_NIGHT_TYPE;



typedef enum OFF_TEST_STEP_ON_TYPE
{
	OFF_TEST_STEP_ON_TYPE_OFF,
	OFF_TEST_STEP_ON_TYPE_TESTSTEP,
	OFF_TEST_STEP_ON_TYPE_ON
}OFF_TEST_STEP_ON_TYPE;


typedef enum NORM_BRT_DIM_TYPE
{
	NORM_BRT_DIM_TYPE_NORM,
	NORM_BRT_DIM_TYPE_BRT,
	NORM_BRT_DIM_TYPE_DIM
}NORM_BRT_DIM_TYPE;

typedef enum OFF_MMC_TYPE
{
	AVION_MMC_OFF,
	MMC
}OFF_MMC_TYPE;

typedef enum OFF_STA_TYPE
{
	AVION_STA_OFF,
	STA
}OFF_STA_TYPE;

typedef enum OFF_NORM_DUMP_RAM_TYPE
{
	OFF_NORM_DUMP_RAM_TYPE_OFF,
	OFF_NORM_DUMP_RAM_TYPE_NORM,
	OFF_NORM_DUMP_RAM_TYPE_DUMP,
	OFF_NORM_DUMP_RAM_TYPE_RAM
}OFF_NORM_DUMP_RAM_TYPE;

typedef enum OFF_FCC_TYPE
{
	OFF_FCC_TYPE_OFF,
	OFF_FCC_TYPE_FCC
}OFF_FCC_TYPE;

typedef enum OFF_SMS_TYPE
{
	OFF_SMS_TYPE_OFF,
	OFF_SMS_TYPE_SMS
}OFF_SMS_TYPE;


typedef enum OFF_MFD_TYPE
{
	OFF_MFD_TYPE_OFF,
	OFF_MFD_TYPE_MFD
}OFF_MFD_TYPE;


typedef enum OFF_UFC_TYPE
{
	OFF_UFC_TYPE_OFF,
	OFF_UFC_TYPE_UFC
}OFF_UFC_TYPE;

typedef enum ZERO_OFF_ON_TYPE
{
	AVION_MIDS_SWITCH_ZERO,
	AVION_MIDS_SWITCH_OFF,
	AVION_MIDS_SWITCH_ON
}ZERO_OFF_ON_TYPE;

typedef enum OFF_GES_TYPE
{
	AVION_SWITCH_OFF,
	AVION_SWITCH_GES,
}OFF_GES_TYPE;


typedef enum OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE
{
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_OFF,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_STORHDG,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_NORM,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_NAV,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_CAL,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_INFLT,
	OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE_ATT
}OFF_STOR_HDG_NORM_NAV_CAL_IN_FLT_ATT_TYPE;

typedef enum OFF_GPS_TYPE
{
	OFF_GPS_TYPE_OFF,
	OFF_GPS_TYPE_GPS
}OFF_GPS_TYPE;


typedef enum OFF_DL_TYPE
{
	OFF_DL_TYPE_OFF,
	OFF_DL_TYPE_DL
}OFF_DL_TYPE;

typedef enum OFF_CPD_TYPE
{
	OFF_CPD_TYPE_OFF,
	OFF_CPD_TYPE_CPD
}OFF_CPD_TYPE;

typedef enum OFF_MAP_TYPE
{
	OFF_MAP_TYPE_OFF,
	OFF_MAP_TYPE_MAP
}OFF_MAP_TYPE;

typedef enum EMERGENCY_NORM_TEST_MASK_TYPE
{
	EMERGENCY_NORM_TEST_MASK_TYPE_EMERGENCY,
	EMERGENCY_NORM_TEST_MASK_TYPE_NORM,
	EMERGENCY_NORM_TEST_MASK_TYPE_TESTMASK
}EMERGENCY_NORM_TEST_MASK_TYPE;



typedef enum NORM_O2_TYPE
{
	NORM_O2_TYPE_NORM,
	NORM_O2_TYPE_O2
}NORM_O2_TYPE;

typedef enum PBG_ON_OFF_TYPE
{
	PBG_ON_OFF_TYPE_PBG,
	PBG_ON_OFF_TYPE_ON,
	PBG_ON_OFF_TYPE_OFF
}PBG_ON_OFF_TYPE;

typedef enum WHITE_BLACK_TYPE
{
	WHITE_BLACK_TYPE_WHITE,
	WHITE_BLACK_TYPE_BLACK

}WHITE_BLACK_TYPE;


typedef enum OFF_LEFT_HDPT_TYPE
{
	OFF_LEFT_HDPT_TYPE_OFF,
	OFF_LEFT_HDPT_TYPE_LEFTHDPT
}OFF_LEFT_HDPT_TYPE;

typedef enum OFF_RIGHT_HDPT_TYPE
{
	OFF_RIGHT_HDPT_TYPE_OFF,
	OFF_RIGHT_HDPT_TYPE_RIGHTHDPT
}OFF_RIGHT_HDPT_TYPE;

typedef enum OFF_FCR_TYPE
{
	OFF_FCR_TYPE_OFF,
	OFF_FCR_TYPE_FCR
}OFF_FCR_TYPE;


typedef enum OFF_RDR_ALT_STBY_TYPE
{
	OFF_RDR_ALT_STBY_TYPE_OFF,
	OFF_RDR_ALT_STBY_TYPE_RDRALT,
	OFF_RDR_ALT_STBY_TYPE_STBY
}OFF_RDR_ALT_STBY_TYPE;


typedef enum OFF_OFP_DATA_TYPE
{
	OFF_OFP_DATA_TYPE_OFF,
	OFF_OFP_DATA_TYPE_OFP,
	OFF_OFP_DATA_TYPE_DATA
}OFF_OFP_DATA_TYPE;



typedef enum INNIBIT_NORM_TYPE
{
	INNIBIT_NORM_TYPE_INNIBIT,
	INNIBIT_NORM_TYPE_NORM
}INNIBIT_NORM_TYPE;


typedef enum NORM_CARD1_CARD2_TYPE
{
	NORM_CARD1_CARD2_TYPE_NORM,
	NORM_CARD1_CARD2_TYPE_CARD1,
	NORM_CARD1_CARD2_TYPE_CARD2
}NORM_CARD1_CARD2_TYPE;

typedef enum OFF_ON_AUTO_TYPE
{
	OFF_ON_AUTO_TYPE_OFF,
	OFF_ON_AUTO_TYPE_ON,
	OFF_ON_AUTO_TYPE_AUTO
}OFF_ON_AUTO_TYPE;

typedef enum NORM_UPPER_LOWER_TYPE
{
	NORM_UPPER_LOWER_TYPE_NORM,
	NORM_UPPER_LOWER_TYPE_UPPER,
	NORM_UPPER_LOWER_TYPE_LOWER
}NORM_UPPER_LOWER_TYPE;




typedef enum ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE
{
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_ONE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_TWO,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_THREE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_FOUR,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_FIVE,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_SIX,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_MAN,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_OFL,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_Z_ALL,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_REM,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_OFF,
	ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE_PT

}ONE_TO_SIX_MAN_OFF_ZALL_REM_OFF_PT_TYPE;

///////////////////////////////////////////////////////////////////////////////////
//기존 f-15 구조체
////////////////////////////////////////////////////////////////////////////////////////

typedef enum VOICE_DATA
{
	MTD_ROGER_COPY,
	MTD_LOUD_AND_CLEAR,
	MTD_UHF_LOW_ANTENNA,
	MTD_UHF_UPPER_ANTENNA,
	MTD_UHF_ANTENNA_AUTO_MODE,
	MTD_UHF_GUARD_CHECK,
	MTD_VHF_LOW_ANTENNA,
	MTD_VHF_UPPER_ANTENNA,
	MTD_VHF_ANTENNA_AUTO_MODE,
	MTD_VHF_GUARD_CHECK,
	ROGER_COPY,
	SECURE_MODE,
	LOW_CHECK,
	SECURE_MODE_NOT,

	VOICE_END
}VOICE_DATA;

typedef enum MAIN_PWR_SW_TYPE
{
	PWR_OFF					= 0, 
	PWR_BATT					= 1,
	PWR_MAIN					= 2
} MAIN_PWR_SW_TYPE;

typedef enum LANDING_TAXI_LGT_SW_TYPE
{
	
	LDG_TAXI_LGT_TAXI			= 0,
	LDG_TAXI_LGT_OFF			= 1,
	LDG_TAXI_LGT_LANDING		= 2
} LANDING_TAXI_LGT_SW_TYPE;

/* Define the enumeration type for general switch. */
typedef enum FUEL_MASTER_SW_TYPE
{
	Fuel_Master_OFF				= 0,
	Master						= 1                        
} FUEL_MASTER_SW_TYPE;

/* Define the EX Fuel type for Norm, Wing_First */
typedef enum EXT_FUEL_TRANS_TYPE	
{
	Trans_Norm   					= 0,								
	Wing_First 					= 1

} EXT_FUEL_TRANS_TYPE;

/* Define the enumeration type for channel transfer switch. */
typedef enum CHNL_TRANS_SW_TYPE
{
	CHNL_TRANS_AUTO				= 0,
	CHNL_TRANS_OVRD				= 1
} CHNL_TRANS_SW_TYPE;


typedef enum APU_GEN_SW_TYPE
{
	APU_AUTO					= 0,
	APU_ON					= 1
}APU_GEN_SW_TYPE;

/* Define the enumeration type for tail wing switch. */
typedef enum BRT_DIM_SW_TYPE
{
	BRT_LIGHT_DIM				= 0,
	BRT_LIGHT_OFF				= 1,
	BRT_LIGHT_BRIGHT			= 2
} BRT_DIM_SW_TYPE;

/* Define the enumeration type for air source knob. */
typedef enum AIR_SRC_KNOB_TYPE
{
	AIR_SRC_OFF				= 0,
	AIR_SRC_NORM				= 1,
	AIR_SRC_DUMP				= 2,
	AIR_SRC_RAM				= 3
} AIR_SRC_KNOB_TYPE;

typedef enum STICK_TRIM_SW_TYPE
{
	TRIM_ACTIVE_OFF		= 0,
	TRIM_NORM				= 1,
	TRIM_DISC				= 2
} STICK_TRIM_SW_TYPE;

/* Define the enumeration type for anti-icing switch. */
typedef enum ANTI_ICE_SW_TYPE
{
	ANTI_ICE_OFF				= 0,
	ANTI_ICE_AUTO				= 1,
	ANTI_ICE_ON				= 2
	
} ANTI_ICE_SW_TYPE;

/* Define the enumeration type for ground jettison switch. */
typedef enum GND_JETT_SW_TYPE
{
	GND_JETT_OFF				= 0,
	GND_JETT_ENABLE			= 1
} GND_JETT_SW_TYPE;

typedef enum CAGE_KNOB_TYPE
{
	CAGE_PUSH					= 0,
	CAGE_PULL					= 1
} CAGE_KNOB_TYPE;

typedef enum HOT_FUEL_KNOB_TYPE
{
	HOT_FUEL_AUTO				= 0, 
	HOT_FUEL_FWD				= 1,
	HOT_FUEL_HOLD				= 2,
	HOT_FUEL_AFT				= 3
} HOT_FUEL_KNOB_TYPE;

typedef enum CMDS_QUIET_SW_TYPE
{
	SILENT			    = 0,
	QUIET                = 1,    
	RF_NORM				= 2
}CMDS_QUIET_SW_TYPE;

typedef enum IFF_MASTER_SW_TYPE
{
	MASTER_OFF		    = 0,
	MASTER_STBY			= 1,
	//MASTER_LOW		    = 2,
	MASTER_NORM		    = 2,
	MASTER_EMER		    = 3

}IFF_MASTER_SW_TYPE;

typedef enum IFF_M_4_CODE_SW_TYPE
{
	ZERO		    = 0,
	A_B			= 1,
	HOLD		    = 2
}IFF_M_4_CODE_SW_TYPE;

typedef enum EDTU_Control_Sw_TYPE
{
	EDTU_SW_OFF		= 0,
	EDTU_SW_ON		= 1,
	EDTU_SW_CLR	    = 2

}EDTU_Control_Sw_TYPE;

typedef enum CMDS_MODE_SW_TYPE
{
	CMDS_MODE_OFF		= 0,
	CMDS_MODE_STBY	= 1,
	CMDS_MODE_NORM	= 2,
	CMDS_MODE_BYPASS  = 3

}CMDS_MODE_SW_TYPE;

typedef enum LIGHT_MASTER_SW_TYPE
{
	LIGHT_MASTER_OFF		= 0,
	LIGHT_MASTER_ALL		= 1,
	LIGHT_MASTER_AC	    = 2,
	LIGHT_MASTER_FORM		= 3,
	LIGHT_MASTER_NORM		= 4

}LIGHT_MASTER_SW_TYPE;

typedef enum ANTI_COLLISION_SW_TYPE
{                              
	ANTI_SW_0		= 0,
	ANTI_SW_1		= 1,
	ANTI_SW_2    = 2,
	ANTI_SW_3		= 3,
	ANTI_SW_4		= 4,
	ANTI_SW_A		= 5,
	ANTI_SW_B		= 6,
	ANTI_SW_C	    = 7

}ANTI_COLLISION_SW_TYPE;

/* Define the enumeration type for antenna position. */
typedef enum ANTENNA_TYPE
{
	ANTENNA_LOWER				= 0,
	ANTENNA_NORM				= 1,
	ANTENNA_UPPER				= 2
} ANTENNA_TYPE;

typedef enum OXYGEN_SUPPLY_SW_TYPE
{
	OXYGEN_OFF		= 0,
	OXYGEN_ON			= 1,
	OXYGEN_PBG		= 2
}OXYGEN_SUPPLY_SW_TYPE;

typedef enum ECS_IBIT_SW_TYPE
{
	ECS_IBIT_OFF    = 0, 
	ECS_IBIT_RESET  = 1
}ECS_IBIT_SW_TYPE;

typedef enum OXYGEN_BIT_SW_TYPE
{
	OXY_OFF			= 0,
	OXY_BIT			= 1
}OXYGEN_BIT_SW_TYPE;

typedef enum APU_GENERATOR_SW_TYPE
{
	APU_OFF			= 0,
	APU_GEN			= 1
}APU_GENERATOR_SW_TYPE;

typedef enum PROBE_HEAT_TEST_SW_TYPE
{
	PROBE_OFF				= 0,
	PROBE_TEST_HEAT	    = 1 
}PROBE_HEAT_TEST_SW_TYPE;

typedef enum OXYGEN_SET_SW_TYPE
{
	OXYGEN_SET_TEST_MASK = 0,
	OXYGEN_SET_NORM = 1,
	OXYGEN_SET_EMER = 2

}OXYGEN_SET_SW_TYPE;

typedef enum MFD_DISP_Control_SW_TYPE
{
	DECOUPLE			= 0,
	COUPLE			= 1
}MFD_DISP_Control_SW_TYPE;
typedef enum ecs_mode_sw_type	
{
	ECS_MAN	   = 0,
	ECS_AUTO	   = 1,
	ECS_CLR     = 2   

} ecs_mode_sw_type;

/* Define the enumeration type for BRT/DIM style switch position */
typedef enum Caws_Light_Type  
{
	Caws_Light_DIM			= 0,
	Caws_Light_MID			= 1,
	Caws_Light_BRT			= 2

} Caws_Light_Type;
typedef enum FLCS_Test_Switch_Type			/* flcs test switch type */ 
{
	FLCS_MAINT	=	0,
	FLCS_NORM		=	1,
	FLCS_TEST		=	2

} FLCS_Test_Switch_Type;

typedef enum AFT_MISC_MASTER_ALM_SW_TYPE			
{
	MISC_AFT	=	0,
	MISC_OFF	=	1,
	MISC_FWD	=	2

} AFT_MISC_MASTER_ALM_SW_TYPE;

typedef enum STA_OVRD_SEL_TYPE					
{
	STA_OVRD_SEL_AFT				= 0,
	STA_OVRD_SEL_OFF			    = 1,
	STA_OVRD_SEL_FWD			    = 2
}STA_OVRD_SEL_TYPE;

/* Define the enumeration type for Radar ALT power switch position */
typedef enum rdr_alt_power_sw_type               
{
	RDR_ALT_OFF		= 0,  
	RDR_ALT_STBY		= 1,  
	RDR_ALT_ON		= 2  

} rdr_alt_power_sw_type;

typedef enum ALTN_FLAPS_Switch_Type		/* altn flaps switch type */ 
{
	FLAPS_NORM			= 0,
	FLAPS_EXTEND			= 1

} ALTN_FLAPS_Switch_Type;

typedef enum ARMT_CONSENT_SW_TYPE  
{
	Armt_Consent_Off			= 0,
	Armt_Consent				= 1,

} ARMT_CONSENT_SW_TYPE;

typedef enum MPD_TYPE
{
	FWD_LEFT_MPD = 0,
	FWD_RIGHT_MPD = 1,
	FWD_MPCD = 2,
	AFT_LEFT_MPD = 3,
	AFT_RIGHT_MPD = 4,
	AFT_LEFT_MPCD = 5,
	AFT_RIGHT_MPCD = 6,

	MPD_TYPE_TOT = 7
}MPD_TYPE;

typedef enum RCU_BTN_TYPE
{
	RCU_OSB1 = 0,
	RCU_OSB2,
	RCU_OSB3,
	RCU_OSB4,
	RCU_OSB5,
	RCU_OSB6,
	RCU_OSB7,
	RCU_OSB8,

	RCU_TOT

}RCU_BTN_TYPE;

 typedef enum BUTTON_TYPE
 {
 	RELEASE = 0,
 	DEPRESS = 1
 }BUTTON_TYPE;

typedef enum Circuit_Breaker_Type
{
	CB_OPEN		= 0,
	CB_CLOSE		= 1

} Circuit_Breaker_Type;

typedef enum RMFD_OSS_INDEX_TYPE
{

	MFD_1_OSB_T1	       = 0,   //RIGHT_MFD_OSB_1
	MFD_1_OSB_T2        = 1, 	//RIGHT_MFD_OSB_2
	MFD_1_OSB_T3        = 2, 	//RIGHT_MFD_OSB_3
	MFD_1_OSB_T4        = 3, 	//RIGHT_MFD_OSB_4
	MFD_1_OSB_T5        = 4, 	//RIGHT_MFD_OSB_5
	MFD_1_OSB_T6        = 5, 	//RIGHT_MFD_OSB_6
	MFD_1_OSB_R1        = 6, 	//RIGHT_MFD_OSB_7
	MFD_1_OSB_R2        = 7, 	//RIGHT_MFD_OSB_8
	MFD_1_OSB_R3        = 8, 	//RIGHT_MFD_OSB_9
	MFD_1_OSB_R4		  = 9, 	//RIGHT_MFD_OSB_10
	MFD_1_OSB_R5       = 10,	//RIGHT_MFD_OSB_11
	MFD_1_OSB_R6       = 11,	//RIGHT_MFD_OSB_12
	MFD_1_OSB_R7       = 12,	//RIGHT_MFD_OSB_13
	MFD_1_OSB_B6       = 13,	//RIGHT_MFD_OSB_14
	MFD_1_OSB_B5       = 14,	//RIGHT_MFD_OSB_15
	MFD_1_OSB_B4       = 15,	//RIGHT_MFD_OSB_16
	MFD_1_OSB_B3       = 16,	//RIGHT_MFD_OSB_17
	MFD_1_OSB_B2       = 17,	//RIGHT_MFD_OSB_18
	MFD_1_OSB_B1       = 18,	//RIGHT_MFD_OSB_19
	MFD_1_OSB_L7       = 19,	//RIGHT_MFD_OSB_20
	MFD_1_OSB_L6       = 20,	//RIGHT_MFD_OSB_21
	MFD_1_OSB_L5       = 21,	//RIGHT_MFD_OSB_22
	MFD_1_OSB_L4       = 22,	//RIGHT_MFD_OSB_23
	MFD_1_OSB_L3       = 23,	//RIGHT_MFD_OSB_24
	MFD_1_OSB_L2       = 24,	//RIGHT_MFD_OSB_25
	MFD_1_OSB_L1       = 25,	//RIGHT_MFD_OSB_26
	MFD_1_OSB_CON_UP   = 26,	//RIGHT_MFD_OSB_CON_UP
	MFD_1_OSB_CON_DN   = 27,	//RIGHT_MFD_OSB_CON_DOWN
	MFD_1_OSB_BRT_UP   = 28,	//RIGHT_MFD_OSB_BRT_UP
	MFD_1_OSB_BRT_DN   = 29,	//RIGHT_MFD_OSB_BRT_DOWN  
	MFD_1_OSB_TOT  	   = 30     //RIGHT_MFD_OSB_TOT	

}RMFD_OSS_INDEX_TYPE;

typedef enum LMFD_OSS_INDEX_TYPE
{
	MFD_2_OSB_T1	       = 0,   //LEFT_MFD_OSB_1
	MFD_2_OSB_T2        = 1, 	//LEFT_MFD_OSB_2
	MFD_2_OSB_T3        = 2, 	//LEFT_MFD_OSB_3
	MFD_2_OSB_T4        = 3, 	//LEFT_MFD_OSB_4
	MFD_2_OSB_T5        = 4, 	//LEFT_MFD_OSB_5
	MFD_2_OSB_T6        = 5, 	//LEFT_MFD_OSB_6
	MFD_2_OSB_R1        = 6, 	//LEFT_MFD_OSB_7
	MFD_2_OSB_R2        = 7, 	//LEFT_MFD_OSB_8
	MFD_2_OSB_R3        = 8, 	//LEFT_MFD_OSB_9
	MFD_2_OSB_R4       = 9, 	//LEFT_MFD_OSB_10
	MFD_2_OSB_R5       = 10,	//LEFT_MFD_OSB_11
	MFD_2_OSB_R6       = 11,	//LEFT_MFD_OSB_12
	MFD_2_OSB_R7       = 12,	//LEFT_MFD_OSB_13
	MFD_2_OSB_B6       = 13,	//LEFT_MFD_OSB_14
	MFD_2_OSB_B5       = 14,	//LEFT_MFD_OSB_15
	MFD_2_OSB_B4       = 15,	//LEFT_MFD_OSB_16
	MFD_2_OSB_B3       = 16,	//LEFT_MFD_OSB_17
	MFD_2_OSB_B2       = 17,	//LEFT_MFD_OSB_18
	MFD_2_OSB_B1       = 18,	//LEFT_MFD_OSB_19
	MFD_2_OSB_L7       = 19,	//LEFT_MFD_OSB_20
	MFD_2_OSB_L6       = 20,	//LEFT_MFD_OSB_21
	MFD_2_OSB_L5       = 21,	//LEFT_MFD_OSB_22
	MFD_2_OSB_L4       = 22,	//LEFT_MFD_OSB_23
	MFD_2_OSB_L3       = 23,	//LEFT_MFD_OSB_24
	MFD_2_OSB_L2       = 24,	//LEFT_MFD_OSB_25
	MFD_2_OSB_L1       = 25,	//LEFT_MFD_OSB_26
	MFD_2_OSB_CON_UP   = 26,	//LEFT_MFD_OSB_CON_UP
	MFD_2_OSB_CON_DN   = 27,	//LEFT_MFD_OSB_CON_DOWN
	MFD_2_OSB_BRT_UP   = 28,	//LEFT_MFD_OSB_BRT_UP
	MFD_2_OSB_BRT_DN   = 29,	//LEFT_MFD_OSB_BRT_DOWN  
	MFD_2_OSB_TOT  	   = 30   //LEFT_MFD_OSB_TOT	

}LMFD_OSS_INDEX_TYPE;


typedef enum NOT_PRESS_PRESS_TYPE
{
	NOT_PRESS,
	PRESS
}NOT_PRESS_PRESS_TYPE;

typedef enum FWD_CIRCUIT_BREAKER_TYPE
{
	FWD_CB_AFCS_ESS_DC_A1 = 0,
	FWD_CB_AFCS_ESS_DC_A2,
	FWD_CB_AFCS_ESS_DC_A3,
	FWD_CB_LG,
	FWD_CB_NWS,
	FWD_CB_SPD_BRK,
	FWD_CB_L_PITOT_HEAT,
	FWD_CB_R_PITOT_HEAT,
	FWD_CB_AFCS_ESS_AC_B1,
	FWD_CB_AFCS_ESS_AC_B2,
	FWD_CB_FLAP,
	FWD_CB_AFCS_DC_B4,
	FWD_CB_AFCS_DC_B5,
	FWD_CB_AFCS_DC_B6,

	FWD_TOTAL
}FWD_CIRCUIT_BREAKER_TYPE;

typedef enum LEFT_CIRCUIT_BREAKER_TYPE
{
	_IRST_AC_A1 = 0,
	_IRST_AC_A2,
	_IRST_AC_A3,
	_JHMCS_A4,
	_L_WING_XFR_PUMP_AC_B1,
	_L_WING_XFR_PUMP_AC_B2,
	_L_WING_XFR_PUMP_AC_B3,
	_JHMCS_B4,
	_FWD_LCFT_XFR_PUMP_C1,
	_FWD_LCFT_XFR_PUMP_C2,
	_FWD_LCFT_XFR_PUMP_C3,
	_JHMCS_C4,
	_LCFT_XFR_PUMP_AC_D1,
	_LCFT_XFR_PUMP_AC_D2,
	_LCFT_XFR_PUMP_AC_D3,
	_MPD_L_AFT_E1,
	_MPD_L_AFT_E2,
	_MPD_L_AFT_E3,
	_UFC_AC_E4,
	_MPD_L_FWD_F1,
	_MPD_L_FWD_F2,
	_MPD_L_FWD_F3,
	_AOA_FWD_AS_AFT_F4,
	_EGI_F5,
	_MPD_R_AFT_G1,
	_MPD_R_AFT_G2,
	_MPD_R_AFT_G3,
	_VSI_FWD_G4,
	_PITOT_MAST_HTR_G5,
	_MPD_R_FWD_H1,
	_MPD_R_FWD_H2,
	_MPD_R_FWD_H3,
	_VSI_AFT_H4,
	_PITOT_L_HTR_H5,
	_HUD_J1,
	_HUD_J2,
	_HUD_J3,
	_INTERIOR_LTS_J4,
	_INSTR_LTS_J5,
	_RWR_AC_K1,
	_RWR_AC_K2,
	_RWR_AC_K3,
	_INTRFR_BLNKR_K5,
	_RWR_DC_L1,
	_ICS_CONT_L2,
	_L_WING_XFR_PUMP_DC_L3,
	_VTRS_DVR_M1,
	_CFT_LVL_CONT_M2,
	_LR_CFT_XFR_PMP_M3,
	_L_RUD_TRAV_LMTR_N1,
	_IRST_DC_N2,
	_EGI1_N3,
	_UFC_DC_P1,
	_HOT_FUEL_RECIRC_P2,
	_EISS_PWR_A_P3,
	_MAINT_DIAG_PANEL_Q1,
	_ENG_BURN_THRU_Q2,
	_EISS_PWR_B_Q3,
	_UTIL_FLOOD_LT_PWR_R2,

	LEFT_CB_TOTAL
}LEFT_CIRCUIT_BREAKER_TYPE;

typedef enum RIGHT_CIRCUIT_BREAKER_TYPE
{
	_AA_STA_3LCFT_STA3_A1,
	_AA_STA_3LCFT_STA3_A2,
	_AA_STA_3LCFT_STA3_A3,
	_AA_STA_3LCFT_STA3_PWR1_A4,
	_AA_STA_3LCFT_STA3_PWR2_A5,
	_AA_STA_4LCFT_STA1_B1,
	_AA_STA_4LCFT_STA1_B2,
	_AA_STA_4LCFT_STA1_B3,
	_AA_STA_4LCFT_STA1_PWR1_B4,
	_AA_STA_4LCFT_STA1_PWR2_B5,
	_AG_STA5_C1,
	_AG_STA5_C2,
	_AG_STA5_C3,
	_AG_STA5_PWR1_C4,
	_AG_STA5_PWR5_C5,
	_AA_STA_6LCFT_STA1_D1,
	_AA_STA_6LCFT_STA1_D2,
	_AA_STA_6LCFT_STA1_D3,
	_AA_STA_6LCFT_STA1_PWR1_D4,
	_AA_STA_6LCFT_STA1_PWR2_D5,
	_AA_STA_7LCFT_STA3_E1,
	_AA_STA_7LCFT_STA3_E2,
	_AA_STA_7LCFT_STA3_E3,
	_AA_STA_7LCFT_STA3_PWR1_E4,
	_AA_STA_7LCFT_STA3_PWR2_E5,
	_DMS_AC_F1,
	_DMS_AC_F2,
	_DMS_AC_F3,
	_DMS_DC_F4,
	_SET_ADJUST_AC_G1,
	_SET_ADJUST_AC_G2,
	_SET_ADJUST_AC_G3,
	_L_ENG_NOZL_POS_IND_G4,
	_R_ENG_NOZL_POS_IND_G5,
	_RCFT_AFT_PUMP_H1,
	_RCFT_AFT_PUMP_H2,
	_RCFT_AFT_PUMP_H3,
	_L_ENG_OIL_PRESS_H4,
	_R_ENG_OIL_PRESS_H5,
	_R_WING_XFR_PUMP_AC_J1,
	_R_WING_XFR_PUMP_AC_J2,
	_R_WING_XFR_PUMP_AC_J3,
	_INST_BUS_PRC_POS_J4,
	_INST_BUS_UTL_HYD_PRESS_IND_J5,
	_UTL_PWR_RECPT_K1,
	_26_VAC_AUTO_XFMR_K2,
	_R_DUCT_PITOT_HTR_K3,
	_DAS_EXT_SNSR_K4,
	_PC1_HYD_PRESS_IND_K5,
	_L_FUEL_FLOW_IND_L2,
	_PC2_HYD_PRESS_IND_L5,
	_FUEL_FLOW_IND_M2,
	_ENGINE_ANTI_ICE_M3,
	_WSHLD_ANTI_ICE_N1,
	_MPCD_L_AFT_N2,
	_RT_RAMP_CONT_N3,
	_UMB_RET_PWR_N5,
	_EGI2_P1,
	_MPCD_R_AFT_P2,
	_ICE_DET_P3,
	_GUN_TRIG_PWR_P5,
	_UTIL_RECPT_Q1,
	_SET_ADJUST_DC_Q2,
	_HOLDING_BRAKE_Q3,
	_MASTER_ARM_LOGIC_Q5,
	_LAST_ROUND_PWR_R1,
	_R_WING_XFR_PUMP_DC_R2,
	_AERP_R3,
	_AG_STA5_ARM_R5,

	RIGHT_CB_TOTAL

}RIGHT_CIRCUIT_BREAKER_TYPE;


typedef enum ESSENTIAL_CB_PANEL1_TYPE
{
	_ESS_PANEL1_L5,
	_ESS_PANEL1_M5,
	_ESS_PANEL1_N5,
	_ESS_PANEL1_A1_FUEL_PRESS_REG,
	_ESS_PANEL1_B1_ENVIR_CONT_SYS,
	_ESS_PANEL1_C1_CONF_TK_AFT_XFR_PUMPS,
	_ESS_PANEL1_D1_HOT_FUEL_GND_REFUEL,
	_ESS_PANEL1_E1_CONF_TK_LVL_CONT_NO_2,
	_ESS_PANEL1_F1_FUEL_LVL_SEN_UNIT,
	_ESS_PANEL1_G1_AERIAL_REFUELING,
	_ESS_PANEL1_H1_PRAD_CONT,
	_ESS_PANEL1_J1_INT_LTS_TEST,
	_ESS_PANEL1_K1_ECS_HT_EXCHGR,
	_ESS_PANEL1_L1_R_MLG_WOW_PWR,
	_ESS_PANEL1_M1_L_MLG_WOW_PWR,
	_ESS_PANEL1_N1_LDG_GR_POS_IND,
	_ESS_PANEL1_P1_LDG_GR_POS_WRN_TONE,
	_ESS_PANEL1_Q1_SKID_CONT_ARI_SHUT_OFF,
	_ESS_PANEL1_A2_ENG_CONT_ESS_DC_BUSS,
	_ESS_PANEL1_B2_BLEED_AIR_LEAK_DET_BK_PULSER,
	_ESS_PANEL1_C2_CIT,
	_ESS_PANEL1_D2_INTERCOM_PNL,
	_ESS_PANEL1_E2_EMER_JETT_NO_1,
	_ESS_PANEL1_F2_EMER_JETT_NO_2,
	_ESS_PANEL1_G2_EJECT_PWR_NO_1,
	_ESS_PANEL1_H2_EJECT_PWR_NO_2,
	_ESS_PANEL1_J2_CFT_AG_STORES_RELEASE,
	_ESS_PANEL1_K2_EGI1,
	_ESS_PANEL1_L2_DAS,
	_ESS_PANEL1_M2_SPARE,
	_ESS_PANEL1_N2_SPARE,
	_ESS_PANEL1_P2_SPARE,
	_ESS_PANEL1_Q2_SPARE,
	_ESS_PANEL1_A3_EMER_BST_PUMP_PWR,
	_ESS_PANEL1_B3_SPARE,
	_ESS_PANEL1_C3_LR_CONF_TK_FWD_XFR_PUMP,
	_ESS_PANEL1_D3_ESS_XFMR_RECT,
	_ESS_PANEL1_E3_STORM_FLOOD_LRS_FWD,
	_ESS_PANEL1_F3_L_ENG_LOW_ENGY_ING,
	_ESS_PANEL1_G3_R_ENG_LOW_ENGY_ING,
	_ESS_PANEL1_H3_ARR_FL_LTS,
	_ESS_PANEL1_J3_FWD_UFC,
	_ESS_PANEL1_K3_AFT_UFC,
	_ESS_PANEL1_L3_IFF_ZEROIZE,
	_ESS_PANEL1_M3_ARR_EMER_OPEN,
	_ESS_PANEL1_N3_ARG_CONT,
	_ESS_PANEL1_P3_ARG_SOL,
	_ESS_PANEL1_Q3_EMER_BST_PMP_CONT,
	_ESS_PANEL1_R3_AMAD_F_EXT_SYS,
	_ESS_PANEL1_A4_EMER_BST_PUMP_PWR,
	_ESS_PANEL1_B4_SPARE,
	_ESS_PANEL1_C4_LR_CONF_TK_FWD_XFR_PUMP,
	_ESS_PANEL1_D4,
	_ESS_PANEL1_E4,
	_ESS_PANEL1_F4,
	_ESS_PANEL1_G4,
	_ESS_PANEL1_H4,
	_ESS_PANEL1_J4,
	_ESS_PANEL1_K4,
	_ESS_PANEL1_L4,
	_ESS_PANEL1_M4,
	_ESS_PANEL1_N4,
	_ESS_PANEL1_P4,
	_ESS_PANEL1_Q4,
	_ESS_PANEL1_A5,
	_ESS_PANEL1_B5,
	_ESS_PANEL1_C5_LR_CONF_TK_FWD_XFR_PUMP,
	_ESS_PANEL1_D5,
	_ESS_PANEL1_E5,
	_ESS_PANEL1_F5,
	_ESS_PANEL1_G5,
	_ESS_PANEL1_H5,
	_ESS_PANEL1_J5,
	_ESS_PANEL1_K5,
	_ESS_PANEL1_P5,
	_ESS_PANEL1_Q5,
	_ESS_PANEL1_R5,

	ESS_PANEL1_CB_TOTAL
}ESSENTIAL_CB_PANEL1_TYPE;


typedef enum ESSENTIAL_CB_PANEL2_TYPE
{
	_ESS_PANEL2_A1,
	_ESS_PANEL2_B1,
	_ESS_PANEL2_C1,
	_ESS_PANEL2_D1,
	_ESS_PANEL2_E1,
	_ESS_PANEL2_F1,
	_ESS_PANEL2_G1,
	_ESS_PANEL2_H1,
	_ESS_PANEL2_J1,
	_ESS_PANEL2_K1,
	_ESS_PANEL2_L1,
	_ESS_PANEL2_A2,
	_ESS_PANEL2_B2,
	_ESS_PANEL2_C2,
	_ESS_PANEL2_D2,
	_ESS_PANEL2_E2,
	_ESS_PANEL2_F2,
	_ESS_PANEL2_G2,
	_ESS_PANEL2_H2,
	_ESS_PANEL2_J2,
	_ESS_PANEL2_K2,
	_ESS_PANEL2_L2,

	ESS_PANEL2_CB_TOTAL
}ESSENTIAL_CB_PANEL2_TYPE;

typedef enum LEFT_CB_PANEL1_TYPE
{
	_LEFT_PANEL1_1A,
	_LEFT_PANEL1_1B,
	_LEFT_PANEL1_1C,
	_LEFT_PANEL1_1D,
	_LEFT_PANEL1_1E,
	_LEFT_PANEL1_1F,
	_LEFT_PANEL1_1G,
	_LEFT_PANEL1_1H,
	_LEFT_PANEL1_1J,
	_LEFT_PANEL1_1K,
	_LEFT_PANEL1_1L,
	_LEFT_PANEL1_1M,
	_LEFT_PANEL1_1N,
	_LEFT_PANEL1_1P,
	_LEFT_PANEL1_1Q,
	_LEFT_PANEL1_1R,
	_LEFT_PANEL1_1S,
	_LEFT_PANEL1_1T,
	_LEFT_PANEL1_1V,
	_LEFT_PANEL1_1W,
	_LEFT_PANEL1_1X,
	_LEFT_PANEL1_1Y,
	_LEFT_PANEL1_1Z,
	_LEFT_PANEL1_2A,
	_LEFT_PANEL1_2B,
	_LEFT_PANEL1_2C,
	_LEFT_PANEL1_2D,
	_LEFT_PANEL1_2E,
	_LEFT_PANEL1_2F,
	_LEFT_PANEL1_2G,
	_LEFT_PANEL1_2H,
	_LEFT_PANEL1_2J,
	_LEFT_PANEL1_2K,
	_LEFT_PANEL1_2L,
	_LEFT_PANEL1_2M,
	_LEFT_PANEL1_2N,
	_LEFT_PANEL1_2P,
	_LEFT_PANEL1_2Q,
	_LEFT_PANEL1_2R,
	_LEFT_PANEL1_2S,
	_LEFT_PANEL1_2T,
	_LEFT_PANEL1_2V,
	_LEFT_PANEL1_2W,
	_LEFT_PANEL1_2X,
	_LEFT_PANEL1_2Y,
	_LEFT_PANEL1_2Z,
	_LEFT_PANEL1_3A,
	_LEFT_PANEL1_3B,
	_LEFT_PANEL1_3C,
	_LEFT_PANEL1_3D,
	_LEFT_PANEL1_3E,
	_LEFT_PANEL1_3F,
	_LEFT_PANEL1_3G,
	_LEFT_PANEL1_3H,
	_LEFT_PANEL1_3J,
	_LEFT_PANEL1_3K,
	_LEFT_PANEL1_3L,
	_LEFT_PANEL1_3M,
	_LEFT_PANEL1_3N,
	_LEFT_PANEL1_3P,
	_LEFT_PANEL1_3Q,
	_LEFT_PANEL1_3R,
	_LEFT_PANEL1_3S,
	_LEFT_PANEL1_3T,
	_LEFT_PANEL1_3V,
	_LEFT_PANEL1_3W,
	_LEFT_PANEL1_3X,
	_LEFT_PANEL1_3Y,
	_LEFT_PANEL1_3Z,
	_LEFT_PANEL1_4A,
	_LEFT_PANEL1_4B,
	_LEFT_PANEL1_4C,
	_LEFT_PANEL1_4D,
	_LEFT_PANEL1_4E,
	_LEFT_PANEL1_4F,
	_LEFT_PANEL1_4G,
	_LEFT_PANEL1_4H,
	_LEFT_PANEL1_4J,
	_LEFT_PANEL1_4K,
	_LEFT_PANEL1_4L,
	_LEFT_PANEL1_4M,
	_LEFT_PANEL1_4N,
	_LEFT_PANEL1_4P,
	_LEFT_PANEL1_4Q,
	_LEFT_PANEL1_4R,
	_LEFT_PANEL1_4S,
	_LEFT_PANEL1_4T,
	_LEFT_PANEL1_4V,
	_LEFT_PANEL1_4W,
	_LEFT_PANEL1_4X,
	_LEFT_PANEL1_4Y,
	_LEFT_PANEL1_4Z,
	_LEFT_PANEL1_5A,
	_LEFT_PANEL1_5B,
	_LEFT_PANEL1_5C,
	_LEFT_PANEL1_5D,
	_LEFT_PANEL1_5E,
	_LEFT_PANEL1_5F,
	_LEFT_PANEL1_5G,
	_LEFT_PANEL1_5H,
	_LEFT_PANEL1_5J,
	_LEFT_PANEL1_5K,
	_LEFT_PANEL1_5L,
	_LEFT_PANEL1_5M,
	_LEFT_PANEL1_5N,
	_LEFT_PANEL1_5P,
	_LEFT_PANEL1_5Q,
	_LEFT_PANEL1_5R,
	_LEFT_PANEL1_5S,
	_LEFT_PANEL1_5T,
	_LEFT_PANEL1_5V,
	_LEFT_PANEL1_5W,
	_LEFT_PANEL1_5X,
	_LEFT_PANEL1_5Y,
	_LEFT_PANEL1_5Z,

	LEFT_PANEL1_CB_TOTAL
}LEFT_CB_PANEL1_TYPE;


typedef enum RIGHT_CB_PANEL1_TYPE
{
	_RIGHT_PANEL1_1A,
	_RIGHT_PANEL1_1B,
	_RIGHT_PANEL1_1C,
	_RIGHT_PANEL1_1D,
	_RIGHT_PANEL1_1E,
	_RIGHT_PANEL1_1F,
	_RIGHT_PANEL1_1G,
	_RIGHT_PANEL1_1H,
	_RIGHT_PANEL1_1J,
	_RIGHT_PANEL1_1K,
	_RIGHT_PANEL1_1L,
	_RIGHT_PANEL1_1M,
	_RIGHT_PANEL1_1N,
	_RIGHT_PANEL1_1P,
	_RIGHT_PANEL1_1Q,
	_RIGHT_PANEL1_2A,
	_RIGHT_PANEL1_2B,
	_RIGHT_PANEL1_2C,
	_RIGHT_PANEL1_2D,
	_RIGHT_PANEL1_2E,
	_RIGHT_PANEL1_2F,
	_RIGHT_PANEL1_2G,
	_RIGHT_PANEL1_2H,
	_RIGHT_PANEL1_2J,
	_RIGHT_PANEL1_2K,
	_RIGHT_PANEL1_2L,
	_RIGHT_PANEL1_2M,
	_RIGHT_PANEL1_2N,
	_RIGHT_PANEL1_2P,
	_RIGHT_PANEL1_2Q,
	_RIGHT_PANEL1_3A,
	_RIGHT_PANEL1_3B,
	_RIGHT_PANEL1_3C,
	_RIGHT_PANEL1_3D,
	_RIGHT_PANEL1_3E,
	_RIGHT_PANEL1_3F,
	_RIGHT_PANEL1_3G,
	_RIGHT_PANEL1_3H,
	_RIGHT_PANEL1_3J,
	_RIGHT_PANEL1_3K,
	_RIGHT_PANEL1_3L,
	_RIGHT_PANEL1_3M,
	_RIGHT_PANEL1_3N,
	_RIGHT_PANEL1_3P,
	_RIGHT_PANEL1_3Q,
	_RIGHT_PANEL1_4A,
	_RIGHT_PANEL1_4B,
	_RIGHT_PANEL1_4C,
	_RIGHT_PANEL1_4D,
	_RIGHT_PANEL1_4E,
	_RIGHT_PANEL1_4F,
	_RIGHT_PANEL1_4G,
	_RIGHT_PANEL1_4H,
	_RIGHT_PANEL1_4J,
	_RIGHT_PANEL1_4K,
	_RIGHT_PANEL1_4L,
	_RIGHT_PANEL1_4M,
	_RIGHT_PANEL1_4N,
	_RIGHT_PANEL1_4P,
	_RIGHT_PANEL1_4Q,
	_RIGHT_PANEL1_5A,
	_RIGHT_PANEL1_5B,
	_RIGHT_PANEL1_5C,
	_RIGHT_PANEL1_5D,
	_RIGHT_PANEL1_5E,
	_RIGHT_PANEL1_5F,
	_RIGHT_PANEL1_5G,
	_RIGHT_PANEL1_5H,
	_RIGHT_PANEL1_5J,
	_RIGHT_PANEL1_5K,
	_RIGHT_PANEL1_5L,
	_RIGHT_PANEL1_5M,
	_RIGHT_PANEL1_5N,
	_RIGHT_PANEL1_5P,
	_RIGHT_PANEL1_5Q,
	_RIGHT_PANEL1_6A,
	_RIGHT_PANEL1_6B,
	_RIGHT_PANEL1_6C,
	_RIGHT_PANEL1_6D,
	_RIGHT_PANEL1_6E,
	_RIGHT_PANEL1_6F,
	_RIGHT_PANEL1_6G,
	_RIGHT_PANEL1_6H,
	_RIGHT_PANEL1_6J,
	_RIGHT_PANEL1_6K,
	_RIGHT_PANEL1_6L,
	_RIGHT_PANEL1_6M,
	_RIGHT_PANEL1_6N,
	_RIGHT_PANEL1_6P,
	_RIGHT_PANEL1_6Q,

	RIGHT_PANEL1_CB_TOTAL
}RIGHT_CB_PANEL1_TYPE;

typedef enum RIGHT_CB_PANEL2_TYPE
{
	_RIGHT_PANEL2_1A,
	_RIGHT_PANEL2_1B,
	_RIGHT_PANEL2_1C,
	_RIGHT_PANEL2_1D,
	_RIGHT_PANEL2_1E,
	_RIGHT_PANEL2_1F,
	_RIGHT_PANEL2_1G,
	_RIGHT_PANEL2_1H,
	_RIGHT_PANEL2_1J,
	_RIGHT_PANEL2_1K,
	_RIGHT_PANEL2_1L,
	_RIGHT_PANEL2_1M,
	_RIGHT_PANEL2_1N,
	_RIGHT_PANEL2_1P,
	_RIGHT_PANEL2_2A,
	_RIGHT_PANEL2_2B,
	_RIGHT_PANEL2_2C,
	_RIGHT_PANEL2_2D,
	_RIGHT_PANEL2_2E,
	_RIGHT_PANEL2_2F,
	_RIGHT_PANEL2_2G,
	_RIGHT_PANEL2_2H,
	_RIGHT_PANEL2_2J,
	_RIGHT_PANEL2_2K,
	_RIGHT_PANEL2_2L,
	_RIGHT_PANEL2_2M,
	_RIGHT_PANEL2_2N,
	_RIGHT_PANEL2_2P,
	_RIGHT_PANEL2_3A,
	_RIGHT_PANEL2_3B,
	_RIGHT_PANEL2_3C,
	_RIGHT_PANEL2_3D,
	_RIGHT_PANEL2_3E,
	_RIGHT_PANEL2_3F,
	_RIGHT_PANEL2_3G,
	_RIGHT_PANEL2_3H,
	_RIGHT_PANEL2_3J,
	_RIGHT_PANEL2_3K,
	_RIGHT_PANEL2_3L,
	_RIGHT_PANEL2_3M,
	_RIGHT_PANEL2_3N,
	_RIGHT_PANEL2_3P,

	RIGHT_PANEL2_CB_TOTAL
}RIGHT_CB_PANEL2_TYPE;


#define K_NUM_OF_INT_LT			8//5

typedef enum Caution_Lt_Index_Type
{
	CL_CABIN_PRESS			= 0,
	CL_IFF					= 1,
	CL_FUEL_HOT				= 2,
	CL_AVIONICS_FAULT			= 3,
	CL_ELEC_SYS				= 4,
	CL_BRAKE					= 5,
	CL_ECMS_FAULT				= 6,
	CL_STORES_CONFIG			= 7,
	CL_NWS_FAIL				= 8,
	CL_RADAR_ALT				= 9,
	CL_AUTO_PLT_DISENG			= 10,
	CL_HOOK					= 11,
	CL_ECS					= 12,
	CL_FUEL_PRESS_LOW			= 13,
	CL_ENGINE_FAULT			= 14,
	CL_INLET_ICING			= 15,
	CL_SEAT_NOT_ARMED			= 16,
	CL_FLCS_FAULT				= 17,
	CL_FWD_FUEL_LOW			= 18,
	CL_OVERHEAT				= 19,
	CL_ANTI_SKID				= 20,
	CL_PROBE_HEAT				= 21,
	CL_EQUIP_HOT				= 22,
	CL_STICK_FAIL				= 23,
	CL_AFT_FUEL_LOW			= 24,
	CL_FUEL_IMBALANCE			= 25,
	CL_EPS_FUEL_LOW			= 26,
	CL_AEPS_FAULT				= 27,
	CL_SPARE1					= 28,
	CL_SPARE2					= 29,
	CL_SPARE3					= 30,
	CL_SPARE4					= 31,
	CL_TOT					= 32
}Caution_Lt_Index_Type;

/* Define the enumeration type for warning Lights index */
typedef enum Warning_Lt_Index_Type
{ 
	WL_ENG_FIRE				= 0,
	WL_ENGINE					= 1,
	WL_HYD_PRESS				= 2,	/* Modified HYD_PRESS	*/
	WL_OIL_PRESS				= 3,	/* Modified. OIL_PRESS	*/
	WL_FLCS					= 4,
	WL_LDG_CONFIG				= 5,	/* Modified. LDG_CONFIG	*/
	WL_OXY_LOW				= 6,
	WL_CANOPY					= 7,
	WL_APU_FIRE				= 8, 	
	WL_SPARE1					= 9,
	WL_SPARE2					= 10,			
	WL_TOT					= 11	 /* Total Number of Warning Light */

} Warning_Lt_Index_Type;


typedef enum INTERCOM_BTN_INDEX_TYPE
{
	ITC_GRD1_Btn		= 0,
	ITC_SQL1_Btn		= 1,
	ITC_GRD2_Btn		= 2,
	ITC_SQL2_Btn		= 3,
	ITC_TONE_Btn		= 4,
	ITC_INTHBT_Btn	= 5,
	ITC_MUTE_Btn		= 6,
	ITCB_TOT         = 7    
}INTERCOM_BTN_INDEX_TYPE;


typedef enum SEC_WARNING_MESSAGE_TYPE
{
	SEC_NO_WARNING	= 0,
	SEC_Pull_Up		= 1,
	SEC_Altitude		= 2,
	SEC_Engine_Fire	= 3,
	SEC_Warning		= 4,
	SEC_Caution		= 5,
	SEC_Bingo			= 6,
	SEC_Jammer		= 7,
	SEC_Counter		= 8,
	SEC_Chaff_Flare	= 9,
	SEC_Program		= 10,
	SEC_Low			= 11,
	SEC_Lock			= 12,
	SEC_Out			= 13,
	SEC_Data			= 14,
	SEC_IFF			= 15,
	SEC_Landing_Configuration = 16,
	SEC_TEST			       = 17,
	SEC_INHBT_TEST		   = 18,
	SEC_Morse		   = 19,
	SEC_Squelch			= 20,
	SEC_WARNING_TOTAL		   = 21
	
} SEC_WARNING_MESSAGE_TYPE;


typedef enum INTERCOM_KNOB_INDEX_TYPE
{
	ITC_COMM1_TEST_Knob		= 0,
	ITC_COMM2_TEST_Knob		= 1,
	ITC_EW_TEST_Knob		= 2,
	ITC_MSL_TEST_Knob		= 3,
	ITC_VOX_TEST_Knob		= 4,
	ITC_VOR_TEST_Knob		= 5,
	ITC_TACAN_TEST_Knob		= 6,
	ITC_IFF_TEST_Knob		= 7,
	ITC_RFUL_TEST_Knob		= 8,
	ITC_VMU_TEST_Knob		= 9,
	ITCK_TOT             = 10    
}INTERCOM_KNOB_INDEX_TYPE;

typedef enum STICK_BTN_INDEX_TYPE
{
	CMS_UP_Btn			= 0,
	CMS_DN_Btn			= 1,
	CMS_LFET_Btn			= 2,
	CMS_RIGHT_Btn			= 3,
	TRIM_UP_Btn			= 4,
	TRIM_DN_Btn			= 5,
	TRIM_LEFT_Btn			= 6,
	TRIM_RIGHT_Btn		= 7,
	TMS_UP_Btn		    = 8,
	TMS_DN_Btn	        = 9,
	TMS_LEFT_Btn			= 10,
	TMS_RIGHT_Btn			= 11,
	DMS_UP_Btn		    = 12,
	DMS_DN_Btn	        = 13,
	DMS_LEFT_Btn			= 14,
	DMS_RIGHT_Btn			= 15,
	STICK_TOT            = 16       
}STICK_BTN_INDEX_TYPE;

typedef enum AFT_LMFD_OSS_INDEX_TYPE
{

	MFD_3_OSB_T1		   = 0,   //RIGHT_MFD_OSB_1
	MFD_3_OSB_T2        = 1, 	//RIGHT_MFD_OSB_2
	MFD_3_OSB_T3        = 2, 	//RIGHT_MFD_OSB_3
	MFD_3_OSB_T4        = 3, 	//RIGHT_MFD_OSB_4
	MFD_3_OSB_T5        = 4, 	//RIGHT_MFD_OSB_5
	MFD_3_OSB_T6        = 5, 	//RIGHT_MFD_OSB_6
	MFD_3_OSB_R1        = 6, 	//RIGHT_MFD_OSB_7
	MFD_3_OSB_R2        = 7, 	//RIGHT_MFD_OSB_8
	MFD_3_OSB_R3        = 8, 	//RIGHT_MFD_OSB_9
	MFD_3_OSB_R4       = 9, 	//RIGHT_MFD_OSB_10
	MFD_3_OSB_R5       = 10,	//RIGHT_MFD_OSB_11
	MFD_3_OSB_R6       = 11,	//RIGHT_MFD_OSB_12
	MFD_3_OSB_R7       = 12,	//RIGHT_MFD_OSB_13
	MFD_3_OSB_B6       = 13,	//RIGHT_MFD_OSB_14
	MFD_3_OSB_B5       = 14,	//RIGHT_MFD_OSB_15
	MFD_3_OSB_B4       = 15,	//RIGHT_MFD_OSB_16
	MFD_3_OSB_B3       = 16,	//RIGHT_MFD_OSB_17
	MFD_3_OSB_B2       = 17,	//RIGHT_MFD_OSB_18
	MFD_3_OSB_B1       = 18,	//RIGHT_MFD_OSB_19
	MFD_3_OSB_L7       = 19,	//RIGHT_MFD_OSB_20
	MFD_3_OSB_L6       = 20,	//RIGHT_MFD_OSB_21
	MFD_3_OSB_L5       = 21,	//RIGHT_MFD_OSB_22
	MFD_3_OSB_L4       = 22,	//RIGHT_MFD_OSB_23
	MFD_3_OSB_L3       = 23,	//RIGHT_MFD_OSB_24
	MFD_3_OSB_L2       = 24,	//RIGHT_MFD_OSB_25
	MFD_3_OSB_L1       = 25,	//RIGHT_MFD_OSB_26
	MFD_3_OSB_CON_UP   = 26,	//RIGHT_MFD_OSB_CON_UP
	MFD_3_OSB_CON_DN   = 27,	//RIGHT_MFD_OSB_CON_DOWN
	MFD_3_OSB_BRT_UP   = 28,	//RIGHT_MFD_OSB_BRT_UP
	MFD_3_OSB_BRT_DN   = 29,	//RIGHT_MFD_OSB_BRT_DOWN  
	MFD_3_OSB_TOT  	   = 30     //RIGHT_MFD_OSB_TOT	

}AFT_LMFD_OSS_INDEX_TYPE;

typedef enum AFT_RMFD_OSS_INDEX_TYPE
{
	MFD_4_OSB_T1	      = 0,   //LEFT_MFD_OSB_1
	MFD_4_OSB_T2        = 1, 	//LEFT_MFD_OSB_2
	MFD_4_OSB_T3        = 2, 	//LEFT_MFD_OSB_3
	MFD_4_OSB_T4        = 3, 	//LEFT_MFD_OSB_4
	MFD_4_OSB_T5        = 4, 	//LEFT_MFD_OSB_5
	MFD_4_OSB_T6        = 5, 	//LEFT_MFD_OSB_6
	MFD_4_OSB_R1        = 6, 	//LEFT_MFD_OSB_7
	MFD_4_OSB_R2        = 7, 	//LEFT_MFD_OSB_8
	MFD_4_OSB_R3        = 8, 	//LEFT_MFD_OSB_9
	MFD_4_OSB_R4       = 9, 	//LEFT_MFD_OSB_10
	MFD_4_OSB_R5       = 10,	//LEFT_MFD_OSB_11
	MFD_4_OSB_R6       = 11,	//LEFT_MFD_OSB_12
	MFD_4_OSB_R7       = 12,	//LEFT_MFD_OSB_13
	MFD_4_OSB_B6       = 13,	//LEFT_MFD_OSB_14
	MFD_4_OSB_B5       = 14,	//LEFT_MFD_OSB_15
	MFD_4_OSB_B4       = 15,	//LEFT_MFD_OSB_16
	MFD_4_OSB_B3       = 16,	//LEFT_MFD_OSB_17
	MFD_4_OSB_B2       = 17,	//LEFT_MFD_OSB_18
	MFD_4_OSB_B1       = 18,	//LEFT_MFD_OSB_19
	MFD_4_OSB_L7       = 19,	//LEFT_MFD_OSB_20
	MFD_4_OSB_L6       = 20,	//LEFT_MFD_OSB_21
	MFD_4_OSB_L5       = 21,	//LEFT_MFD_OSB_22
	MFD_4_OSB_L4       = 22,	//LEFT_MFD_OSB_23
	MFD_4_OSB_L3       = 23,	//LEFT_MFD_OSB_24
	MFD_4_OSB_L2       = 24,	//LEFT_MFD_OSB_25
	MFD_4_OSB_L1       = 25,	//LEFT_MFD_OSB_26
	MFD_4_OSB_CON_UP   = 26,	//LEFT_MFD_OSB_CON_UP
	MFD_4_OSB_CON_DN   = 27,	//LEFT_MFD_OSB_CON_DOWN
	MFD_4_OSB_BRT_UP   = 28,	//LEFT_MFD_OSB_BRT_UP
	MFD_4_OSB_BRT_DN   = 29,	//LEFT_MFD_OSB_BRT_DOWN  
	MFD_4_OSB_TOT  	   = 30   //LEFT_MFD_OSB_TOT	

}AFT_RMFD_OSS_INDEX_TYPE;

typedef enum AFT_INTERCOM_BTN_INDEX_TYPE
{
	ITC1_GRD1_Btn		= 0,
	ITC1_SQL1_Btn		= 1,
	ITC1_GRD2_Btn		= 2,
	ITC1_SQL2_Btn		= 3,
	ITC1_TONE_Btn		= 4,
	ITC1_INTHBT_Btn	= 5,
	ITC1_MUTE_Btn		= 6,
	ITCB1_TOT			= 7    
}AFT_INTERCOM_BTN_INDEX_TYPE;

typedef enum AFT_INTERCOM_KNOB_INDEX_TYPE
{
	ITC1_COMM1_TEST_Knob	= 0,
	ITC1_COMM2_TEST_Knob	= 1,
	ITC1_EW_TEST_Knob		= 2,
	ITC1_MSL_TEST_Knob		= 3,
	ITC1_VOX_TEST_Knob		= 4,
	ITC1_VOR_TEST_Knob		= 5,
	ITC1_TACAN_TEST_Knob	= 6,
	ITC1_IFF_TEST_Knob		= 7,
	ITC1_RFUL_TEST_Knob	= 8,
	ITC1_VMU_TEST_Knob		= 9,
	ITCK1_TOT            = 10    
}AFT_INTERCOM_KNOB_INDEX_TYPE;

typedef enum AFT_STICK_BTN_INDEX_TYPE
{
	CMS1_UP_Btn			= 0,
	CMS1_DN_Btn			= 1,
	CMS1_LFET_Btn			= 2,
	CMS1_RIGHT_Btn		= 3,
    TRIM1_UP_Btn			= 4,
	TRIM1_DN_Btn			= 5,
	TRIM1_LEFT_Btn	    = 6,
	TRIM1_RIGHT_Btn       = 7,
	TMS1_UP_Btn		    = 8,
	TMS1_DN_Btn	        = 9,
	TMS1_LEFT_Btn			= 10,
	TMS1_RIGHT_Btn		= 11,
	DMS1_UP_Btn		    = 12,
	DMS1_DN_Btn	        = 13,
	DMS1_LEFT_Btn		    = 14,
	DMS1_RIGHT_Btn		= 15,
	STICK1_TOT           = 16       
}AFT_STICK_BTN_INDEX_TYPE;

//cockpit_types.h
typedef enum pto_switch_type
{
	PTO_NORMAL	= 0,
	PTO_DECOUPLE	= 1
} pto_switch_type;

typedef enum pitch_command_type				
{
	PITCH_TRIM_DOWN		= 0,
	PITCH_TRIM_NEUTRAL		= 1,
	PITCH_TRIM_UP			= 2
} pitch_trim_type;

typedef enum roll_trim_type
{
	ROLL_TRIM_LEFT_DOWN	= 0,
	ROLL_TRIM_NEUTRAL		= 1,
	ROLL_TRIM_RIGHT_DOWN	= 2
} roll_trim_type;

typedef enum alternate_flaps_switch_type
{
	ALTERNATE_FLAPS_NORM	= 0,
	ALTERNATE_FLAPS_EXTEND = 1
} alternate_flaps_switch_type;

typedef enum anti_ice_switch_type
{
	ANTI_ICING_OFF	= 0,
    ANTI_ICING_AUTO	= 1,
	ANTI_ICING_ON		= 2
} anti_ice_switch_type;

typedef enum anti_skid_switch_type
{
	ANTI_SKID_OFF		= 0,
	ANTI_SKID_ON		= 1,
	PARKING_BRAKE		= 2
} anti_skid_switch_type;

typedef enum backup_enable_switch_type
{
	BACKUP_ENABLE_NORM = 0,
	BACKUP_ENABLE_EMER = 1
} backup_enable_switch_type;

typedef enum handle_type
{
	HANDLE_OFF		= 0,
	HANDLE_PULLED		= 1
} handle_type;


typedef enum canopy_state_sensor_type
{	
	CANOPY_STATE_CLOSE		= 0,
	CANOPY_STATE_OPEN		= 1
} canopy_state_sensor_type;

typedef enum channel_transfer_switch_type
{
	CHANNEL_TRANSFER_AUTO = 0,
	CHANNEL_TRANSFER_OVRD = 1
} channel_transfer_switch_type;

typedef enum engine_feed_knob_type
{
	ENG_FEED_OFF				= 0,
	ENG_FEED_NORM				= 1,  
	ENG_FEED_AFT				= 2,
	ENG_FEED_FWD				= 3
} engine_feed_knob_type;

typedef enum eps_switch_type
{
	EPS_SWITCH_OFF	= 0,
	EPS_SWITCH_NORM	= 1,
	EPS_SWITCH_ON		= 2
} eps_switch_type;

/* Define the enumeration type for APS Operation command */
typedef enum aps_operation_command_type
{
	APS_STOP		= 0,
	APS_START		= 1

} aps_operation_command_type;

typedef enum external_fuel_transfer_switch_type
{
	EXT_FUEL_TRANSFER_NORM			= 0,
	EXT_FUEL_TRANSFER_WING_FIRST	= 1
} external_fuel_transfer_switch_type;

typedef enum flash_steady_switch_type
{
	LIGHT_STEADY		= 0,
	LIGHT_FLASH		= 1
} flash_steady_switch_type;

typedef enum flcs_power_test_switch_type
{
	FLCS_POWER_MAINT		= 0,
	FLCS_POWER_NORM		= 1, 
	FLCS_POWER_TEST		= 2
} flcs_power_test_switch_type;

typedef enum fuel_quantity_select_switch_type
{
	FUEL_SEL_TEST = 0,
	FUEL_SEL_NORM = 1,
	FUEL_SEL_RSVR = 2,
	FUEL_SEL_WING = 3,
	FUEL_SEL_EXT  = 4
} fuel_quantity_select_switch_type;

typedef enum fuel_quantity_select_switch_type_OFP
{
	FUEL_SELECT_NORM = 0,
	FUEL_SELECT_TEST = 1,
	FUEL_SELECT_RSVR = 2,
	FUEL_SELECT_WING = 3,
	FUEL_SELECT_EXT = 4
} fuel_quantity_select_switch_typee_OFP;

typedef enum landing_taxi_light_switch_type
{
	LANDING_TAXI_LIGHT_OFF = 0,
	LANDING_LIGHT			= 1,
	TAXI_LIGHT			= 2
} landing_taxi_light_switch_type;


typedef enum switch_up_down_type
{
	SWITCH_UP		= 1,
	SWITCH_DOWN = 0
} switch_up_down_type;



typedef enum cmds_type
{
	CMDS_OFF = 0,
	CMDS_STBY = 1,
	CMDS_NORM = 2,
	CMDS_BYPASS= 3
} cmds_type;



typedef enum projector_nvis_type
{
	MODE_DAY = 0,
	MODE_NIGHT = 1,
	MODE_NVIS = 2,
	MODE_DUSK = 3
}projector_nvis_type;


//[MI:KSJ140529] modify
typedef enum main_power_switch_type
{
	SW_MAIN_PWR_OFF = 0,
	SW_BATT = 1,
	SW_MAIN_PWR = 2 
} main_power_switch_type;

typedef enum manual_pitch_override_switch_type
{
	MPO_NORM = 0,
	MPO_OVRD = 1
} manual_pitch_override_switch_type;

typedef enum oxygen_supply_lever_type
{
	OXYGEN_SUPPLY_LEVER_OFF		= 0,
	OXYGEN_SUPPLY_LEVER_ON			= 1,
	OXYGEN_SUPPLY_LEVER_PBG		= 2
} oxygen_supply_lever_type;

//[MI:KSJ140529] modify
typedef enum pitch_autopilot_switch_type
{
	PITCH_ATT_HOLD			= 0,
	PITCH_AP_OFF				= 1,
	PITCH_ALT_HOLD			= 2
} pitch_autopilot_switch_type;

typedef enum pull_to_cage_knob_type
{
	PULL_TO_CAGE_OFF			= 0,
	PULL_TO_CAGE_PULLED		= 1
} pull_to_cage_knob_type;

typedef enum roll_autopilot_switch_type
{
	ROLL_STRG_HOLD			= 0,
	ROLL_ATT_HOLD				= 1,
	ROLL_HDG_SEL				= 2
} roll_autopilot_switch_type;


typedef enum speed_brake_switch_type
{
	SB_AFT = 0,
	SB_MID = 1,
	SB_FWD = 2
} speed_brake_switch_type;

typedef enum station_override_switch_type
{
	FWD_POSITION = 0,
	AFT_POSITION = 1
} station_override_switch_type;

typedef enum stick_switch_type 
{
	STICK_OFF  = 0,
	STICK_NORM = 1,
	STICK_DISC = 2
} stick_switch_type;

typedef enum stores_configuration_switch_type
{
	CAT3						= 0,
	CAT2						= 1,
	CAT1						= 2
} stores_configuration_switch_type;


typedef enum tail_wing_switch_type
{
	TAIL_WING_LIGHT_OFF		= 0,
	TAIL_WING_LIGHT_DIM		= 1,
	TAIL_WING_LIGHT_BRIGHT		= 2
} tail_wing_switch_type;

typedef enum yaw_trim_type			
{
	YAW_TRIM_LEFT    = 0 ,
	YAW_TRIM_NEUTRAL = 1,
	YAW_TRIM_RIGHT   = 2 
} yaw_trim_type;

typedef enum tank_pressure_switch_type
{
	TANK_PRESSURE_DEPRESS	= 0, 
	TANK_PRESSURE_NORM		= 1
} tank_pressure_switch_type;

typedef enum cam_switch_type
{
	CAM_SWITCH_OFF		= 0,
	CAM_SWITCH_IDLE		= 1
} cam_switch_type;

typedef enum ics_mode_knob_type
{
	ICS_COLD		= 0,
	ICS_HOT		= 1,
	ICS_TEST		= 2	
} ics_mode_knob_type;


typedef enum master_arm_type
{
	MASTER_ARM_SIM= 0,
	MASTER_ARM_OFF= 1,
	MASTER_ARM_ON	= 2
} master_arm_type;


typedef enum master_arm_type_ofp
{
	MASTER_ARM_OFF_OFP = 0,
	MASTER_ARM_ON_OFP = 1,
	MASTER_ARM_SIMULATE_OFP = 2
} master_arm_type_ofp;


typedef enum ground_jettison_type
{
	GROUND_JETTISON_OFF	= 0,
	GROUND_JETTISON_ON		= 1
} ground_jettison_type;


typedef enum apu_generator_switch_type
{
	APU_GEN_AUTO	= 0,
	APU_GEN_ON	= 1
} apu_generator_switch_type;

typedef enum engine_data_switch_type
{
	ENGINE_DATA_NORMAL		= 0,
	ENGINE_DATA_SAVE		= 1		
} engine_data_switch_type;

typedef enum temp_mode_switch_type
{
	TEMP_MODE_MANUAL	= 0,
	TEMP_MODE_AUTO	= 1
} temp_mode_switch_type;

typedef enum cm_manage_type
{
	CM_MANAGE_NEUTRAL	= 0,
	CM_MANAGE_LEFT 	= 1,
	CM_MANAGE_RIGHT   = 2,
	CM_MANAGE_UP 		= 3,
	CM_MANAGE_DOWN 	= 4
} cm_manage_type;

typedef enum emerrgency_lever_type
{
	EMER_LEVER_NORMAL 		= 0,
	EMER_LEVER_EMERGENCY	= 1,
	EMER_LEVER_TEST_MASK	= 2
} emergency_lever_type;

typedef enum oxygen_mode_lever_type
{
	OXYGEN_NORM		= 0,
	OXYGEN_MAX 		= 1
} oxygen_mode_lever_type;

typedef enum vmu_inhibit_switch_type
{
	INHIBIT		= 0,
	VMU			= 1
} vmu_inhibit_switch_type;

typedef enum iff_switch_type
{
	IFF_NORM		= 0,
	IFF_UPPER		= 1,
	IFF_LOWER		= 2
} iff_switch_type;

typedef enum uhf_vhf_switch_type
{
	UVHF_NORM  = 0,
	UVHF_UPPER = 1,
	UVHF_LOWER = 2
} uhf_vhf_switch_type;

typedef enum caws_light_switch_type
{
	CAWS_LIGHT_BRIGHT = 0,
	CAWS_LIGHT_CENTER = 1,
	CAWS_LIGHT_DIM	= 2
} caws_light_switch_type;

typedef enum canopy_switch_type
{
	CANOPY_DOWN   = 0,
	CANOPY_CENTER = 1,
	CANOPY_UP     = 2

} canopy_switch_type;

// by baek-5
// -------------------------------------
typedef enum zeroize_switch_type
{
	ZEROIZE_OFF		= 0,
	ZEROIZE			= 1,
	ZEROIZE_CLR		= 2
} zeroize_switch_type;

typedef enum station_override_switch_type shoulder_harness_lock_lever_type;


//cockpit_types_mtd.h
typedef enum egi_mode_sw_type
{
	EGI_OFF						= 0, 
	EGI_STORED_HEADING				= 1, 
	EGI_NORMAL					= 2,
	EGI_INS						= 3,
	EGI_INS_GPS					= 4,
	EGI_IN_FLIGHT_ALIGN			= 5,
	EGI_ATTITUDE					= 6
} egi_mode_sw_type;						

typedef enum iff_mode_sw_type
{
	IFF_OFF					= 0,
	IFF_STDBY					= 1,
	IFF_LOW					= 2,
	IFF_NORMAL				= 3,
	IFF_EMERGENCY				= 4
}iff_mode_sw_type;						

typedef enum ralt_sw_type
{
	RALT_SW_OFF	= 0,
	RALT_STDBY	= 1, 
	RALT_ON		= 2
}ralt_sw_type;							

typedef enum  lock_type
{
	UNLOCKED = 0,
	LOCKED	= 1
}lock_type;



typedef enum sql_type
{
	SQL_OFF		= 0,
	SQL_SQL		= 1,
	SQL_GD		= 2
}sql_type;

typedef enum WATT_CON1_SW_TYPE
{
	WATT_2_5               =2,
	WATT_10                =1,
	WATT_5                 =0
}WATT_CON1_SW_TYPE;
//ASTD Watt-meter switch type addition(sWitch name Without knowing) By SHS

typedef enum WATT_CON2_SW_TYPE
{
	WATT_X10                = 2,
	WATT_X1                 = 1,
	WATT_X100               = 0   
}WATT_CON2_SW_TYPE;
//ASTD Watt-meter switch type addition(sWitch name Without knowing) By SHS

typedef enum T_47G_UUT_FUNCTION_TYPE
{
	T_47G_XPDR    = 0,
	T_47G_MODE_S  = 1,
	T_47G_INTERR  = 2,
	T_47G_TCAS    = 3,
	T_47G_DME     = 4,
	T_47G_TACAN   = 5
}T_47G_UUT_FUNCTION_TYPE;

typedef enum T_47G_BEARING_RANGE_TYPE
{
	RANGE_2   = 0,
	RANGE_6   = 1,
	RANGE_10  = 2,
	RANGE_25  = 3,
	RANGE_100 = 4,
	RANGE_130 = 5,
	RANGE_180 = 6,
	RANGE_300 = 7
}T_47G_BEARING_RANGE_TYPE;

typedef enum VOR_LOC_DDM_State_TYPE
{
	VOR_LOC_DDM_L_150 = 8,
	VOR_LOC_DDM_L_200 = 7,
	VOR_LOC_DDM_L_155 = 6,
	VOR_LOC_DDM_L_093 = 5,
	VOR_LOC_DDM_0		= 4,
	VOR_LOC_DDM_R_093 = 3,
	VOR_LOC_DDM_R_155 = 2,
	VOR_LOC_DDM_R_200 = 1,
	VOR_LOC_DDM_R_90 = 0

}VOR_LOC_DDM_State_TYPE;
//ASTD  VOR/ILS Test Set LOC DDM Controller

typedef enum VOR_Frequency_Mode_SW_TYPE
{
	VOR_MKR_FIXED = 10,
	VOR_MKR_VAR = 9,
	VOR_FIXED_ = 8,
	VOR_VAR_     = 7,
	VOR_LOC_FIXED_ = 6,
	VOR_LOC_VAR = 5,
	VOR_G_S_FIXED = 4,
	VOR_G_S_VAR = 3,
	VOR_COMM_FIXED = 2,
	VOR_COM25 = 1,
	VOR_COM833 = 0

}VOR_Frequency_Mode_SW_TYPE;
//ASTD  VOR/ILS Test Set Frequency mod switch

typedef enum VOR_FIXED_HI_LO_SW_TYPE
{
	VOR_FIXED_LO = 0,
	VOR_FIXED_HI = 1

}VOR_FIXED_HI_LO_SW_TYPE;
//ASTD  VOR/ILS Test Set FIXED switch

typedef enum VOR_Count_MOD_SW_TYPE
{
	VOR_GEN                 = 5,
	VOR_HZ                  = 4,
	VOR_KHZ1                = 3,
	VOR_KHZ2                = 2,
	VOR_MHZ                 = 1,
	VOR_BRG                 = 0

}VOR_Count_MOD_SW_TYPE;
//ASTD  VOR/ILS Test Set Counting Mode Switch

typedef enum VOR_Ton_SW_TEST_TYPE
{
	VOR_TONE_OFF_TEST			= 0,
	VOR_Ton_400_TEST			= 1,
	VOR_Ton_1300_TEST           = 2,
	VOR_Ton_3000_TEST           = 3,
	VOR_Ton_1020_TEST           = 4
}VOR_Ton_SW_TEST_TYPE;
// ASTD intercom Test after Del!

typedef enum VOR_Ton_SW_TYPE
{
	VOR_Ton_CTR_IN          = 5,
	VOR_Ton_MOD_IN          = 4,
	VOR_Ton_1020            = 3,
	VOR_Ton_400             = 2,
	VOR_Ton_1300            = 1,
	VOR_Ton_3000            = 0
}VOR_Ton_SW_TYPE;
//ASTD  VOR/ILS Test Set TON Switch

typedef enum VOR_AVG_PEAK_LOC_XMTR_ON_SW_TYPE
{
	VOR_AVG                 = 1,
	VOR_PEAK_LOC            = 0,

}VOR_AVG_PEAK_LOC_XMTR_ON_SW_TYPE;
//ASTD  VOR/ILS Test Set AVG/PEAK LOC XMTR ON Switch

typedef enum VOR_ILS_TO_FROM_SW_TYPE
{
	VOR_from = 0,
	VOR_to = 1
}VOR_ILS_TO_FROM_SW_TYPE;
//ASTD  VOR/ILS Test Set TO/TROM Switch

typedef enum VOR_Monitor_SW_TYPE
{
	VOR_Monitor_100W = 6,
	VOR_Monitor_10W = 5,
	VOR_Monitor_RF = 4,
	VOR_Monitor_BAT = 3,
	VOR_Monitor_30 = 2,
	VOR_Monitor_100 = 1,
	VOR_Monitor_BRG = 0

}VOR_Monitor_SW_TYPE;
//ASTD  VOR/ILS Test Set Monitor Switch

typedef enum VOR_Hz_VAR_State_TYPE
{
	VOR_Hz_VAR_State_0 = 0,
	VOR_Hz_VAR_State_1 = 1,
	VOR_Hz_VAR_State_2 = 2,
	VOR_Hz_VAR_State_3 = 3

}VOR_Hz_VAR_State_TYPE;
//ASTD  VOR/ILS Test Set 30Hz var Controller

typedef enum VOR_KHz_REF_State_TYPE
{
	VOR_KHz_REF_State0       = 0,
	VOR_KHz_REF_State10      = 1,
	VOR_KHz_REF_State20      = 2,
	VOR_KHz_REF_State30      = 3,

}VOR_KHz_REF_State_TYPE;
//ASTD  VOR/ILS Test Set 9.96KHz REF Controller


typedef enum VOR_ILS_PWR_BAT_SW_TYPE
{
	VOR_ILS_BAT = 0,
	VOR_ILS_MID = 1,
	VOR_ILS_PWR = 2

}VOR_ILS_PWR_BAT_SW_TYPE;
//ASTD  VOR/ILS Test Set PWR BAT Switch

typedef enum VOR_ILS_Master_State_TYPE
{
	Master_State_CAL = 0,
	Master_State_MAX = 1
}VOR_ILS_Master_State_TYPE;
//ASTD  VOR/ILS Master Controller 
 
typedef enum VOR_ILS_GS_DDM_State_TYPE
{
	GS_DDM_State_l90 = 8,
	GS_DDM_State_L400 = 7,
	GS_DDM_State_L175 = 6,
	GS_DDM_State_L091 = 5,
	GS_DDM_State_0 = 4,
	GS_DDM_State_R091 = 3,
	GS_DDM_State_R175 = 2,
	GS_DDM_State_R400 = 1,
	GS_DDM_State_R150 = 0

}VOR_ILS_GS_DDM_State_TYPE;
//ASTD  VOR/ILS GS_DDM_State Controller

typedef enum WATT_PWR_SW_TYPE  
{
	WATT_BAT                         =0,
	WATT_OFF                         =1,
	WATT_LINE                         =2
}WATT_PWR_SW_TYPE;
//ASTD Watt-meter Power Switch Type Add By SHS

typedef enum WATT_ELE_STATE_TYPE
{
	ELE_NONE        = 0,
	ELE_50A_ANT_DIR = 1,
	ELE_50A_RA_DIR  = 2,
	ELE_50B_ANT_DIR = 3,
	ELE_50B_RA_DIR  = 4,
	ELE_50C_ANT_DIR = 5,
	ELE_50C_RA_DIR  = 6,
	ELE_50D_ANT_DIR = 7,
	ELE_50D_RA_DIR  = 8,
	ELE_STOPPER		= 9

}WATT_ELE_STATE_TYPE;
//ASTD Watt-meter Element State Type Add By SHS

typedef enum COMM_CHAN_TYPE
{
	COMM_EXTERNAL		= 0,
	COMM_INTERNAL		= 1,
	COMM_EXTERNAL_READY	= 2,
	COMM_NONE			= 3,
}COMM_TYPE;

typedef enum SMFD_CMDS_MODE_SELECT_TYPE
{
	CMDS_MODE_MAN,
	CMDS_MODE_SEMI,
	CMDS_MODE_AUTO

}SMFD_CMDS_MODE_SELECT_TYPE;

typedef enum RWR_POWER_SW_TYPE
{
	RWR_EXT         =2,
	RWR_OFF         =1,
	RWR_BATT        =0
}RWR_POWER_SW_TYPE;

typedef enum IMDC2_OFP_Upload_LRU_SEL_TYPE
{
	IMDC2_NONE = 0,
	HPM = 1,
	PGM1 =2,
	PGM2 =3,
	SEND =4
}IMDC2_OFP_Upload_LRU_SEL_TYPE;


typedef enum TCC_PAGE_NUM_TYPE
{
	TCC_OFF_PAGE		                    = 0,
	TCC_WALLPAPER_PAGE		                = 1,
	IOGP_PAGE		                        = 2,
	IOGP_MAIN_PAGE		                    = 3,
	IOGP_MAIN_BIT_PAGE		                = 4,
	IOGP_MAIN_BIT_ID_PAGE		            = 5,
	WINDOW_START_PAGE		                = 6,
	IOGP_DOWN_VAI_PAGE		                = 7,
	IOGP_DOWN_RD_PAGE		                = 8,
	IOGP_DOWN_VOIC_PAGE		                = 9,
	IOGP_DOWN_FILE_PAGE		                = 10,
	IOGP_DOWN_FILE_DOWN_PAGE		        = 11,
	TCC_MAIN_MENU_PAGE		                = 12,
	TCC_FCR_OFP_UPLOAD_PAGE		            = 13,
	TCC_FCR_OPEN_PAGE		                = 14,
	TCC_FCR_OPEN_FILE_CLICK_PAGE		    = 15,
	TCC_FCR_OFP_UPLOAD_SEARCH_PAGE		    = 16,
	TCC_FCR_INFORMATION_PAGE		        = 17,
	TCC_FCR_OFP_UPLOAD_COMPLETE_PAGE	    = 18,
	TCC_FCR_CLOSE_PAGE		                = 19,
	TCC_IMDC2_OFP_UPLOAD_PAGE		        = 20,
	TCC_IMDC2_OFP_UPLOAD_HMP_CLICK_PAGE		= 21,
	TCC_IMDC2_OPEN_PAGE		                = 22,
	TCC_IMDC2_OPEN_FILE_CLICK_PAGE		    = 23,
	TCC_IMDC2_OFP_UPLOAD_SEARCH_PAGE		= 24,
	TCC_IMDC2_INFORMATION_PAGE		        = 25,
	TCC_IMDC2_OFP_Upload_Complete_PAGE		= 26,
	TCC_IMDC2_Close_PAGE		            = 27,
	TCC_FLCC_OFP_UPLOAD_PAGE				= 28,
	TCC_FLCC_OPEN_PAGE						= 29,
	TCC_FLCC_OPEN_FILE_CLICK_PAGE			= 30,
	TCC_FLCC_OFP_UPLOAD_CHARGING_PAGE		= 31,
	TCC_FLCC_UPLOAD_READY_PAGE				= 32,
	TCC_FLCC_SHOING_PAGE					= 33,
	TCC_FLCC_LOADING_PAGE					= 34,
	TCC_FLCC_INFORMATION_PAGE				= 35,
	TCC_FLCC_UPLOAD_COMPLETE_PAGE			= 36,
	TCC_FLCC_CLOSE_PAGE						= 37,
	TCC_ECMS_MAIN_PAGE						= 38,
	TCC_ECMS_DATA_DOWN_PAGE					= 39,
	TCC_ECMS_DATA_DOWN_COMP_PAGE			= 40,
	TCC_ECMS_DATA_DIS_PAGE					= 41,
	TCC_ECMS_DATA_PFL_MFL_PAGE				= 42,
	TCC_ECMS_MEMORY_PAGE					= 43,
	TCC_ECMS_MEMORY_CLEAR_PAGE				= 44,
	TCC_ECMS_MEMORY_COMP_PAGE				= 45,

}TCC_PAGE_NUM_TYPE;

//after Del
typedef enum TCC_Page_TYPE
{
	Main = 0,
	IOGP = 1,
	IOGP_Down_VAI = 2,
	IOGP_Down_RD = 3,
	IOGP_Down_VOIC = 4,
	IOGP_Down_Status = 5,
	IOGP_Down_Status_1 = 6,
	IOGP_Down_File = 7,
	TCC_Main_Menu = 8,
	TCC_FCR_OFP_Upload = 9,
	TCC_FCR_Open = 10,
	TCC_FCR_Information = 11,
	TCC_FCR_Close = 12,
	TCC_IMDC2_OFP_Upload = 13,
	TCC_IMDC2_Open = 14,
	TCC_IMDC2_Information = 15,
	TCC_IMDC2_Close = 16,
	TCC_ECMS_Main_Menu = 17,
	TCC_ECMS_Data_Display = 18,
	TCC_ECMS_PFL_MFL = 19,
	TCC_FLCC_OFP_Upload = 20,
	TCC_FLCC_Close =21,
	TCC_FLCC_Information = 22,
	TCC_FLCC_Open = 23,
	TCC_FLCC_SHOPING = 24
}TCC_Page_TYPE;
//after Del

//SLS
typedef enum SLS_PAGE_NUM_TYPE
{
	SLS_OFF_PAGE		  = 0, 
	SLS_WALLPAPER_PAGE	  = 1, 
	SLS_WIN_STR_PAGE	  = 2, 
	SLS_CMD1_PAGE		  = 3, 
	SLS_CMD2_PAGE		  = 4, 
	SLS_CMD3_PAGE		  = 5, 
	SLS_CMD4_PAGE		  = 6, 
	SLS_CMD5_PAGE		  = 7, 
	SLS_CMD6_PAGE		  = 8, 
	SLS_CMD7_PAGE		  = 9, 
	SLS_CMD8_PAGE		  = 10,
	SLS_CMD9_PAGE		  = 11,
	SLS_CMD10_PAGE		  = 12,
	SLS_CMD11_PAGE		  = 13,
	SLS_CMD12_PAGE		  = 14,
	SLS_CMD13_PAGE		  = 15,
	SLS_CMD14_PAGE		  = 16,
	SLS_CMD15_PAGE		  = 17,
	SLS_CMD16_PAGE		  = 18,
	SLS_CMD17_PAGE		  = 19,
	SLS_CMD18_PAGE		  = 20,
	SLS_CMD19_PAGE		  = 21,
	SLS_CMD20_PAGE		  = 22,
	SLS_CMD21_PAGE		  = 23,
	SLS_CMD22_PAGE		  = 24,
	SLS_CMD23_PAGE		  = 25,
	SLS_CMD24_PAGE		  = 26,
	SLS_CMD25_PAGE		  = 27,
	SLS_CMD26_PAGE		  = 28,
	SLS_CMD27_PAGE		  = 29,
	SLS_CMD28_PAGE		  = 30,
	SLS_CMD29_PAGE		  = 31,
	SLS_CMD30_PAGE		  = 32,
	SLS_CMD31_PAGE		  = 33,
	SLS_CMD32_PAGE		  = 34,
	SLS_CMD33_PAGE		  = 35,
	SLS_CMD34_PAGE		  = 36,
	SLS_CMD35_PAGE		  = 37,
	SLS_CMD36_PAGE		  = 38,
	SLS_CMD37_PAGE		  = 39,
	SLS_CMD38_PAGE		  = 40,
	SLS_CMD39_PAGE		  = 41,
	SLS_CMD40_PAGE		  = 42,
	SLS_CMD41_PAGE		  = 43,
	SLS_CMD42_PAGE		  = 44,
	SLS_CMD43_PAGE		  = 45,
	SLS_CMD44_PAGE		  = 46,
	SLS_CMD45_PAGE		  = 47,
	SLS_CMD46_PAGE		  = 48,
	SLS_CMD47_PAGE		  = 49,
	SLS_WIN_CLOSE_PAGE	  = 50 
}SLS_PAGE_NUM_TYPE;

//GRIDCASE1590 Type Add
typedef enum GRIDCASE1590_Page_TYPE
{
	GRIDCASE1590_OFF = 0,
	GRIDCASE1590_Loading = 1,
	GRIDCASE1590_Login = 2,
	GRIDCASE1590_Main_Menu= 3,
	GRIDCASE1590_Information = 4,
	GRIDCASE1590_Tail_number = 5,
	GRIDCASE1590_AFT = 6,
	GRIDCASE1590_FWD = 7,
	GRIDCASE1590_Camera_Setup_Instructions = 8,
	GRIDCASE1590_Verifying_Camera_Setup = 9,
	GRIDCASE1590_Measurement_Results = 10,
	GRIDCASE1590_EGI = 11,
	GRIDCASE1590_View_Report = 12,
	GRIDCASE1590_Measurement_Results_View =13
}GRIDCASE1590_Page_TYPE;

//=====================================================
//EESTD Support Equipment enum Type
//=====================================================
typedef enum TB_SIMULATOR_OM_SEL_TYPE
{
	TB_SIMULATOR_OM_AUTO = 0,
	TB_SIMULATOR_OM_MANUAL = 1
}TB_SIMULATOR_OM_SEL_TYPE;

typedef enum TB_SIMULATOR_IP_TYPE
{
	TB_SIMULATOR_IP_OFF = 0,
	TB_SIMULATOR_IP_R_N = 1,
	TB_SIMULATOR_IP_S_N = 2,
	TB_SIMULATOR_IP_T_N = 3
}TB_SIMULATOR_IP_TYPE;

typedef enum ECTS_MODE_TYPE
{
	ECTS_MODE_OFF        = 0,
	ECTS_MODE_PHASE_A    = 1,
	ECTS_MODE_PHASE_B    = 2,
	ECTS_MODE_PHASE_C    = 3,
	ECTS_MODE_FRE_QUENCY = 4
}ECTS_MODE_TYPE;

typedef enum TEST_ADAPTER_S1_TYPE
{
	TEST_ADAPTER_S1_OFF         = 0,
	TEST_ADAPTER_S1_BAT_CHGR    = 1,
	TEST_ADAPTER_S1_MAIN_PWR    = 2,
	TEST_ADAPTER_S1_EXC_OUT     = 3,
	TEST_ADAPTER_S1_CONT_OUT    = 4,
	TEST_ADAPTER_S1_BAT_BUS     = 5,
	TEST_ADAPTER_S1_PMG_1200HZ  = 6,
	TEST_ADAPTER_S1_PMG_5600HZ  = 7,
	TEST_ADAPTER_S1_EXC_FLD     = 8,
	TEST_ADAPTER_S1_SPARE1      = 9,
	TEST_ADAPTER_S1_SPARE2      = 10,
	TEST_ADAPTER_S1_SPARE3      = 11
}TEST_ADAPTER_S1_TYPE;

typedef enum TEST_ADAPTER_S2_TYPE
{
	TEST_ADAPTER_S2_OFF = 0,
	TEST_ADAPTER_S2_TEST = 1
}TEST_ADAPTER_S2_TYPE;

//=====================================================
//COSTD Support Equipment enum Type
//=====================================================
typedef enum CLT_RATE_SELECTOR_VALVE_SW_TYPE
{
	CLT_RATE_SELECTOR_VALVE_DECREASE = 0,
	CLT_RATE_SELECTOR_VALVE_START    = 1,
	CLT_RATE_SELECTOR_VALVE_INCREASE = 2

}CLT_RATE_SELECTOR_VALVE_SW_TYPE;

typedef enum CLT_START_KEY_TYPE
{
	CLT_START_KEY_P = 0,
	CLT_START_KEY_O = 1,
	CLT_START_KEY_1 = 2,
	CLT_START_KEY_2 = 3,
	CLT_START_KEY_3 = 4
}CLT_START_KEY_TYPE;

typedef enum EVT_POWER_SW_TYPE
{
	EVT_POWER_OFF = 0,
	EVT_POWER_ON = 1,
	EVT_POWER_SELF_TEST = 2,
	
}EVT_POWER_SW_TYPE;

typedef enum EVT_PRSOV_SW_TYPE
{
	EVT_PRSOV_OPEN = 0,
	EVT_PRSOV_CLOSE = 1,
}EVT_PRSOV_SW_TYPE;

typedef enum PBG_POWER_SW_TYPE
{
	PBG_POWER_SW_OFF = 0,
	PBG_POWER_SW_CB1 = 1,
	PBG_POWER_SW_ON = 2
}PBG_POWER_SW_TYPE;

typedef enum PBG_KEY_TYPE
{
	PBG_1_BTN = 0,
	PBG_2_BTN = 1,
	PBG_3_BTN = 2,
	PBG_4_BTN = 3,
	PBG_5_BTN = 4,
	PBG_6_BTN = 5,
	PBG_7_BTN = 6,
	PBG_8_BTN = 7,
	PBG_9_BTN = 8,
	PBG_STAR_BTN = 9,
	PBG_0_BTN = 10,
	PBG_POUND_BTN = 11,
	PBG_NONE = 12,
	PBG_KEY_TOT = 13

}PBG_KEY_TYPE;


typedef enum PBG_V11_KNOB_OPEN_CLOSE_TYPE
{
	PBG_V11_KNOB_CLOSE = 0,
	PBG_V11_KNOB_OPEN = 1
	

}PBG_V11_KNOB_OPEN_CLOSE_TYPE;

typedef enum PBG_V12_KNOB_OPEN_CLOSE_TYPE
{
	PBG_V12_KNOB_CLOSE = 0,
	PBG_V12_KNOB_OPEN = 1
	
}PBG_V12_KNOB_OPEN_CLOSE_TYPE;

typedef enum PBG_PRESS_BULB_VALVE_TYPE
{
	PBG_PRESS_BULB_VALVE_OFF = 0,
	PBG_PRESS_BULB_VALVE_FLOW = 1
}PBG_PRESS_BULB_VALVE_TYPE;

//=====================================================
//FSTD Support Equipment enum Type
//=====================================================
/* define enumeration type of Capacitance Test Set Power switch type */
typedef enum Capa_Test_Set_Pwr_Switch_Type 
{
	CAPA_TEST_PWR_CHG		= 0,
	CAPA_TEST_PWR_BATT		= 1,
	CAPA_TEST_PWR_OFF		= 2,
	CAPA_TEST_PWR_AC		= 3
} Capa_Test_Set_Pwr_Switch_Type;

/* define enumeration type of Capacitance system select switch type */
typedef enum Capa_Sys_Sel_Switch_Type 
{
	CAPA_SYS_SEL_AC_FQGS	= 0,
	CAPA_SYS_SEL_DC_FQGS	= 1

} Capa_Sys_Sel_Switch_Type;

/* define enumeration type of Capacitance range switch type */
typedef enum Capa_Range_Switch_Type 
{
	CAPA_RNG_1000M_OHM		= 0,
	CAPA_RNG_200M_OHM		= 1,
	CAPA_RNG_20M_OHM		= 2,
	CAPA_RNG_199_9_PF		= 3,
	CAPA_RNG_1999_9_PF		= 4,
	CAPA_RNG_8000_PF		= 5

} Capa_Range_Switch_Type;

/* define enumeration type of Capacitance DC mode switch type */
typedef enum Capa_DC_Mode_Switch_Type
{
	CAPA_DC_MEGAOHMMETER_SELECT	= 0,
	CAPA_DC_SET_SIM_COMP		= 1,
	CAPA_DC_SET_SIM_TU			= 2,
	CAPA_DC_SIM			        = 3,
	//CAPA_DC_MODE				= 4, 
	CAPA_DC_MEAS_TU_PLUS		= 4,
	CAPA_DC_MEAS_TU_MINUS		= 5,
	CAPA_DC_MEAS_COMP_PLUS		= 6,
	CAPA_DC_MEAS_COMP_MINUS		= 7,
	CAPA_DC_CAL_ZERO			= 8,
	CAPA_DC_CAL_LOW				= 9,
	CAPA_DC_CAL_MID				= 10,
	CAPA_DC_CAL_HIGH			= 11

} Capa_DC_Mode_Switch_Type;

typedef enum FQMS_Test_Set_Power_Switch_Type
{
	FQMS_POWER_OFF			= 0,
	FQMS_POWER_ON			    = 1

} FQMS_Test_Set_Power_Switch_Type;

/* define enumeration type of FQMS Test Set measure level sensor type */
typedef enum FQMS_Test_Set_Level_Sensor_Type
{
	FQMS_SENSOR_NOT_CONNECT		= 0,
	FQMS_SENSOR_PLUS_MINUS_CONNECT	= 1,
	FQMS_SENSOR_PLUS_CONNECT	    = 2,
	FQMS_SENSOR_MINUS_NOT_CONNECT	= 3,
	FQMS_SENSOR_CONNECT_ERROR		= 4

} FQMS_Test_Set_Level_Sensor_Type;

/* define enumeration type of FQMS Test Set Quantity Selector switch type */
typedef enum FQMS_Test_Set_Qty_Sel_Switch_Type
{
	FQMS_QTY_SEL_OFF			= 0,
	FQMS_QTY_SEL_F1			= 1,
	FQMS_QTY_SEL_F2			= 2,
	FQMS_QTY_SEL_F3			= 3,
	FQMS_QTY_SEL_F4			= 4,
	FQMS_QTY_SEL_F5			= 5,
	FQMS_QTY_SEL_W1			= 6,
	FQMS_QTY_SEL_W2			= 7,
	FQMS_QTY_SEL_LE			= 8,
	FQMS_QTY_SEL_CE			= 9,
	FQMS_QTY_SEL_RE			= 10,
	FQMS_QTY_SEL_TOTAL			= 11

} FQMS_Test_Set_Qty_Sel_Switch_Type;

/* define enumeration type of FQMS Test Set Unit Selector switch type */
typedef enum FQMS_Test_Set_Unit_Sel_Switch_Type
{
	FQMS_UNIT_SEL_OFF			= 0,
	FQMS_UNIT_SEL_LW_AFT		= 1,
	FQMS_UNIT_SEL_LW_CTR		= 2,
	FQMS_UNIT_SEL_LW_FWD		= 3,
	FQMS_UNIT_SEL_RW_AFT		= 4,
	FQMS_UNIT_SEL_RW_CTR		= 5,
	FQMS_UNIT_SEL_RW_FWD		= 6,
	FQMS_UNIT_SEL_EXT_RH		= 7,
	FQMS_UNIT_SEL_EXT_CTR		= 8,
	FQMS_UNIT_SEL_EXT_LH		= 9,
	FQMS_UNIT_SEL_F5_LH		= 10,
	FQMS_UNIT_SEL_F5_RH		= 11,
	FQMS_UNIT_SEL_F4			= 12,
	FQMS_UNIT_SEL_F3			= 13,
	FQMS_UNIT_SEL_F2_LH		= 14,
	FQMS_UNIT_SEL_F2_RH		= 15,
	FQMS_UNIT_SEL_F1			= 16


} FQMS_Test_Set_Unit_Sel_Switch_Type;

typedef enum FQMS_Test_Set_Unit_Switch_Type
{
	FQMS_UNIT_SEL_THRU		= 0,
	FQMS_UNIT_SEL_LLF4		= 1,
	FQMS_UNIT_SEL_LLF3		= 2,
	FQMS_UNIT_SEL_AEF4		= 3,
	FQMS_UNIT_SEL_AEF3		= 4

} FQMS_Test_Set_Unit_Switch_Type;


typedef enum CAPA_Cal_Switch_Type
{
	CAL_ZERO	    = 0,
	CAL_LOW		    = 1,
	CAL_MID		    = 2,
	CAL_HIGH		= 3

} CAPA_Cal_Switch_Type;


typedef enum Fqms_Air_Ejector_Sw_Type
{
	AIR_EJECTOR_SW_THRU = 0,
	AIR_EJECTOR_SW_OFF  = 1,
	AIR_EJECTOR_SW_ON   = 2

} Fqms_Air_Ejector_Sw_Type;


typedef enum FQMS_Hfsov_Sw_Type

{
	FQMS_HFSOV_THRU	= 0,
	FQMS_HFSOV_CLOSE  = 1,
	FQMS_HFSOV_OPEN   = 2

} FQMS_Hfsov_Sw_Type;


typedef enum LG_Up_Down_Type
{
	LG_DOWN	= 0,
	LG_UP	= 1

} LG_Up_Down_Type;


typedef enum LG_Down_Type
{
	NLG_MLG_UP = 0,
	NLG_DOWN_MLG_UP = 1,
	NLG_MLG_DOWN = 2,
} LG_Down_Type;


/* Define the enumeration type for internal Lights index */
typedef enum Internal_Light_Index_Type
{
	L_PRIM_CS_LTS				= 0,			/* Left Primary Console Lights					
										**	- Transformer(3312T1) for Left Consoles Light	*/	
	R_PRIM_CS_LTS				= 1,			/* Right Priamery Console Lights				
										**	- Transformer(3312T2) for Right Consoles Light	*/
	L_FLOOD_CS_LTS			= 2,			/* Left Side wall Flood Console Lights
										**	- Transformer(3313T2) form Left Consoles Light	
										**	- Light: 3313XDS6, 7,8, 9, 10.					*/
	R_FLOOD_CS_LTS			= 3,			/* Right Side wall Flood Console Lights		
										**	- Transformer(3313T3) for Right Consoles Light
										**	- Light: 3313XDS11, 12, 13, 14, 15.				*/
	C_FLOOD_Inst_CS_LTS		= 4,			/* Center Side wall Flood INST Lights.
										**	- Transformer(3313T1)
										**	- Left Glaresheild Flood Lts:	3313XDS1
										**	- Right Glaresshei Flood Lts:	3313XDS3
										**	- Center Flood Lts:				3313XDS5.		*/
	PRIM_INST_LTS				= 5,			/* Primary Instrument Lights.					
										**	- Transformer(3311T1) for Primary Inst Light	*/
	CAWS_DIM_LTS				= 6,			/* CAWS SWITCH STATUS.								*/
	CAWS_TEST_LTS				= 7,			/* CAWS TEST SWITCH STATUS.							*/

	TOT_INT_LT				= 8			/* Total Number of Internal Lights					*/

} Internal_Light_Index_Type;

/* Define the enumeration type for External Lights Index. */
typedef enum external_light_index_type
{
	/* Flash Mode Light */
	ANTI_C			=	0,
	L_INLET_NAV		=	1,
	R_INLET_NAV		=	2,
	TAIL_NAV		=	3,
	L_WT_FORM_NAV	=	4,
	R_WT_FORM_NAV	=	5,

	/* Non-Flash Mode Light */
	LANDING			=	6,
	TAXI			=	7,
	L_VERT_TAIL_FLOOD = 8,
	R_VERT_TAIL_FLOOD = 9,
	UP_FORM			=	10,
	LO_FORM			=	11,

	TOT_EXT_LT		=   12	/* Total Number of External Lights */

} external_light_index_type;

/* Define the enumeration type for Light Status. */
typedef enum light_status_type
{
	EXT_LT_OFF			= 0,
	EXT_STEADY_ON		= 1,
	EXT_FLASH_ON		= 2,
	EXT_FAST_FLASH_ON	= 3

} light_status_type;

/* Define the enumeration type for External Light Property */
typedef struct ext_light_property_type 
{
	light_status_type			Status;			
	LIGHT_BRIGHTNESS_TYPE		Brtn;	

} ext_light_property_type;

typedef enum loop_sw_type
{
	LOOP_SW_ONE			= 0,
	LOOP_SW_NORM		= 1,
	LOOP_SW_TWO			= 2

} loop_sw_type;

typedef struct flc_circuit_breaker_type
{
	Circuit_Breaker_Type DSP_CB_Fw_NLG_WOW_BRANCH_A;
	Circuit_Breaker_Type DSP_CB_Fw_NLG_WOW_BRANCH_B;
	Circuit_Breaker_Type DSP_CB_Fw_NLG_WOW_BRANCH_C;
	Circuit_Breaker_Type DSP_CB_LH_MLG_WOW_BRANCH_A;
	Circuit_Breaker_Type DSP_CB_LH_MLG_WOW_BRANCH_B;
	Circuit_Breaker_Type DSP_CB_LH_MLG_WOW_BRANCH_C;

} flc_circuit_breaker_type;


typedef enum THROTTLE_DGFT_SW_TYPE    //[MI:HSD150116]Add 
{
	THROTTLE_MSL					= 0,
	THROTTLE_MID					= 1,
	THROTTLE_DGFT				    = 2

} THROTTLE_DGFT_SW_TYPE;


typedef enum ENG_SECIGN_SW_TYPE    //[MI:HSD150116]Add 
{
	ENG_SECIGN_SW_OFF 	= 0,
	ENG_SECIGN_SW_SECIGN	= 1,
	ENG_SECIGN_SW_CLR 	= 2,

} ENG_SECIGN_SW_TYPE;

typedef enum ENG_APS_SW_TYPE		//[MI:HSD150116]Add 		
{	
	ENG_APS_SW_OFF		= 0,
	ENG_APS_SW_ON		= 1,
	ENG_APS_SW_CLR		= 2
} ENG_APS_SW_TYPE;
typedef enum FLCS_Reset_Switch_Type		/* flcs reset switch type */
{
	FLCS_RESET_NORM		= 0,
	FLCS_RESET_RESET	= 1,
	FLCS_RESET_CLR      = 2

} FLCS_Reset_Switch_Type;

typedef enum RWR_Set_Sw_Type
{
	RWR_SET_SW_OFF		= 0,
	RWR_SET_SW_ON			= 1,
	RWR_SET_SW_CLR	    = 2

}RWR_Set_Sw_Type;

typedef enum CMDS_Jettison_Sw_Type
{
	CMDS_Jettison_OFF	= 0,
	CMDS_Jettison		= 1,
	CMDS_Jettison_CLR	= 2

}CMDS_Jettison_Sw_Type;

typedef enum IFF701_signal_type
{
	IFF701st_DSP_MEASURE		= 0,
	IFF701st_CW_M5				= 1,
	IFF701st_CW				= 2,
	IFF701st_CW_P4				= 3,
	IFF701st_ATC_A_BCKGND		= 4,
	IFF701st_ATC_C_BCKGND		= 5,
	IFF701st_ITM_MODES_C		= 6,
	IFF701st_ITM_MODES_A		= 7,
	IFF701st_ITM_ATC_C			= 8,
	IFF701st_ITM_ATC_A_S		= 9,
	IFF701st_ITM_ATC_A			= 10,
	IFF701st_ATC_C_SLS			= 11,
	IFF701st_ATC_A_SLS			= 12,
	IFF701st_ATC_C_SLS0DB		= 13,
	IFF701st_ATC_A_SLS0DB		= 14,
	IFF701st_ATC_C				= 15,
	IFF701st_ATC_A				= 16,
	IFF701st_FMT21				= 17,
	IFF701st_FMT20				= 18,
	IFF701st_FMT16				= 19,
	IFF701st_FMT11				= 20,
	IFF701st_FMT5				= 21,
	IFF701st_FMT4_SPR_OFF		= 22,
	IFF701st_FMT4_SPR_ON		= 23,
	IFF701st_FMT0				= 24,
	IFF701st_MODE_4B_MAX_OUT	= 25,
	IFF701st_MODE_4B_MAX_IN	= 26,
	IFF701st_MODE_4B_MIN_IN	= 27,
	IFF701st_MODE_4B_MIN_OUT	= 28,
	IFF701st_MODE_4A_MAX_OUT	= 29,
	IFF701st_MODE_4A_MAX_IN	= 30,
	IFF701st_MODE_4A_MIN_IN	= 31,
	IFF701st_MODE_4A_MIN_OUT	= 32,
	IFF701st_MODE_2_MAX_OUT	= 33,
	IFF701st_MODE_2_MAX_IN		= 34,
	IFF701st_MODE_2_MIN_IN		= 35,
	IFF701st_MODE_2_MIN_OUT	= 36,
	IFF701st_MODE_1_MAX_OUT	= 37,
	IFF701st_MODE_1_MAX_IN		= 38,
	IFF701st_MODE_1_MIN_IN		= 39,
	IFF701st_MODE_1_MIN_OUT	= 40,
	IFF701st_MODE_C_MAX_OUT	= 41,
	IFF701st_MODE_C_MAX_IN		= 42,
	IFF701st_MODE_C_MIN_IN		= 43,
	IFF701st_MODE_C_MIN_OUT	= 44,
	IFF701st_MODE_A_MAX_OUT	= 45,
	IFF701st_MODE_A_MAX_IN		= 46,
	IFF701st_MODE_A_MIN_IN		= 47,
	IFF701st_MODE_A_MIN_OUT	= 48,
	IFF701st_MODE_4B_SLS9		= 49,
	IFF701st_MODE_4A_SLS9		= 50,
	IFF701st_MODE_4B_SLS0		= 51,
	IFF701st_MODE_4A_SLS0		= 52,
	IFF701st_MODE_4B			= 53,
	IFF701st_MODE_4A			= 54,
	IFF701st_MODE_2_SLS9		= 55,
	IFF701st_MODE_1_SLS9		= 56,
	IFF701st_MODE_2_SLS0		= 57,
	IFF701st_MODE_1_SLS0		= 58,
	IFF701st_MODE_2			= 59,
	IFF701st_MODE_1			= 60
}IFF701_signal_type;

typedef enum IFF701_PRF_type
{
	IFF_PRF_1		= 0,
	IFF_PRF_2		= 1,
	IFF_PRF_3		= 2,
	IFF_PRF_4		= 3,
	IFF_PRF_5		= 4,
	IFF_PRF_6		= 5,
	IFF_PRF_7		= 6,
	IFF_PRF_8		= 7,
	IFF_PRF_9		= 8,
	IFF_PRF_10		= 9,
	IFF_PRF_11		= 10,
	IFF_PRF_12		= 11,
	IFF_PRF_13		= 12,
	IFF_PRF_14		= 13,
	IFF_PRF_15		= 14,
	IFF_PRF_16		= 15,
	IFF_PRF_18		= 16,
	IFF_PRF_20		= 17,
	IFF_PRF_21		= 18,
	IFF_PRF_24		= 19,
	IFF_PRF_26		= 20,
	IFF_PRF_29		= 21,
	IFF_PRF_34		= 22,
	IFF_PRF_39		= 23,
	IFF_PRF_47		= 24,
	IFF_PRF_59		= 25,
	IFF_PRF_78		= 26,
	IFF_PRF_118		= 27,
	IFF_PRF_235		= 28
}IFF701_PRF_type;

typedef enum IFF701_ATTENUATION_type
{
	IFF_ATTENUATION_1		= 0,
	IFF_ATTENUATION_2		= 1,
	IFF_ATTENUATION_3		= 2,
	IFF_ATTENUATION_4		= 3,
	IFF_ATTENUATION_5		= 4,
	IFF_ATTENUATION_6		= 5,
	IFF_ATTENUATION_7		= 6,
	IFF_ATTENUATION_8		= 7,
	IFF_ATTENUATION_9		= 8,
	IFF_ATTENUATION_10		= 9,
	IFF_ATTENUATION_11		= 10,
	IFF_ATTENUATION_12		= 11,
	IFF_ATTENUATION_13		= 12,
	IFF_ATTENUATION_14		= 13,
	IFF_ATTENUATION_15		= 14,
	IFF_ATTENUATION_16		= 15,
	IFF_ATTENUATION_17		= 16,
	IFF_ATTENUATION_18		= 17,
	IFF_ATTENUATION_19		= 18,
	IFF_ATTENUATION_20		= 19,
	IFF_ATTENUATION_21		= 20,
	IFF_ATTENUATION_22		= 21,
	IFF_ATTENUATION_23		= 22,
	IFF_ATTENUATION_24		= 23,
	IFF_ATTENUATION_25		= 24,
	IFF_ATTENUATION_26		= 25,
	IFF_ATTENUATION_27		= 26,
	IFF_ATTENUATION_28		= 27,
	IFF_ATTENUATION_29		= 28,
	IFF_ATTENUATION_30		= 29,
	IFF_ATTENUATION_31		= 30,
	IFF_ATTENUATION_32		= 31,
	IFF_ATTENUATION_33		= 32,
	IFF_ATTENUATION_34		= 33,
	IFF_ATTENUATION_35		= 34,
	IFF_ATTENUATION_36		= 35,
	IFF_ATTENUATION_37		= 36,
	IFF_ATTENUATION_38		= 37,
	IFF_ATTENUATION_39		= 38,
	IFF_ATTENUATION_40		= 39,
}IFF701_ATTENUATION_type;

typedef enum IFF701_ADDRESS_type
{
	IFF_ADDRESS_1	 = 0,
	IFF_ADDRESS_2	 = 1,
	IFF_ADDRESS_3	 = 2,
	IFF_ADDRESS_4	 = 3,
	IFF_ADDRESS_5	 = 4,
	IFF_ADDRESS_6	 = 5,
	IFF_ADDRESS_7	 = 6,
	IFF_ADDRESS_8	 = 7,
	IFF_ADDRESS_9	 = 8,
	
}IFF701_ADDRESS_type;

typedef enum FLCS_TRIM
{                              
	FLCS_TRIM_1 = 0,
	FLCS_TRIM_2 = 1,
	FLCS_TRIM_3 = 2,
	FLCS_TRIM_4 = 3

}FLCS_TRIM;

typedef enum MIDS_CONTROL_KNOB_TYPE
{

	MIDS_ZERO		= 0,
	MIDS_OFF		= 1, 
	MIDS_ON		= 2,
	MIDS_HOLD		= 3	

} MIDS_CONTROL_KNOB_TYPE;

typedef enum CF_31_PAGE_TYPE
{

	CF31_OFF							=1,
	CF31_ON								=2,
	CF31_LOADER_ON						=3,
	CF31_CONFIGURATION					=4,
	CF31_CONFIGURATION_CLOSE			=5,
	CF31_FILE_OPEN						=6,
	CF31_FILE_SELECT					=7,
	CF31_FILE_SELECT_COMPLITE			=8,
	CF31_FILE_LOADINIG					=9,
	CF31_FILE_LOAD_COMPLITE				=10,
	CF31_FILE_LOAD_CONFIRM				=11,
	CF31_SELF_TEST_START				=12,
	CF31_STATE_CHECK_LOADING			=13,
	CF31_STATE_CHECK_COMPLITE			=14,
	CF31_NETWORK_CHECK_LOADING			=15,
	CF31_NETWORK_CHECK_COMPLITE			=16,
	CF31_SELF_TEST_LOADING				=17,
	CF31_SELF_TEST_COMPLITE				=18,
	CF31_SELF_TEST_END					=19,
	CF31_LOADER_OFF						=20,
	CF31_START_MENU 					=21,

}CF_31_PAGE_TYPE;

typedef enum MISC_GA_KNOB_TYPE
{

	MISC_DIM		= 0,
	MISC_MID1		= 1, 
	MISC_MID2		= 2,
	MISC_BRT		= 3,	

}MISC_GA_KNOB_TYPE;

typedef enum CAMERA_GUN_TYPE
{
	CG_OFF			= 0, 
	CAMERA			= 1,
	GUN				= 2,
} CAMERA_GUN_TYPE;

typedef enum ON_OFF_AUTO_TYPE
{
	AUTO_ON = 0,
	AUTO_AUTO = 1,
	AUTO_OFF = 2
}ON_OFF_AUTO_TYPE;

typedef enum ON_OFF_RESET_TYPE
{
	RESET_ON = 0,
	RESET = 1,
	RESET_OFF = 2
}ON_OFF_RESET_TYPE;

typedef enum ON_OFF_STBY_TYPE
{
	STBY_ON = 0,
	STBY = 1,
	STBY_OFF = 2
}ON_OFF_STBY_TYPE;

typedef enum ON_OFF_TEST_TYPE
{
	TEST_ON = 0,
	TEST_OFF = 1,
	TEST_TEST = 2
}ON_OFF_TEST_TYPE;

typedef enum ON_OFF_ORIDE_TYPE
{
	ORIDE_ON = 0,
	ORIDE_OFF = 1,
	ORIDE = 2
}ON_OFF_ORIDE_TYPE;


typedef enum UP_DOWN_TYPE
{
	UP_DOWN_UP = 0,
	UP_DOWN_DOWN = 1
}UP_DOWN_TYPE;

typedef enum OPEN_CLOSE_TYPE
{
	OEPN = 0,
	CLOSE = 1
}OPEN_CLOSE_TYPE;


typedef enum LDG_POSITION_TYPE
{
	LDG_PS_DOWN = 0,
	LDG_PS_QUARTER = 1,
	LDG_PS_HALF = 2,
	LDG_PS_UP = 3,

}LDG_POSITION_TYPE;


typedef enum OPEN_CLOSE_ORIDE_TYPE
{
	SWITCH_ORIDE = 0,
	SWITCH_OPEN = 1,
	SWITCH_CLOSE = 2
}OPEN_CLOSE_ORIDE_TYPE;

typedef enum OPEN_NORM_TYPE
{
	NORM_OPEN = 0,
	NORM = 1
}OPEN_NORM_TYPE;

typedef enum AUTO_EMERG_TYPE
{
	EMERG_AUTO = 0,
	EMERG = 1
}AUTO_EMERG_TYPE;

typedef enum DAY_NIGHT_TYPE
{
	DN_DAY = 0,
	DN_NIGHT = 1,
	DN_AUTO = 2
}DAY_NIGHT_TYPE;

typedef enum JET_STARTER_TYPE
{
	JET_STARTER_SEC = 0,
	JET_STARTER_FIR = 1,
	JET_STARTER_NORM = 2
}JET_STARTER_TYPE;

typedef enum ANTI_SKID_TYPE
{
	ANTISKID_NORM = 0,
	ANTISKID_PULSER = 1,
	ANTISKID_OFF = 2
}ANTI_SKID_TYPE;

typedef enum LDG_TAXI_LIGHT_TYPE
{
	LDG_LDG_LIGHT = 0,
	LDG_OFF = 1,
	LDG_TAXTI_LIGHT = 2
}LDG_TAXI_LIGHT_TYPE;

typedef enum FUEL_CONTROL_TYPE
{
	FUEL_CONTROL_STOP_TRANS = 0,
	FUEL_CONTROL_NORM = 1,
	FUEL_CONTROL_STOP_REFUEL = 2

}FUEL_CONTROL_TYPE;

typedef enum DUMP_TYPE
{
	DUMP = 0,
	DUMP_NORM = 1
}DUMP_TYPE;

typedef enum EXT_TRANS_TYPE
{
	EXT_TRANS_CONF_TANK = 0,
	EXT_TRANS_WING_CTR = 1,
}EXT_TRANS_TYPE;

typedef enum IFF_ANTENNA_TYPE
{
	IFF_ANTENNA_UPPER = 0,
	IFF_ANTENNA_BOTH = 1,
	IFF_ANTENNA_LOWER = 2
}IFF_ANTENNA_TYPE;

typedef enum CRYPTO_TYPE
{
	CRYPTO_HOLD = 0,
	CRYPTO_NORM = 1,
	CRYPTO_ZERO = 2
}CRYPTO_TYPE;

typedef enum RAD1_ANT_TYPE
{
	RAD1_ANT_UPPER = 0,
	RAD1_ANT_AUTO = 1,
	RAD1_ANT_LOWER = 2
}RAD1_ANT_TYPE;

typedef enum TONE_TYPE
{
	TONE_RAD1 = 0,
	TONE_OFF = 1,
	TONE_RAD2 = 2
}TONE_TYPE;

typedef enum TONE_DR_TYPE
{
	TONE_DR_OFF = 0,
	TONE_DR_RAD1 = 1,
	TONE_DR_RAD2 = 2
}TONE_DR_TYPE;

typedef enum CIPHER_TEXT_TYPE
{
	CIPHER_TEXT_ONLY = 0,
	CIPHER_TEXT_NORM = 1
}CIPHER_TEXT_TYPE;

typedef enum TF_TYPE
{
	TF_COUPLE = 0,
	TF_OFF = 1
}TF_TYPE;

typedef enum POSITION_TYPE
{
	POSITION_FWD = 0,
	POSITION_CTR = 1,
	POSITION_AFT = 2
}POSITION_TYPE;

typedef enum STICK_POSITION_TYPE
{
	STICK_CENTER = 0,
	STICK_UP_LIMIT = 1,
	STICK_DOWN_LIMIT = 2,
	STICK_LEFT_LIMIT = 3,
	STICK_RIGHT_LIMIT = 4,
	STICK_IGNORE = 5
}STICK_POSITION_TYPE;

typedef enum THROTTLE_POSITION_TYPE
{
	THROTTLE_OFF = 0,
	THROTTLE_MIL = 1,
	THROTTLE_MAX = 2,
	THROTTLE_IDLE = 3
}THROTTLE_POSITION_TYPE;

typedef enum EXTERIOR_LIGHT_TYPE
{
	EXTERIOR_LIGHT_OFF = 0,
	EXTERIOR_LIGHT_ONE = 1,
	EXTERIOR_LIGHT_TWO = 2,
	EXTERIOR_LIGHT_THREE = 3,
	EXTERIOR_LIGHT_FOUR = 4,
	EXTERIOR_LIGHT_FIVE = 5,
	EXTERIOR_LIGHT_BRT = 6,
	EXTERIOR_LIGHT_FLASH = 7
}EXTERIOR_LIGHT_TYPE;

typedef enum FORMATION_LIGHT_TYPE
{
	FORMATION_LIGHT_NORMAL = 0,
	FORMATION_LIGHT_NVIS = 1
}FORMATION_LIGHT_TYPE;

typedef enum VERT_TAIL_FLOOD_LIGHT_TYPE
{
	VERT_TAIL_FLOOD_LIGHT_BRT = 0,
	VERT_TAIL_FLOOD_LIGHT_DIM = 1,
	VERT_TAIL_FLOOD_LIGHT_OFF = 2
}VERT_TAIL_FLOOD_LIGHT_TYPE;

typedef enum RDR_ALT_TYPE
{
	RDRALT_OVERRIDE = 0,
	RDRALT_ON = 1,
	RDRALT_OFF = 2,

}RDR_ALT_TYPE;

typedef enum RADAR_MODE_TYPE
{
	RADAR_MODE_OFF = 0,
	RADAR_MODE_STBY = 1,
	RADAR_MODE_ON = 2,
	RADAR_MODE_EMERG = 3
}RADAR_MODE_TYPE;

typedef enum FDL_TYPE
{
	FDL_OFF = 0,
	FDL_POLL = 1,
	FDL_NORM = 2,
	FDL_SIL = 3,
	FDL_HOLD = 4
}FDL_TYPE;

typedef enum SEAT_ARMAMENT_TYPE
{
	SEAT_ARMAMENT_SEAT = 0,
	SEAT_ARMAMENT_OVERRIDE = 1
}SEAT_ARMAMENT_TYPE;

typedef enum IFF_MODE_TYPE
{
	IFF_MODE_MODE_B = 0,
	IFF_MODE_MODE_A = 1,
	IFF_MODE_MODE_OUT = 2,
}IFF_MODE_TYPE;

typedef enum IFF_MASTER_TYPE
{
	IFF_MASTER_LOW = 0,
	IFF_MASTER_NORM = 1,
	IFF_MASTER_EMERG = 2
}IFF_MASTER_TYPE;

typedef enum IFF_LIGHT_TYPE
{
	IFF_LIGHT_LIGHT = 0,
	IFF_LIGHT_AUDIO_REC = 1,
	IFF_LIGHT_OFF = 2
}IFF_LIGHT_TYPE;

typedef enum ANTI_FOG_TYPE
{
	ANTI_FOG_HOT = 0,
	ANTI_FOG_NORM = 1,
	ANTI_FOG_COLD = 2
}ANTI_FOG_TYPE;

typedef enum AIRCOND_TEMP_TYPE
{
	AIRCOND_TEMP_AUTO = 0,
	AIRCOND_TEMP_MAN = 1,
	AIRCOND_TEMP_OFF = 2
}AIRCOND_TEMP_TYPE;

typedef enum AIRCOND_FLOW_TYPE
{
	AIRCOND_FLOW_MAX = 0,
	AIRCOND_FLOW_NORM = 1,
	AIRCOND_FLOW_MIN = 2
}AIRCOND_FLOW_TYPE;

typedef enum ICS_SWITCH_TYPE
{
	ICS_SWITCH_MAN = 0,
	ICS_SWITCH_AUTO = 1,
	ICS_SWITCH_STBY = 2
}ICS_SWITCH_TYPE;

typedef enum CMD_BYPASS_TYPE
{
	CMD_BYPASS_BYPASS = 0,
	CMD_BYPASS_ON = 1,
	CMD_BYPASS_OFF = 2
}CMD_BYPASS_TYPE;

typedef enum ENGINE_EMERG_TYPE
{
	ENGINE_EMERG_AUTO = 0,
	ENGINE_EMERG_MAN = 1,
	ENGINE_EMERG_ISOLATE = 2
}ENGINE_EMERG_TYPE;

typedef enum ENGINE_EXTPWR_TYPE
{
	ENGINE_EXTPWR_RESET = 0,
	ENGINE_EXTPWR_NORM = 1,
	ENGINE_EXTPWR_OFF = 2
}ENGINE_EXTPWR_TYPE;

typedef enum OXYGEN_EMERG_TYPE
{
	OXYGEN_EMERG_EMERG = 0,
	OXYGEN_EMERG_NORM = 1,
	OXYGEN_EMERG_TEST_MASK = 2
}OXYGEN_EMERG_TYPE;

typedef enum OXYGEN_TYPE
{
	OXY_MAX = 0,
	OXY_NORM = 1
}OXYGEN_TYPE;

typedef enum OXYGEN_SUPPLY_TYPE
{
	OXYGEN_SUPPLY_PBG = 0,
	OXYGEN_SUPPLY_ON = 1,
	OXYGEN_SUPPLY_OFF = 2
}OXYGEN_SUPPLY_TYPE;

typedef enum DISCHARGE_TYPE
{
	DISCHARGE_DISCHARGE = 0,
	DISCHARGE_OFF = 1,
	DISCHARGE_TEST = 2

}DISCHARGE_TYPE;

typedef enum ARMT_CONTROL_TYPE
{
	ARMT_CONTROLFF = 0,
	ARMT_CONTROLRET = 1,
	ARMT_CONTROLREL = 2,
	ARMT_CONTROLOFF = 3,
	ARMT_CONTROLCOMBAT = 4,
	ARMT_CONTROLA_A = 5,
	ARMT_CONTROLA_G = 6
}ARMT_CONTROL_TYPE;

typedef enum ARMT_TYPE
{
	ARMT_ARM = 0,
	ARMT_SAFE = 1
}ARMT_TYPE;

typedef enum PULL_PUSH_TYPE
{
	PULL = 0,
	PUSH = 1
}PULL_PUSH_TYPE;


typedef enum FUEL_QTY_TYPE
{
	FUEL_QTY_BIT = 0,
	FUEL_QTY_FEED = 1,
	FUEL_QTY_INTL_WING = 2,
	FUEL_QTY_EXT_WING = 3,
	FUEL_QTY_EXT_CTR = 4,
	FUEL_QTY_CONF_TANL = 5
}FUEL_QTY_TYPE;

typedef enum UFC_MODE_TYPE
{
	UFC_MODE_A_A = 0,
	UFC_MODE_A_G = 1,
	UFC_MODE_NAV = 2,
	UFC_MODE_INST = 3
}UFC_MODE_TYPE;

typedef enum FOUR_WAY_TYPE
{
	FOUR_WAY_NONE = 0,
	FOUR_WAY_FWD = 1,
	FOUR_WAY_AFT = 2,
	FOUR_WAY_LEFT = 3,
	FOUR_WAY_RIGHT = 4,
	FOUR_WAY_PRESS = 5
}FOUR_WAY_TYPE;

typedef enum EJECT_MODE_TYPE
{
	EJECT_MODE_NORM = 0,
	EJECT_MODE_SOLO = 1,
	EJECT_MODE_AFT_INITIATE = 2
}EJECT_MODE_TYPE;

typedef enum TRRIGER_TYPE
{
	TRRIGER_NONE = 0,
	TRRIGER_HALF,
	TRRIGER_FULL
} TRRIGER_TYPE;

typedef enum LEFT_RIGHT_NORMAL_TYPE
{
	CT_LEFT = 0,
	CT_NORMAL = 1,
	CT_RIGHT = 2
}LEFT_RIGHT_NORMAL_TYPE;

typedef enum LEFT_RIGHT_DR_TYPE
{
	DR_NORMAL = 0,
	DR_LEFT = 1,
	DR_RIGHT = 2
}LEFT_RIGHT_DR_TYPE;

typedef enum ROTATION_TYPE
{
	ROTATION_NONE = 0,
	ROTATION_HORIZONTAL = 1,
	ROTATION_VERTICAL = 2
}ROTATION_TYPE;

typedef enum UFC_PWR_MODE_TYPE
{
	UFC_PWR_OFF = 0,
	UFC_PWR_N = 1,
	UFC_PWR_D
}UFC_PWR_MODE_TYPE;


typedef enum CANOPY_CONTROL_TYPE
{
	CANOPY_CTR_LOCKED = 0,
	CANOPY_CTR_DOWN = 1,
	CANOPY_CTR_HOLD = 2,
	CANOPY_CTR_UP
}CANOPY_CONTROL_TYPE;

typedef enum MULTIFUNCTION_TYPE
{
	HAT_CENTER = 0,
	HAT_UP = 1,
	HAT_DOWN = 2,
	HAT_LEFT = 3,
	HAT_RIGHT = 4
}RIGHT_MULTIFUNCTION_TYPE;

typedef enum TARGET_DESIGNATOR_CONTROL_TYPE
{
	TDC_CENTER = 0,
	TDC_UP = 1,
	TDC_DOWN = 2,
	TDC_LEFT = 3,
	TDC_RIGHT = 4
}TARGET_DESIGNATOR_CONTROL_TYPE;

typedef enum CASTLE_TYPE
{
	CASTLE_CENTER = 0,
	CASTLE_PUSH = 1,
	CASTLE_UP = 2,
	CASTLE_DOWN = 3,
	CASTLE_LEFT = 4,
	CASTLE_RIGHT = 5
}CASTLE_TYPE;

typedef enum TRIM_TYPE
{
	TRIM_CENTER = 0,
	TRIM_PUSH = 1,
	TRIM_UP = 2,
	TRIM_DOWN = 3,
	TRIM_LEFT = 4,
	TRIM_RIGHT = 5
}TRIM_TYPE;

typedef enum AUTO_ACQUISITION_TYPE
{
	AUTO_ACQUISITION_CENTER = 0,
	AUTO_ACQUISITION_FWD = 1,
	AUTO_ACQUISITION_AFT = 2,
	AUTO_ACQUISITION_DOWN = 3
}AUTO_ACQUISITION_TYPE;

typedef enum STICK_TRIGGER_TYPE
{
	TRIGGER_OFF = 0,
	TRIGGER_DVR = 1,
	TRIGGER_FIRE = 2
}STICK_TRIGGER_TYPE;

typedef enum CANOPY_JETTISON_TYPE
{
	CANOPY_JETTISON_PULL = 0,
	CANOPY_JETTISON_PUSH = 1
}CANOPY_JETTISON_TYPE;

typedef enum CANOPY_LOCK_TYPE
{
	CANOPY_LOCK = 0,
	CANOPY_UNLOCK = 1

}CANOPY_LOCK_TYPE;


typedef enum AIR_SOURCE_TYPE
{
	FLOW_SWITCH_OFF = 0,
	FLOW_SWITCH_L_ENG = 1,
	FLOW_SWITCH_BOTH = 2,
	FLOW_SWITCH_R_ENG = 3
}AIR_SOURCE_TYPE;

typedef enum RWR_COMBAT_TYPE
{
	RWR_SWITCH_COMBAT = 0,
	RWR_SWITCH_TRNG = 1
}RWR_COMBAT_TYPE;

typedef enum CMD_JETTISON_TYPE
{
	CMD_SWITCH_JETT = 0,
	CMD_SWITCH_NORM = 1
}CMD_JETTISON_TYPE;

typedef enum SYM_DECLUTTER_TYPE
{
	SYM_BRT_NORM = 0,
	SYM_BRT_REJ1 = 1,
	SYM_BRT_REJ2 = 2
}SYM_DECLUTTER_TYPE;

typedef enum FUEL_SERVICNG_TYPE
{
	SERVICING_NONE = 0,
	SERVICING_REFUEL = 1,
	SERVICING_DEFUEL = 2,

}FUEL_SERVICNG_TYPE;

typedef enum FUEL_QTY_SELECT_TYPE
{
	BIT = 0,
	FEED = 1,
	INTL_WING = 2,
	TANK = 3,
	EXT_WING = 4,
	EXT_CTR = 5,
	CONF_TANK = 6
}FUEL_QTY_SELECT_TYPE;

typedef enum COMMAND_SELECTOR_TYPE
{
	COMMAND_NORM = 0,
	COMMAND_SOLO = 1,
	AFT_INITIATE = 2
}COMMAND_SELECTOR_TYPE;


typedef enum UUT_FUNCT_TYPE
{
	GA_TACAN =0,
	AA_TACAN,
	AA_BCN_TACAN,
	INTERR,
	TCAS,
	XPDR,
	MODE_S,
	DME
}UUT_FUNCT_TYPE;


typedef enum LEFT_SLEW_TYPE
{
	SLEW_CHN = 0,
	SLEW_CODE_ALT,
	SLEW_ATTEN
}LEFT_SLEW_TYPE;

typedef enum RIGHT_SLEW_TYPE
{
	CHN = 0,
	SLEW_UP = 1,
	SLEW_DOWN
}RIGHT_SLEW_TYPE;

typedef enum CODE_TYPE
{
	CODE_VALID = 0,
	CODE_INVALID,

}CODE_TYPE;

typedef enum GROUND_PWR_TYPE
{
	GND_PWR_ON = 0,
	GND_PWR_AUTO = 1
}GROUND_PWR_TYPE;

typedef enum DIRECT_ANTENNA_TYPE
{
	HANDLE_ATTACHED = 0,
	HANDLE_DETACHED = 1,
	CABLE_ASSEMBLY_SUM = 2,
	CABLE_ASSEMBLY_DIF = 3
}DIRECT_ANTENNA_TYPE;

typedef enum START2FROM_TYPE
{
	TO_FROM_NONE = 0,
	TO_START = 1,
	FROM_STOP = 2,
	
}START2FROM_TYPE;

typedef enum T47_EMERGENCY_SW_TYPE
{
	T47_EMERGENCY_IDENT = 0,
	T47_EMERGENCY_CENTER,
	T47_EMERGENCY_DEL_135_EMERGENCY
}T47_EMERGENCY_SW_TYPE;

typedef enum BEARING_RANGE_TYPE
{
	BR_2 = 0,
	BR_6 = 1,
	BR_10 = 2,
	BR_25 = 3,
	BR_100 = 4,
	BR_130 = 5,
	BR_180 = 6,
	BR_300 = 7
}BEARING_RANGE_TYPE;

typedef enum LEFT_ATTENUATOR_CONTROL_TYPE
{
	LAC_0 = 0,
	LAC_10,
	LAC_20,
	LAC_30,
	LAC_40,
	LAC_50,
	LAC_60,
	LAC_70,
	LAC_80,
	LAC_90,
	LAC_100
}LEFT_ATTENUATOR_CONTROL_TYPE;


typedef enum RIGHT_ATTENUATOR_CONTROL_TYPE
{
	RAC_0 = 0,
	RAC_1,
	RAC_2,
	RAC_3,
	RAC_4,
	RAC_5,
	RAC_6,
	RAC_7,
	RAC_8,
	RAC_9,
	RAC_10
}RIGHT_ATTENUATOR_CONTROL_TYPE;


typedef enum MB_SW_TYPE
{
	MB_400 = 0,
	MB_1300,
	MB_3000

}MB_SW_TYPE;

typedef enum FUNCTION_SW_TYPE
{
	FSW_ILS = 0,
	FSW_GS,
	FSW_LOC,
	FSW_VOR,
	FSW_MB
}FUNCTION_SW_TYPE;


typedef enum LOC_SW_TYPE
{
	LSW_OC = 0,
	LSW_L1,
	LSW_L2,
	LSW_R1,
	LSW_R2,
}LOC_SW_TYPE;


typedef enum GS_SW_TYPE
{
	GSW_OC = 0,
	GSW_MINUS_ONE,
	GSW_MINUS_TWO,
	GSW_PLUS_ONE,
	GSW_PLUS_TWO
}GS_SW_TYPE;


typedef enum W12A1_SELECT_TYPE
{
	W12A1_1 = 0,
	W12A1_2,
	W12A1_3,
	W12A1_4,
	W12A1_5,
	W12A1_6,
	W12A1_7,
	W12A1_8,
	W12A1_9,
	W12A1_10

}W12A1_SELECT_TYPE;

typedef enum W12A1_TEST_TYPE
{
	W12A1_TEST = 0,
	W12A1_CENTER = 1,
	W12A1_RESET = 2

}W12A1_TEST_TYPE;


typedef enum W12A1_START_TYPE
{
	W12A1_START_A = 0,
	W12A1_START_OFF = 1,
	W12A1_START_B = 2,

}W12A1_START_TYPE;

typedef enum W12A1_MODE_TYPE
{
	W12A1_MODE_A = 0,
	W12A1_MODE_B,
	W12A1_MODE_C,
	W12A1_MODE_D,
	W12A1_MODE_E,
	W12A1_MODE_F
}W12A1_MODE_TYPE;

typedef enum VD_SELECTOR_TYPE
{
	VD_SELF_TEST_OFF = 0,
	VD_SELF_CABLE4OHM,
	VD_SELF_CABLE700OHM,
	VD_SELF_SV,
	VD_SELF_EJ,
	VD_SELF_24V
}VD_SELECTOR_TYPE;

typedef enum VD_TEST_RESET_TYPE
{
	VD_TEST = 0,
	VD_OFF,
	VD_RESET
}VD_TEST_RESET_TYPE;

typedef enum VD_ACTL_VALUE_TYPE
{
	VD_ACTL_1 = 0,
	VD_ACTL_OFF,
	VD_ACTL_2,
}VD_ACTL_VALUE_TYPE;


typedef enum ROTATE_TYPE
{
	R_NOMAL = 0,
	R_ROTATE = 1
}ROTATE_TYPE;


typedef enum AUTO_TEST_MANUAL_TYPE
{
	TEST = 0,
	AUTO2,
	MANUAL
}AUTO_TEST_MANUAL_TYPE;

typedef enum AN_APM480_LEFT_SLEW_TYPE
{
	CODE_ALT = 0,
	RANGE,
	ATTEN
}AN_APM480_LEFT_SLEW_TYPE;

typedef enum IDENT_EMERGENCY_TYPE
{
	AN_APM480_IDENT = 0,
	AN_APM480_EMERG
}IDENT_EMERGENCY_TYPE;

typedef enum AN_APM480_MODE_TYPE
{
	MODE_1_2_3A_C_4 = 0,
	MODE_S_TCAS,
	MODE_XPDR
}AN_APM480_MODE_TYPE;

typedef enum AN_APM480_XPDR_TYPE
{
	AN_APM480_XPDR = 0,
	AN_APM480_INTERR
}AN_APM480_XPDR_TYPE;

typedef enum VALID_TYPE
{
	VALID = 0,
	INVALID
}VALID_TYPE;

typedef enum AN_APM480_PWR_CHG_TYPE
{
	AN_APM480_ON = 0,
	AN_APM480_OFF_PWR_CHG
}AN_APM480_PWR_CHG_TYPE;

typedef enum WEIGHT_ON_OFF_WHEELS_TYPE
{
	WEIGHT_OFF_WHEELS = 0,
	NORMAL,
	WEIGHT_ON_WHEELS
}WEIGHT_ON_OFF_WHEELS_TYPE;

typedef enum LOCK_RELEASED_TYPE
{
	LOCK = 0,
	RELEASED
}LOCK_RELEASED_TYPE;

typedef enum UP_CENTER_DOWN_TYPE
{
	UP_ = 0,
	CENTER = 1,
	DOWN_ = 2
}UP_CENTER_DOWN_TYPE;

typedef enum AN_ALM288_PAYLOAD_TYPE
{
	UNLD = 0,
	RF1,
	RF2,
	RR170,
	RR180,
	MJU7,
	MJU10,
	M206,
}AN_ALM288_PAYLOAD_TYPE;

typedef enum AN_ALM288_DATA_TYPE
{
	COUNT = 0,
	RESET_ALE_40,
	LIMITER,
	BAD_GND,
	NO_FIRE,
	SEQ,
	GO_NOGO
}AN_ALM288_DATA_TYPE;

typedef enum AN_ALM288_MODE_TYPE
{
	AN_ALM288_OFF = 0,
	AN_ALM288_SV_BIT,
	AN_ALM288_FIRE_TEST,
	AN_ALM288_MISSFIRE,
	AN_ALM288_JETT,
}AN_ALM288_MODE_TYPE;

typedef enum AN_ALM288_ALE_TYPE
{
	AN_ALM288_ALE_40 = 0,
	AN_ALM288_ALE_45,
	AN_ALM288_ALE_47,
}AN_ALM288_ALE_TYPE;

typedef enum W6_CABLE_TYPE
{
	W6_CABLE_SV = 0,
	W6_CABLE_CENTER = 1,
	W6_CABLE_FIRE
}W6_CABLE_TYPE;

typedef enum BLEED_AIR_ENG_TYPE
{
	BLEED_AIR_ENG_L_ENG = 0,
	BLEED_AIR_ENG_NORM,
	BLEED_AIR_ENG_R_ENG
}BLEED_AIR_ENG_TYPE;

typedef enum BLEED_AIR_ENG_LOOP_TYPE
{
	BLEED_AIR_ENG_LOOP_A = 0,
	BLEED_AIR_ENG_LOOP_NORM,
	BLEED_AIR_ENG_LOOP_B
}BLEED_AIR_ENG_LOOP_TYPE;

typedef enum GND_CHECK_PANEL_NORM_TEST_TYPE
{
	GND_CHECK_PANEL_NORM = 0,
	GND_CHECK_PANEL_TEST
}GND_CHECK_PANEL_NORM_TEST_TYPE;

typedef enum JFS_SW_TYPE
{
	JFS_SW_PRIME = 0,
	JFS_SW_NORM
}JFS_SW_TYPE;

typedef enum BOOST_PUMP_TYPE
{
	BOOST_PUMP_ON = 0,
	BOOST_PUMP_NORM
}BOOST_PUMP_TYPE;

typedef enum FUEL_LEVEL_TEST_TYPE
{
	FUEL_LEVEL_TEST_UPPER = 0,
	FUEL_LEVEL_TEST_NORM,
	FUEL_LEVEL_TEST_LOWER,
}FUEL_LEVEL_TEST_TYPE;

typedef enum FUEL_TEST_SW_TYPE
{
	FUEL_TEST_LEFT = 0,
	FUEL_TEST_NORM,
	FUEL_TEST_RIGHT
}FUEL_TEST_SW_TYPE;

typedef enum HOT_FUEL_TEST_TYPE
{
	HOT_FUEL_TEST_LEFT = 0,
	HOT_FUEL_TEST_NORM
}HOT_FUEL_TEST_TYPE;

typedef enum VALVE_OPEN_TEST_TYPE 
{
	VALVE_OPEN_TEST_REST = 0,
	VALVE_OPEN_TEST_NORM
}VALVE_OPEN_TEST_TYPE;

typedef enum TRANSFER_PUMP_TYPE
{
	TRANSFER_PUMP_OFF = 0,
	TRANSFER_PUMP_INTERNAL_TANK1,
	TRANSFER_PUMP_INTERNAL_L_WING,
	TRANSFER_PUMP_INTERNAL_R_WING,
	TRANSFER_PUMP_CONF_TANK_L_FWD,
	TRANSFER_PUMP_CONF_TANK_L_AFT,
	TRANSFER_PUMP_CONF_TANK_R_FWD,
	TRANSFER_PUMP_CONF_TANK_R_AFT
}TRANSFER_PUMP_TYPE;

typedef enum LVL_CONT_VALVE_TYPE
{
	LVL_CONT_VALVE_OFF = 0,
	LVL_CONT_VALVE_INTERNAL_TK1_XFR,
	LVL_CONT_VALVE_INTERNAL_TK1_RFL,
	LVL_CONT_VALVE_INTERNAL_TANK2,
	LVL_CONT_VALVE_INTERNAL_TANK3,
	LVL_CONT_VALVE_INTERNAL_L_WING,
	LVL_CONT_VALVE_INTERNAL_R_WING,
	LVL_CONT_VALVE_EXT_L_WING,
	LVL_CONT_VALVE_EXT_CTR,
	LVL_CONT_VALVE_EXT_R_WING,
	LVL_CONT_VALVE_CONF_TANK_L_FWD,
	LVL_CONT_VALVE_CONF_TANK_L_AFT,
	LVL_CONT_VALVE_CONF_TANK_R_FWD,
	LVL_CONT_VALVE_CONF_TANK_R_AFT
}LVL_CONT_VALVE_TYPE;

typedef enum FWD_AFT_TYPE
{
	FWD = 0,
	AFT
}FWD_AFT_TYPE;

typedef enum ROUNDS_LIMITER_TYPE
{
	RNDS_LIMIT = 0,
	NO_LIMIT
}ROUNDS_LIMITER_TYPE;

typedef enum ROUNDS_LIMITER_PRESET_TYPE
{
	RNDS_LIMIT_PRESET_900 = 0,
	RNDS_LIMIT_PRESET_850,
	RNDS_LIMIT_PRESET_780,
}ROUNDS_LIMITER_PRESET_TYPE;

typedef enum SAFETY_LEVER_TYPE
{
	SAFETY_LOCK = 0,
	SAFETY_UNLOCK
}SAFETY_LEVER_TYPE;

typedef enum ATTACH_TYPE
{
	ATTACHED = 0,
	DETACHED
}ATTACH_TYPE;

typedef enum BOMB_INTERVALOMETER_TYPE
{
	SALVO_ARM = 0,
	SALVO_ALL,
	SALVO_SAFE,
	BOMB_SINGLE_ARM,
	BOMB_SINGLE_1,
	BOMB_SINGLE_2,
	BOMB_SINGLE_3,
	BOMB_SINGLE_4,
	BOMB_SINGLE_5,
	BOMB_SINGLE_6,
	BOMB_SINGLE_SAFE,
	BOMB_RIPPLE_ARM,
	BOMB_RIPPLE_1,
	BOMB_RIPPLE_2,
	BOMB_RIPPLE_3,
	BOMB_RIPPLE_4,
	BOMB_RIPPLE_5,
	BOMB_RIPPLE_6,
	BOMB_RIPPLE_SAFE
}BOMB_INTERVALOMETER_TYPE;

typedef enum ENGAGE_TYPE
{
	ENGAGE = 0,
	DISENGAGE
}ENGAGE_TYPE;

typedef enum UNIVERSAL_RECPTACLE_TESTER_POWER_TYPE
{
	URT_POWER_ON = 0,
	URT_POWER_OFF_CHG
}UNIVERSAL_RECPTACLE_TESTER_POWER_TYPE;

typedef enum UNIVERSAL_RECPTACLE_TESTER_CONTACT_TYPE
{
	URT_CONTACT_NORMAL = 0,
	URT_CONTACT_CONNECT,
	URT_CONTACT_DISCONNECT,
}UNIVERSAL_RECPTACLE_TESTER_CONTACT_TYPE;

typedef enum UNIVERSAL_RECPTACLE_TESTER_ELBOW_TYPE
{
	URT_ELBOW_NORMAL_POSITION = 0,
	URT_ELBOW_OUTSIDE_POSITION
}UNIVERSAL_RECPTACLE_TESTER_ELBOW_TYPE;

typedef enum OVLD_WRN_TYPE
{
	OVLD_WRN_RESET = 0,
	OVLD_WRN_NORM
}OVLD_WRN_TYPE;

typedef enum RICP_TONE_TYPE
{
	RICP_TONE_RAD1,
	RICP_TONE_OFF,
	RICP_TONE_RAD2
}RICP_TONE_TYPE;

typedef enum SOLENOID_COIL_TYPE
{
	JFS_START_CONTROL_SW = 0,
	DUMP_SW,
	GND_PWR_1_SW,
	GND_PWR_2_SW,
	GND_PWR_3_SW,
	GND_PWR_4_SW,
	GND_PWR_PACS_SW,
	GND_PWR_ADCP_AIU,
	ARMAMENT_SAFETY_OVERRIDE_SW,
	ANTI_FOG_SW,
	EMERG_GEN_SW,

	SOLENOIDE_COIL_END
	
}SOLENOID_COIL_TYPE;

typedef enum LCS_PUMP_TYPE
{
	LCS_PUMP_OFF = 0,
	LCS_PUMP_TEST,
	LCS_PUMP_NORMAL,
}LCS_PUMP_TYPE;

typedef enum VENT_OFF_FLOW_TYPE
{
	VENT_OFF_FLOW_VENT = 0,
	VENT_OFF_FLOW_OFF,
	VENT_OFF_FLOW_FLOW,
}VENT_OFF_FLOW_TYPE;

typedef enum IFR_MODE_TYPE
{
	IFR_OFF = 0,
	IFR_1020,
	IFR_MORSE

}IFR_MODE_TYPE;

typedef enum IFR_LOC_TYPE
{
	IFR_LOC_CENTER = 0,
	IFR_LOC_LEFT1,
	IFR_LOC_LEFT2,
	IFR_LOC_RIGHT1,
	IFR_LOC_RIGHT2
}IFR_LOC_TYPE;

typedef enum IFR_GS_TYPE
{
	IFR_GS_CENTER = 0,
	IFR_GS_UP1,
	IFR_GS_UP2,
	IFR_GS_DOWN1,
	IFR_GS_DOWN2
}IFR_GS_TYPE;

typedef enum IFR_DEL_TYPE
{
	IFR_DEL_BLANK = 0,
	IFR_DEL_90,
	IFR_DEL_90_150,
	IFR_DEL_150
}IFR_DEL_TYPE;

typedef enum IFR_PAGE_TYPE
{
	IFR_NONE = 0,
	IFR_LOC_PAGE = 1,
	IFR_GS_PAGE = 2

}IFR_PAGE_TYPE;

typedef enum ON_OFF_START_TYPE
{
	START_OFF = 0,
	START_ON = 1,
	START_START = 2

}ON_OFF_START_TYPE;

typedef enum RADAR_POSITION_TYPE
{
	RP_NONE = 0,
	RP_FWD_LEFT = 1,
	RP_FWD_RIGHT = 2,
	RP_AFT_LEFT = 3,
	RP_AFT_RIGHT = 4,

}RADAR_POSITION_TYPE;

typedef enum RADAR_TARGET_TYPE
{
	RP_TARGET_NONE = 0,
	RP_TARGET_ONE = 1,
	RP_TARGET_TWO = 2,
	RP_TARGET_THREE = 3,
	RP_TARGET_FOUR = 4,
	RP_TARGET_FIVE = 5,
	RP_TARGET_SIX = 6,
	RP_TARGET_SEVEN = 7
}RADAR_TARGET_TYPE;

typedef enum ON_CENTER_OFF_TYPE
{
	ON_CENTER_OFF_CENTER = 0,
	ON_CENTER_OFF_OFF = 1,
	ON_CENTER_OFF_ON = 2

}ON_CENTER_OFF_TYPE;

typedef enum HUD_VISIBILITY_TYPE : byte
{
	Visible = 0,
	Hidden = 1,
	Collapsed = 2

}HUD_VISIBILITY_TYPE;

typedef enum UP_DOWN_CTR_TYPE
{
	UP_DOWN_CTR_UP = 0,
	UP_DOWN_CTR_CENTER = 1,
	UP_DOWN_CTR_DOWN = 2

}UP_DOWN_CTR_TYPE;

typedef enum LG_DOOR_TYPE
{
	LG_DOOR_CLOSE = 0,
	LG_DOOR_MIDDLE,
	LG_DOOR_OPEN,

}NLG_FWD_DOOR_TYPE;

typedef enum HYD_COMPENSATOR_VALVE_TYPE
{
	HYD_COMPENSATOR_VALVE_CLOSE = 0,
	HYD_COMPENSATOR_VALVE_OPEN_1500,
	HYD_COMPENSATOR_VALVE_OPEN_3000,

}HYD_COMPENSATOR_VALVE_TYPE;

#pragma pack(pop)

