#pragma once

// User Message

#define UM_UPDATE_COCKPIT_LIST				WM_USER + 101
#define UM_UPDATE_COCKPITIO_LIST			WM_USER + 102
#define UM_SELECT_SETTING					WM_USER + 103
#define UM_UPDATE_LOGEVENT					WM_USER + 104
#define UM_FUNCTION_RUDDER					WM_USER + 105


typedef enum TRIM_COMMAND
{
	TC_NONE = 0,
	TC_INIT,
	TC_LEFT,
	TC_RIGHT,
	TC_FRONT,
	TC_REAR,
} TRIM_COMMAND;
//
//
//typedef enum COCKPITTYPE
//{
//	CT_LEFT = 1,
//	CT_MAIN,
//	CT_RIGHT,
//} COCKPITTYPE;
//
//typedef enum COCKPITIOTYPE
//{
//	CIO_DI = 1,
//	CIO_DO,
//	CIO_AI,
//	CIO_AO,
//} COCKPITIOTYPE;

/*typedef enum IOBOARD_ID
{
	
}IOBOARD_ID;*/

//#define IOBOARD_ID_COUNT 23

// Left Console LRU 문자열
static LPCTSTR alpszLEFTLRUType[] =
{
	_T("GND PWR PANEL"),
	_T("EMERGENCY AIR REFUELING"),
	_T("IFF ANT SEL SWITCH"),
	_T("SEAT ADJUST SWITCH"),
	_T("FLYUP ENABLE SWITCH"),
	_T("CANOPY-EMERG JETT HANDLE"),
	_T("ANTI-G PANEL"),
	_T("REMOTE INTERCOMMUNICATION CONTROL PANEL"),
	_T("FUEL CONTROL PANEL"),
	_T("MISC CONTROL PANEL"),
	_T("CAS CONTROL PANEL"),
	_T("EXT LT PANEL"),
	_T("SENSOR CONTROL PANEL"),
};

// Center Instrument LRU 문자열
static LPCTSTR alpszCENTERLRUType[] =
{
	_T("GND PWR PANEL"),
	_T("EMERGENCY AIR REFUELING"),
	_T("IFF ANT SEL SWITCH"),
	_T("SEAT ADJUST SWITCH"),
	_T("FLYUP ENABLE SWITCH"),
	_T("CANOPY-EMERG JETT HANDLE"),
	_T("ANTI-G PANEL"),
	_T("REMOTE INTERCOMMUNICATION CONTROL PANEL"),
	_T("FUEL CONTROL PANEL"),
	_T("MISC CONTROL PANEL"),
	_T("CAS CONTROL PANEL"),
	_T("EXT LT PANEL"),
	_T("SENSOR CONTROL PANEL"),
};

// Right Console LRU 문자열
static LPCTSTR alpszRIGHTLRUType[] =
{
	_T("GND PWR PANEL"),
	_T("EMERGENCY AIR REFUELING"),
	_T("IFF ANT SEL SWITCH"),
	_T("SEAT ADJUST SWITCH"),
	_T("FLYUP ENABLE SWITCH"),
	_T("CANOPY-EMERG JETT HANDLE"),
	_T("ANTI-G PANEL"),
	_T("REMOTE INTERCOMMUNICATION CONTROL PANEL"),
	_T("FUEL CONTROL PANEL"),
	_T("MISC CONTROL PANEL"),
	_T("CAS CONTROL PANEL"),
	_T("EXT LT PANEL"),
	_T("SENSOR CONTROL PANEL"),
};
//
//typedef enum LRU_BUY
//{
//	LB_ANTOS = 0,
//	LB_NEXWARE,
//	LB_COMMERCIAL,
//	LB_NONE,
//} LRU_BUY;
//
//typedef struct LRU_STATUS
//{
//	int nLRUID;
//	int nIOBoardID;
//	LRU_BUY eLRUBuy;
//	DEVICE_POSITION eCockpitType;
//
//} LRU_STATUS;
